// fs-utils.ts – safe file operations for SyncEngine
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { SyncConfig } from "./config.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

// Protected root-level files that must not be overwritten without --force-root
export const protectedFiles = new Set([
  ".gitignore",
  "turbo.json",
  "yarn.lock",
  ".architecture/",
  ".architecture/manifest.yaml",
  ".architecture/generator.config.yaml",
  "README.md",
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
  ".env.test",
]);

/**
 * Compute SHA-256 hash of a string – used for change detection.
 */
function contentHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

/**
 * Determine whether a file was generated by the sync tool.
 */
export function isGeneratedFile(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

/**
 * Check if a path points to a protected root file.
 */
export function isProtectedRoot(filePath: string, config: SyncConfig): boolean {
  const relative = path.relative(config.workspaceRoot, filePath);
  const isRootLevel =
    !relative.startsWith("packages/") &&
    !relative.startsWith("tools/") &&
    !relative.startsWith("apps/");
  return (
    isRootLevel &&
    Array.from(protectedFiles).some(
      (f) => relative.endsWith(f) || relative.includes(f),
    )
  );
}

/**
 * Atomic, idempotent file writer.
 * Returns one of: created, updated, unchanged, skipped, protected.
 *
 * Protection rules:
 *   - Root protected files: require --force-root (NOT --force)
 *   - Non-generated package files: require --force
 */
export async function safeWriteFileAtomic(
  filePath: string,
  content: string,
  config: SyncConfig,
  report?: { record: (type: string, target: string, message: string) => void },
  skipGeneratedCheck: boolean = false,
): Promise<"created" | "updated" | "unchanged" | "skipped" | "protected"> {
  const { dryRun, force, forceRoot, logger, workspaceRoot } = config;
  const relativePath = path.relative(workspaceRoot, filePath);

  let exists = false;
  let currentContent = "";
  let currentHash = "";
  try {
    currentContent = await fs.readFile(filePath, "utf8");
    currentHash = contentHash(currentContent);
    exists = true;
  } catch (e: any) {
    if (e.code !== "ENOENT") throw e;
  }

  const newHash = contentHash(content);
  if (exists && currentHash === newHash) {
    logger.debug(`unchanged ${relativePath}`);
    return "unchanged";
  }

  if (dryRun) {
    const action = exists ? "update" : "create";
    logger.info(`[DRY-RUN] would ${action} ${relativePath}`);
    return exists ? "updated" : "created";
  }

  // Root files require --force-root specifically — --force alone is not enough
  if (isProtectedRoot(filePath, config) && !forceRoot) {
    logger.warn(`skipped (root protected, use --force-root) ${relativePath}`);
    if (report) report.record("blocked", filePath, "Root file protected");
    return "protected";
  }

  if (
    exists &&
    !force &&
    !forceRoot &&
    !skipGeneratedCheck &&
    !isGeneratedFile(currentContent)
  ) {
    logger.warn(
      `skipped (protected non-generated file, use --force) ${relativePath}`,
    );
    return "skipped";
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tmpPath = `${filePath}.tmp.${Date.now()}`;
  await fs.writeFile(tmpPath, content, { encoding: "utf8" });
  try {
    await fs.rename(tmpPath, filePath);
    const status = exists ? "updated" : "created";
    logger.info(`${status} ${relativePath}`);
    return status;
  } catch (err: any) {
    if (err.code === "EXDEV") {
      try {
        await fs.copyFile(tmpPath, filePath);
        await fs.unlink(tmpPath);
        const status = exists ? "updated" : "created";
        logger.info(`${status} ${relativePath}`);
        return status;
      } catch (copyErr) {
        logger.warn(`EXDEV fallback failed for ${relativePath}: ${copyErr}`);
      }
    }
    await fs.unlink(tmpPath).catch(() => {});
    throw err;
  }
}

/**
 * Simple wrapper that forwards to safeWriteFileAtomic without a report.
 */
export async function safeWriteFile(
  filePath: string,
  content: string,
  config: SyncConfig,
  skipGeneratedCheck: boolean = false,
): Promise<"created" | "updated" | "unchanged" | "skipped" | "protected"> {
  return safeWriteFileAtomic(
    filePath,
    content,
    config,
    undefined,
    skipGeneratedCheck,
  );
}
