import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import type { SyncConfig } from './config.js';

const GENERATED_MARKER = '// @generated by @hexagen/sync';

export function isGeneratedFile(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

export function isProtectedRoot(filePath: string, config: SyncConfig): boolean {
  const protectedFiles: readonly string[] = config.manifest?.generator?.sync
    ?.protectedRootFiles ?? [
    'package.json',
    'tsconfig.json',
    'tsconfig.base.json',
    '.architecture.yaml',
    'turbo.json',
    'yarn.lock',
    '.gitignore',
    'README.md',
    '.env*',
  ];

  const relative = path.relative(config.workspaceRoot, filePath);
  const isRootLevel =
    !relative.startsWith('packages/') && !relative.startsWith('tools/');
  return (
    isRootLevel &&
    protectedFiles.some(
      (f: string) => relative.endsWith(f) || relative.includes(f)
    )
  );
}

function contentHash(content: string): string {
  return crypto.createHash('sha256').update(content).digest('hex');
}

export async function safeWriteFile(
  filePath: string,
  content: string,
  config: SyncConfig
): Promise<'created' | 'updated' | 'unchanged' | 'skipped' | 'protected'> {
  const { dryRun, force, logger, workspaceRoot } = config;
  const relativePath = path.relative(workspaceRoot, filePath);

  let exists = false;
  let currentContent = '';
  let currentHash = '';

  try {
    currentContent = await fs.readFile(filePath, 'utf8');
    currentHash = contentHash(currentContent);
    exists = true;
  } catch (e) {
    if (!(e instanceof Error && 'code' in e && e.code === 'ENOENT')) {
      throw e;
    }
  }

  const newHash = contentHash(content);

  // Early exit: no change needed
  if (exists && currentHash === newHash) {
    logger.debug(`unchanged ${relativePath}`);
    return 'unchanged';
  }

  // Dry-run simulation – no disk mutation allowed
  if (dryRun) {
    const action = exists ? 'update' : 'create';
    logger.info(`[DRY-RUN] would ${action} ${relativePath}`);
    return exists ? 'updated' : 'created';
  }

  // Protection checks (after dry-run)
  if (isProtectedRoot(filePath, config) && !force) {
    logger.warn(`skipped (root protected, use --force) ${relativePath}`);
    return 'protected';
  }

  if (exists && !force && !isGeneratedFile(currentContent)) {
    logger.warn(
      `skipped (protected non-generated, use --force) ${relativePath}`
    );
    return 'skipped';
  }

  // Actual mutation – only reached if dryRun=false and protections pass
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');

  const status = exists ? 'updated' : 'created';
  logger.info(`${status} ${relativePath}`);
  return status;
}
