// fs-utils.ts – safe file operations for SyncEngine
import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { SyncConfig } from "./config.js";
import { matchesScope } from "./scope-filter.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

// Protected root-level files that must not be overwritten without --force-root.
// JSON files (package.json, tsconfig.base.json) are included here because
// they cannot carry the `// @generated by @hexagen/sync` marker that guards
// non-root files — without root-level protection, sync --force would silently
// clobber hand-written workspace config (lost devDependencies, lost
// workspaces array, lost packageManager, etc.). See `isProtectedRoot` below
// and the skipGeneratedCheck bypass in `safeWriteFileAtomic`.
export const protectedFiles = new Set([
  ".gitignore",
  ".yarnrc.yml",
  "SETUP.md",
  "package.json",
  "tsconfig.base.json",
  "turbo.json",
  "yarn.lock",
  ".architecture/",
  ".architecture/manifest.yaml",
  ".architecture/generator.config.yaml",
  "README.md",
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
  ".env.test",
]);

/**
 * Compute SHA-256 hash of a string – used for change detection.
 */
function contentHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

/**
 * Determine whether a file was generated by the sync tool.
 */
export function isGeneratedFile(content: string): boolean {
  return content.includes(GENERATED_MARKER);
}

/**
 * Check if a path points to a protected root file.
 */
export function isProtectedRoot(filePath: string, config: SyncConfig): boolean {
  const relative = path.relative(config.workspaceRoot, filePath);
  const isRootLevel =
    !relative.startsWith("packages/") &&
    !relative.startsWith("tools/") &&
    !relative.startsWith("apps/");
  return (
    isRootLevel &&
    Array.from(protectedFiles).some(
      (f) => relative.endsWith(f) || relative.includes(f),
    )
  );
}

/**
 * Atomic, idempotent file writer.
 * Returns one of: created, updated, unchanged, skipped, protected.
 *
 * Protection rules:
 *   - Root protected files: require --force-root (NOT --force)
 *   - Non-generated package files: require --force-root (hand-written files
 *     are preserved even under --force; --force only regenerates files
 *     carrying the @generated marker)
 */
export async function safeWriteFileAtomic(
  filePath: string,
  content: string,
  config: SyncConfig,
  report?: { record: (type: string, target: string, message: string) => void },
  skipGeneratedCheck: boolean = false,
): Promise<"created" | "updated" | "unchanged" | "skipped" | "protected"> {
  const { dryRun, forceRoot, logger, workspaceRoot, only } = config;
  const relativePath = path.relative(workspaceRoot, filePath);

  // `--only` scope filter (checked first, before any disk read): when scope
  // patterns are set, a file outside all of them is skipped without being read
  // or written, in dry-run and real runs alike. Conservative direct-targets
  // semantics — no dependency fan-out (see scope-filter.ts).
  if (only && only.length > 0 && !matchesScope(relativePath, only)) {
    logger.debug(`skipped (outside --only) ${relativePath}`);
    return "skipped";
  }

  let exists = false;
  let currentContent = "";
  let currentHash = "";
  try {
    currentContent = await fs.readFile(filePath, "utf8");
    currentHash = contentHash(currentContent);
    exists = true;
  } catch (e: unknown) {
    if (
      !(
        e instanceof Error &&
        "code" in e &&
        (e as { code?: string }).code === "ENOENT"
      )
    )
      throw e;
  }

  const newHash = contentHash(content);
  if (exists && currentHash === newHash) {
    logger.debug(`unchanged ${relativePath}`);
    return "unchanged";
  }

  // Protection checks run BEFORE the dry-run preview below. A protected file
  // is skipped in a real run, so `--dry-run` must report it as a skip too —
  // not as "would update". (Previously the dry-run branch returned first, so a
  // preview inflated its change set with every protected root and hand-written
  // file that a real run would leave untouched.) The protection logic itself is
  // dry-run-agnostic: `dryRun` only changes the log verb, never the outcome.

  // Root files require --force-root specifically — --force alone is not enough
  if (isProtectedRoot(filePath, config) && !forceRoot) {
    const verb = dryRun ? "[DRY-RUN] would skip" : "skipped";
    logger.warn(`${verb} (root protected, use --force-root) ${relativePath}`);
    if (report) report.record("blocked", filePath, "Root file protected");
    return "protected";
  }

  if (
    exists &&
    !forceRoot &&
    !skipGeneratedCheck &&
    !isGeneratedFile(currentContent)
  ) {
    // Hand-written non-generated file: preserve even with --force.
    // --force was historically permissive here, but that caused silent
    // clobbering of user-authored tsconfigs, barrels, package.json files,
    // and app configs during self-regen in CI. Only --force-root can now
    // overwrite hand-written content (reserved for protected root files
    // and deliberate mass-migrations).
    const verb = dryRun ? "[DRY-RUN] would skip" : "skipped";
    logger.warn(
      `${verb} (hand-written, use --force-root to overwrite) ${relativePath}`,
    );
    return "skipped";
  }

  if (dryRun) {
    const action = exists ? "update" : "create";
    logger.info(`[DRY-RUN] would ${action} ${relativePath}`);
    return exists ? "updated" : "created";
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  const tmpName = `.${path.basename(filePath)}.${crypto.randomUUID()}.tmp`;
  const tmpPath = path.join(path.dirname(filePath), tmpName);
  await fs.writeFile(tmpPath, content, { encoding: "utf8" });
  try {
    await fs.rename(tmpPath, filePath);
    const status = exists ? "updated" : "created";
    logger.info(`${status} ${relativePath}`);
    return status;
  } catch (err: unknown) {
    if (
      err instanceof Error &&
      "code" in err &&
      (err as { code?: string }).code === "EXDEV"
    ) {
      try {
        await fs.copyFile(tmpPath, filePath);
        await fs.unlink(tmpPath);
        const status = exists ? "updated" : "created";
        logger.info(`${status} ${relativePath}`);
        return status;
      } catch (copyErr) {
        logger.warn(`EXDEV fallback failed for ${relativePath}: ${copyErr}`);
      }
    }
    await fs.unlink(tmpPath).catch(() => {});
    throw err;
  }
}

/**
 * Simple wrapper that forwards to safeWriteFileAtomic without a report.
 */
export async function safeWriteFile(
  filePath: string,
  content: string,
  config: SyncConfig,
  skipGeneratedCheck: boolean = false,
): Promise<"created" | "updated" | "unchanged" | "skipped" | "protected"> {
  return safeWriteFileAtomic(
    filePath,
    content,
    config,
    undefined,
    skipGeneratedCheck,
  );
}
