import { afterEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ObservedReport } from "@hexagen/shared";
import {
  observe,
  observeCommander,
  runObserve,
} from "../../../src/commands/observe/index.js";
import { globToRegExp } from "../../../src/commands/shared/glob.js";

const tmpDirs: string[] = [];

async function put(root: string, rel: string, body: string): Promise<void> {
  const file = path.join(root, rel);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, body, "utf8");
}

function git(root: string, ...args: string[]): void {
  execFileSync(
    "git",
    ["-c", "user.name=t", "-c", "user.email=t@example.com", ...args],
    { cwd: root, stdio: "ignore" },
  );
}

async function commitAll(root: string): Promise<void> {
  git(root, "init", "-q");
  git(root, "add", "-A");
  git(root, "commit", "-q", "-m", "fixture", "--no-gpg-sign");
}

async function mkRoot(): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "hexagen-observe-"));
  tmpDirs.push(root);
  return root;
}

/** No workspaces, mixed languages, scoped + mismatched names, vendored deps. */
async function messyRepo(): Promise<string> {
  const root = await mkRoot();
  await put(root, "package.json", JSON.stringify({ name: "@acme/solo" }));
  await put(root, "src/index.ts", "export const a = 1;\n");
  await put(root, "src/util.js", "module.exports = 1;\n");
  await put(root, "lib/helper.py", "x = 1\n");
  await put(root, "cmd/main.go", "package main\n");
  await put(root, "go.mod", "module example.test/m\n");
  await put(root, "Makefile", "all:\n");
  await put(
    root,
    "tools/odd-dir/package.json",
    JSON.stringify({ name: "totally-different" }),
  );
  await put(root, "tools/odd-dir/index.js", "1;\n");
  await put(root, "tools/odd-dir/.gitignore", "cache/\n"); // nested gitignore
  await put(root, "tools/odd-dir/cache/c.js", "1;\n");
  await put(root, "vendor/x/package.json", JSON.stringify({ name: "vend" }));
  await put(root, "node_modules/dep/package.json", '{"name":"dep"}');
  await put(root, "node_modules/dep/index.js", "1;\n");
  await put(root, ".gitignore", "dist/\n*.log\n");
  await put(root, "dist/out.js", "1;\n");
  await put(root, "debug.log", "x\n");
  await put(root, "gen/api.ts", "// @generated by codegen\nexport {};\n");
  await put(root, "src/late.ts", "\n\n\n\n\n// @generated (too late)\n");
  await put(root, "pb/a.pb.go", "package pb\n");
  await put(root, ".gitattributes", "*.pb.go linguist-generated=true\n");
  await put(
    root,
    "CODEOWNERS",
    "# comment\n/legacy/ @team-a @team-b\n*.md @docs\n/tools/odd-dir @ops\n",
  );
  await put(root, "legacy/old.js", "1;\n");
  await commitAll(root);
  return root;
}

async function pnpmRepo(): Promise<string> {
  const root = await mkRoot();
  await put(
    root,
    "package.json",
    JSON.stringify({ name: "mono", private: true }),
  );
  await put(
    root,
    "pnpm-workspace.yaml",
    "packages:\n  - 'packages/**'\n  - '!**/fixtures/**'\n",
  );
  await put(root, "packages/a/package.json", '{"name":"@s/a"}');
  await put(root, "packages/group/b/package.json", '{"name":"b-pkg"}');
  await put(root, "packages/a/fixtures/x/package.json", '{"name":"fx"}');
  await put(root, "apps/c/package.json", '{"name":"c"}');
  await put(root, "apps/noname/package.json", '{"private":true}');
  await commitAll(root);
  return root;
}

async function hashTree(
  root: string,
  skip: (rel: string) => boolean = () => false,
): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  async function rec(dir: string): Promise<void> {
    for (const e of await fs.readdir(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      const rel = path.relative(root, p);
      if (skip(rel)) continue;
      if (e.isDirectory()) {
        out[rel + "/"] = "dir";
        await rec(p);
      } else {
        out[rel] = createHash("sha256")
          .update(await fs.readFile(p))
          .digest("hex");
      }
    }
  }
  await rec(root);
  return out;
}

function items<T>(s: { collected: boolean; items?: T[] }): T[] {
  if (!s.collected) throw new Error("section not collected");
  return s.items as T[];
}

afterEach(async () => {
  while (tmpDirs.length) {
    await fs.rm(tmpDirs.pop() as string, { recursive: true, force: true });
  }
});

describe("hexagen observe", () => {
  it("keeps package names exactly, never lists node_modules or vendor", async () => {
    const root = await messyRepo();
    const report = await observe({ root });
    const pkgs = items(report.packages);
    expect(pkgs).toContainEqual({
      name: "@acme/solo",
      root: ".",
      manifestFile: "package.json",
    });
    expect(pkgs).toContainEqual({
      name: "totally-different",
      root: "tools/odd-dir",
      manifestFile: "tools/odd-dir/package.json",
    });
    expect(pkgs.map((p) => p.name).sort()).toEqual([
      "@acme/solo",
      "totally-different",
    ]);
    expect(JSON.stringify(report)).not.toMatch(/node_modules|vendor/);
  });

  it("validates against the observed schema, with edges and unresolved not collected", async () => {
    const root = await messyRepo();
    const report = await observe({ root });
    expect(ObservedReport.safeParse(report).success).toBe(true);
    expect(report.edges).toEqual({
      collected: false,
      reason: "import pass not run (BW4b)",
    });
    expect(report.unresolved).toEqual({
      collected: false,
      reason: "import pass not run (BW4b)",
    });
    expect(report.limits.truncated).toBe(false);
  });

  it("emits no type, layer, plane or context key anywhere", async () => {
    const root = await messyRepo();
    const text = JSON.stringify(await observe({ root }));
    for (const key of ["type", "layer", "plane", "context"]) {
      expect(text).not.toMatch(new RegExp(`"${key}s?"\\s*:`));
    }
  });

  it("counts languages by extension and skips ignored and vendored trees", async () => {
    const root = await messyRepo();
    const langs = items((await observe({ root })).languages);
    const byName = Object.fromEntries(langs.map((l) => [l.name, l.fileCount]));
    // src/util.js + tools/odd-dir/index.js + legacy/old.js (dist/ and node_modules/ skipped)
    expect(byName.JavaScript).toBe(3);
    expect(byName.TypeScript).toBe(3);
    expect(byName.Python).toBe(1);
    expect(byName.Go).toBe(2);
  });

  it("reports build markers by repo-relative path", async () => {
    const root = await messyRepo();
    const build = items((await observe({ root })).build);
    expect(build).toContainEqual({ marker: "go.mod", path: "go.mod" });
    expect(build).toContainEqual({ marker: "Makefile", path: "Makefile" });
    expect(build).toContainEqual({
      marker: "package.json",
      path: "tools/odd-dir/package.json",
    });
    expect(build.map((b) => b.path)).not.toContain("vendor/x/package.json");
  });

  it("reports generated paths from linguist, header (first 5 lines) and gitignored dist", async () => {
    const root = await messyRepo();
    const gen = items((await observe({ root })).generated);
    expect(gen).toContainEqual({
      path: "pb/a.pb.go",
      source: "linguist-generated",
    });
    expect(gen).toContainEqual({ path: "gen/api.ts", source: "header" });
    expect(gen).toContainEqual({
      path: "dist/",
      source: "gitignored-build-dir",
    });
    expect(gen.map((g) => g.path)).not.toContain("src/late.ts");
  });

  it("reports dontTouch from the flag and CODEOWNERS, never as a rule", async () => {
    const root = await messyRepo();
    const dt = items(
      (await observe({ root, dontTouch: ["legacy", "src/index.ts"] }))
        .dontTouch,
    );
    expect(dt).toContainEqual({ path: "legacy/", source: "flag" });
    expect(dt).toContainEqual({ path: "src/index.ts", source: "flag" });
    expect(dt).toContainEqual({
      path: "legacy/",
      source: "codeowners",
      owner: "@team-a @team-b",
    });
    expect(dt).toContainEqual({
      path: "tools/odd-dir/",
      source: "codeowners",
      owner: "@ops",
    });
    // `*.md` is a glob: not representable as a path, so it is not invented.
    expect(dt.map((d) => d.path)).not.toContain("*.md");
  });

  it("handles a pnpm-workspace.yaml packages/** glob with a negation", async () => {
    const root = await pnpmRepo();
    const pkgs = items((await observe({ root })).packages);
    const names = pkgs.map((p) => p.name).sort();
    expect(names).toEqual(["@s/a", "b-pkg", "c", "mono", "apps/noname"].sort());
    expect(pkgs).toContainEqual({
      name: "b-pkg",
      root: "packages/group/b",
      manifestFile: "packages/group/b/package.json",
    });
    // negated workspace glob drops the fixture package
    expect(names).not.toContain("fx");
  });

  it("reads the npm/yarn {packages} workspaces form", async () => {
    const root = await mkRoot();
    await put(
      root,
      "package.json",
      JSON.stringify({ name: "r", workspaces: { packages: ["libs/*"] } }),
    );
    await put(root, "libs/one/package.json", '{"name":"@x/one"}');
    await commitAll(root);
    const pkgs = items((await observe({ root })).packages);
    expect(pkgs.map((p) => p.name).sort()).toEqual(["@x/one", "r"]);
  });

  it("leaves the fixture tree byte-identical, including --out-less runs", async () => {
    const root = await messyRepo();
    const before = await hashTree(root);
    await observe({ root, dontTouch: ["legacy"] });
    const res = await runObserve({ root });
    expect(res.exitCode).toBe(0);
    expect(JSON.parse(res.stdout ?? "")).toHaveProperty("schemaVersion");
    expect(await hashTree(root)).toEqual(before);
  });

  it("refuses --out outside <root>/.hexagen/ with exit 2 and writes nothing", async () => {
    const root = await messyRepo();
    const before = await hashTree(root);
    for (const out of [
      "observed.json",
      "../escape.json",
      ".hexagen/../observed.json",
      path.join(os.tmpdir(), "elsewhere.json"),
      ".hexagen",
      ".hexagen/",
    ]) {
      const res = await runObserve({ root, out, yes: true });
      expect(res.exitCode, out).toBe(2);
    }
    expect(await hashTree(root)).toEqual(before);
  });

  it("refuses --out through a symlinked .hexagen that escapes the root", async () => {
    const root = await messyRepo();
    const elsewhere = await mkRoot();
    await fs.symlink(elsewhere, path.join(root, ".hexagen"));
    const res = await runObserve({ root, out: ".hexagen/o.json", yes: true });
    expect(res.exitCode).toBe(2);
    expect(await fs.readdir(elsewhere)).toEqual([]);
  });

  it("prints the preflight line and needs --yes before writing under .hexagen/", async () => {
    const root = await messyRepo();
    const target = path.join(root, ".hexagen", "observed.json");
    const dry = await runObserve({ root, out: ".hexagen/observed.json" });
    expect(dry.exitCode).toBe(2);
    expect(dry.messages).toContain(`will write: ${target}`);
    await expect(fs.stat(target)).rejects.toThrow();

    const wet = await runObserve({
      root,
      out: ".hexagen/observed.json",
      yes: true,
    });
    expect(wet.exitCode).toBe(0);
    expect(wet.messages).toContain(`will write: ${target}`);
    const written = ObservedReport.parse(
      JSON.parse(await fs.readFile(target, "utf8")),
    );
    expect(written.repo.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it("stops at the file cap with collected:false sections and the reason in limits", async () => {
    const root = await messyRepo();
    const report = await observe({ root, maxFiles: 3 });
    expect(report.limits.truncated).toBe(true);
    expect(report.limits.maxFiles).toBe(3);
    expect(report.limits.reasons.join(" ")).toMatch(/file cap/);
    for (const s of [report.packages, report.languages, report.build]) {
      expect(s.collected).toBe(false);
    }
    expect(ObservedReport.safeParse(report).success).toBe(true);
  });

  it("stops at the time cap", async () => {
    const root = await messyRepo();
    let t = 0;
    const report = await observe({
      root,
      maxMs: 10,
      now: () => (t += 1000),
    });
    expect(report.limits.truncated).toBe(true);
    expect(report.limits.reasons.join(" ")).toMatch(/time cap/);
    expect(report.languages.collected).toBe(false);
  });

  it("is registered as its own command with the documented flags", () => {
    expect(observeCommander.name()).toBe("observe");
    const flags = observeCommander.options.map((o) => o.long);
    expect(flags).toEqual(
      expect.arrayContaining([
        "--root",
        "--out",
        "--yes",
        "--dont-touch",
        "--max-files",
        "--max-ms",
      ]),
    );
  });
});

describe("globToRegExp", () => {
  const m = (g: string, p: string) => globToRegExp(g)?.test(p) ?? false;
  it("matches * within one segment only", () => {
    expect(m("packages/*", "packages/a")).toBe(true);
    expect(m("packages/*", "packages/a/b")).toBe(false);
  });
  it("matches ** across segments, with and without a trailing segment", () => {
    expect(m("packages/**", "packages/a/b/c")).toBe(true);
    expect(m("**/fixtures/**", "packages/a/fixtures/x")).toBe(true);
    expect(m("**/fixtures/**", "fixtures/x")).toBe(true);
    expect(m("a/**/z", "a/z")).toBe(true);
    expect(m("a/**/z", "a/b/c/z")).toBe(true);
  });
  it("supports ?, character classes and braces", () => {
    expect(m("a?c", "abc")).toBe(true);
    expect(m("a?c", "a/c")).toBe(false);
    expect(m("[ab]x", "bx")).toBe(true);
    expect(m("{apps,libs}/*", "libs/q")).toBe(true);
    expect(m("{apps,libs}/*", "docs/q")).toBe(false);
  });
  it("treats regex metacharacters literally", () => {
    expect(m("a.b", "axb")).toBe(false);
    expect(m("a+(b)", "a+(b)")).toBe(true);
  });
});

const isWin = process.platform === "win32";
const isRoot = typeof process.getuid === "function" && process.getuid() === 0;

function gitOut(cwd: string, ...args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

const EXCLUDE = (root: string) => path.join(root, ".git", "info", "exclude");

describe("hexagen observe: fix round", () => {
  it("requires --root to be the repo top level", async () => {
    const root = await messyRepo();
    const res = await runObserve({ root: path.join(root, "src") });
    expect(res.exitCode).toBe(2);
    expect(res.messages.join("\n")).toContain(
      `--root must be the repo top level (git says ${await fs.realpath(root)})`,
    );
  });

  it("exits 2 on a root that is not a git checkout", async () => {
    const root = await mkRoot();
    await put(root, "a.ts", "1;\n");
    const res = await runObserve({ root });
    expect(res.exitCode).toBe(2);
    expect(res.messages.join(" ")).toMatch(/not a git checkout/);
  });

  describe("git exclude", () => {
    it("adds .hexagen/ once, lists both files in the preflight, and touches nothing else", async () => {
      const root = await messyRepo();
      const skip = (rel: string) =>
        rel === ".hexagen" ||
        rel.startsWith(".hexagen/") ||
        rel === path.join(".git", "info", "exclude");
      const before = await hashTree(root, skip);
      const args = { root, out: ".hexagen/observed.json", yes: true };
      const first = await runObserve(args);
      expect(first.exitCode).toBe(0);
      expect(first.messages).toContain(
        `will write: ${path.join(root, ".hexagen", "observed.json")}`,
      );
      expect(first.messages).toContain(`will write: ${EXCLUDE(root)}`);
      expect(first.messages.join("\n")).toMatch(/git add -f/);
      expect(await fs.readFile(EXCLUDE(root), "utf8")).toContain(".hexagen/\n");
      expect(await hashTree(root, skip)).toEqual(before);
      expect(await fs.readdir(path.join(root, ".hexagen"))).toEqual([
        "observed.json",
      ]);
      // ignored by git afterwards
      execFileSync("git", ["check-ignore", "-q", ".hexagen/observed.json"], {
        cwd: root,
      });

      const second = await runObserve(args);
      expect(second.exitCode).toBe(0);
      const lines = (await fs.readFile(EXCLUDE(root), "utf8"))
        .split("\n")
        .filter((l) => l === ".hexagen/");
      expect(lines).toHaveLength(1);
    });

    it("does not list .hexagen contents on a second run", async () => {
      const root = await messyRepo();
      const args = { root, out: ".hexagen/observed.json", yes: true };
      await runObserve(args);
      const again = await observe({ root });
      expect(JSON.stringify(again)).not.toMatch(/\.hexagen/);
    });

    it("never walks .hexagen, even with package.json and sources inside", async () => {
      const root = await messyRepo();
      await put(root, ".hexagen/inner/package.json", '{"name":"inner"}');
      await put(root, ".hexagen/x.ts", "1;\n");
      const report = await observe({ root });
      expect(items(report.packages).map((p) => p.name)).not.toContain("inner");
      const ts = items(report.languages).find((l) => l.name === "TypeScript");
      expect(ts?.fileCount).toBe(3);
    });

    it.skipIf(isWin)(
      "writes the common exclude file for a linked worktree",
      async () => {
        const root = await messyRepo();
        const wt = path.join(await mkRoot(), "wt");
        git(root, "worktree", "add", "-q", "-b", "side", wt);
        const skip = (rel: string) =>
          rel === ".hexagen" || rel.startsWith(".hexagen/");
        const before = await hashTree(wt, skip);
        const mainBefore = await hashTree(
          root,
          (rel) =>
            rel === path.join(".git", "info", "exclude") ||
            rel.startsWith(path.join(".git", "worktrees")),
        );
        const res = await runObserve({
          root: wt,
          out: ".hexagen/observed.json",
          yes: true,
        });
        expect(res.exitCode).toBe(0);
        const common = path.resolve(
          wt,
          gitOut(wt, "rev-parse", "--git-path", "info/exclude"),
        );
        expect(await fs.realpath(common)).toBe(
          await fs.realpath(EXCLUDE(root)),
        );
        expect(await fs.readFile(common, "utf8")).toContain(".hexagen/\n");
        execFileSync("git", ["check-ignore", "-q", ".hexagen/observed.json"], {
          cwd: wt,
        });
        expect(await hashTree(wt, skip)).toEqual(before);
        expect(
          await hashTree(
            root,
            (rel) =>
              rel === path.join(".git", "info", "exclude") ||
              rel.startsWith(path.join(".git", "worktrees")),
          ),
        ).toEqual(mainBefore);
      },
    );

    it("fails with exit 2 before writing observed.json when the exclude file cannot be updated", async () => {
      const root = await messyRepo();
      await fs.rm(EXCLUDE(root), { force: true });
      await fs.mkdir(EXCLUDE(root)); // a directory where a file must go
      const res = await runObserve({
        root,
        out: ".hexagen/observed.json",
        yes: true,
      });
      expect(res.exitCode).toBe(2);
      await expect(
        fs.stat(path.join(root, ".hexagen", "observed.json")),
      ).rejects.toThrow();
    });
  });

  describe("crash paths from client-controlled text", () => {
    it("skips a workspace pattern that does not compile, with a note", async () => {
      const root = await mkRoot();
      await put(
        root,
        "package.json",
        JSON.stringify({
          name: "r",
          workspaces: ["packages/*", "!packages/[z-a]*"],
        }),
      );
      await put(root, "packages/a/package.json", '{"name":"a"}');
      await commitAll(root);
      const report = await observe({ root });
      expect(items(report.packages).map((p) => p.name)).toContain("a");
      expect(report.limits.reasons.join("\n")).toMatch(/note: .*\[z-a\]/);
      expect(report.limits.truncated).toBe(false);
    });

    it("skips a bad .gitattributes glob and a bad nested .gitignore line only", async () => {
      const root = await messyRepo();
      await put(
        root,
        ".gitattributes",
        "[z-a] linguist-generated\n*.pb.go linguist-generated\n",
      );
      await put(root, "tools/odd-dir/.gitignore", "[z-a]\ncache/\n");
      await commitAll2(root);
      const report = await observe({ root });
      const notes = report.limits.reasons.join("\n");
      expect(notes).toMatch(/\.gitattributes|ignore file/);
      expect(notes).toMatch(/tools\/odd-dir\/\.gitignore/);
      expect(items(report.generated)).toContainEqual({
        path: "pb/a.pb.go",
        source: "linguist-generated",
      });
      // the good line of the nested .gitignore still applies
      const js = items(report.languages).find((l) => l.name === "JavaScript");
      expect(js?.fileCount).toBe(3);
    });

    it.skipIf(isWin)(
      "drops a filename with a backslash, with a note",
      async () => {
        const root = await messyRepo();
        await put(root, "weird\\name.ts", "1;\n");
        await commitAll2(root);
        const report = await observe({ root });
        expect(report.limits.reasons.join("\n")).toMatch(/weird.*skipped/);
        const ts = items(report.languages).find((l) => l.name === "TypeScript");
        expect(ts?.fileCount).toBe(3);
      },
    );
  });

  describe("--out edge cases", () => {
    it("exits 2 when .hexagen exists as a regular file", async () => {
      const root = await messyRepo();
      await fs.writeFile(path.join(root, ".hexagen"), "x");
      const res = await runObserve({
        root,
        out: ".hexagen/observed.json",
        yes: true,
      });
      expect(res.exitCode).toBe(2);
      expect(res.messages.join(" ")).toMatch(/not a directory/);
    });

    it("removes its temp file when the rename fails", async () => {
      const root = await messyRepo();
      await fs.mkdir(path.join(root, ".hexagen", "observed.json"), {
        recursive: true,
      });
      const res = await runObserve({
        root,
        out: ".hexagen/observed.json",
        yes: true,
      });
      expect(res.exitCode).toBe(2);
      expect(await fs.readdir(path.join(root, ".hexagen"))).toEqual([
        "observed.json",
      ]);
    });

    it.skipIf(isWin)(
      "replaces the file by rename, not by rewriting it in place",
      async () => {
        const root = await messyRepo();
        const target = path.join(root, ".hexagen", "observed.json");
        await fs.mkdir(path.dirname(target));
        await fs.writeFile(target, "old");
        const inoBefore = (await fs.stat(target)).ino;
        const res = await runObserve({
          root,
          out: ".hexagen/observed.json",
          yes: true,
        });
        expect(res.exitCode).toBe(0);
        expect((await fs.stat(target)).ino).not.toBe(inoBefore);
      },
    );
  });

  describe("remote credentials", () => {
    async function remoteOf(url: string): Promise<string | undefined> {
      const root = await messyRepo();
      git(root, "remote", "add", "origin", url);
      return (await observe({ root })).repo.remote;
    }
    it("strips userinfo and query from URL remotes", async () => {
      const a = await remoteOf("https://user:tok@host/o/r.git?token=abc");
      expect(a).toBe("https://host/o/r.git");
      const b = await remoteOf("https://user:p@ss@host/o/r");
      expect(b).toBe("https://host/o/r");
      for (const v of [a, b]) {
        expect(v).not.toMatch(/user|tok|p@ss|ss@|abc|\?/);
      }
    });
    it("leaves scp-like remotes unchanged", async () => {
      expect(await remoteOf("git@host:o/r")).toBe("git@host:o/r");
    });
  });

  it("does not treat .yarn, bower_components or jspm_packages as package roots", async () => {
    const root = await messyRepo();
    await put(root, ".yarn/sdks/typescript/package.json", '{"name":"sdk"}');
    await put(root, "bower_components/b/package.json", '{"name":"bw"}');
    await put(root, "jspm_packages/j/package.json", '{"name":"jp"}');
    const names = items((await observe({ root })).packages).map((p) => p.name);
    expect(names).not.toEqual(expect.arrayContaining(["sdk"]));
    expect(names).not.toContain("bw");
    expect(names).not.toContain("jp");
  });

  it("notes a manifest with no name", async () => {
    const root = await pnpmRepo();
    const report = await observe({ root });
    expect(report.limits.reasons).toContain(
      "note: apps/noname/package.json has no name; reported under its directory",
    );
    expect(report.limits.truncated).toBe(false);
  });

  it.skipIf(isWin || isRoot)(
    "notes an unreadable directory and carries on",
    async () => {
      const root = await messyRepo();
      const locked = path.join(root, "locked");
      await fs.mkdir(locked);
      await fs.chmod(locked, 0o000);
      try {
        const report = await observe({ root });
        expect(report.limits.reasons).toContain(
          "note: locked unreadable; skipped",
        );
        expect(report.languages.collected).toBe(true);
      } finally {
        await fs.chmod(locked, 0o755);
      }
    },
  );

  it("honours a ! negation in npm/yarn workspaces", async () => {
    const root = await mkRoot();
    await put(
      root,
      "package.json",
      JSON.stringify({ name: "r", workspaces: ["libs/*", "!libs/skip"] }),
    );
    await put(root, "libs/keep/package.json", '{"name":"keep"}');
    await put(root, "libs/skip/package.json", '{"name":"skip"}');
    await commitAll(root);
    const names = items((await observe({ root })).packages).map((p) => p.name);
    expect(names.sort()).toEqual(["keep", "r"]);
  });

  it("recognises the build markers", async () => {
    const root = await mkRoot();
    for (const f of [
      "build.gradle.kts",
      "pyproject.toml",
      "Cargo.toml",
      "nx.json",
    ]) {
      await put(root, f, "x\n");
    }
    await commitAll(root);
    const markers = items((await observe({ root })).build).map((b) => b.marker);
    expect(markers.sort()).toEqual(
      ["Cargo.toml", "build.gradle.kts", "nx.json", "pyproject.toml"].sort(),
    );
  });

  it("honours a linguist-generated negation", async () => {
    const root = await messyRepo();
    await put(root, "pb/keep.pb.go", "package pb\n");
    await put(
      root,
      ".gitattributes",
      "*.pb.go linguist-generated\npb/keep.pb.go -linguist-generated\n",
    );
    await commitAll2(root);
    const paths = items((await observe({ root })).generated).map((g) => g.path);
    expect(paths).toContain("pb/a.pb.go");
    expect(paths).not.toContain("pb/keep.pb.go");
  });

  it("rejects a bad --dont-touch before walking", async () => {
    const root = await messyRepo();
    let called = 0;
    const res = await runObserve({
      root,
      dontTouch: ["../x"],
      now: () => ++called,
    });
    expect(res.exitCode).toBe(2);
    expect(called).toBe(0);
  });

  it("reads CODEOWNERS in GitHub's order: .github/ first", async () => {
    const root = await messyRepo();
    await put(root, ".github/CODEOWNERS", "/gh-only/ @gh\n");
    await commitAll2(root);
    const dt = items((await observe({ root })).dontTouch);
    expect(dt).toContainEqual({
      path: "gh-only/",
      source: "codeowners",
      owner: "@gh",
    });
    expect(dt.map((d) => d.path)).not.toContain("legacy/");
  });

  it("reports a bad --max-files as a clean commander error", async () => {
    observeCommander.exitOverride();
    observeCommander.configureOutput({
      writeErr: () => {},
      writeOut: () => {},
    });
    await expect(
      observeCommander.parseAsync(["--max-files", "abc"], { from: "user" }),
    ).rejects.toMatchObject({ code: "commander.invalidArgument" });
  });
});

describe("hexagen observe: round 2", () => {
  async function remoteOf2(url: string): Promise<string | undefined> {
    const root = await messyRepo();
    git(root, "remote", "add", "origin", url);
    return (await observe({ root })).repo.remote;
  }

  it("strips credentials from scp-style remotes, keeping the git user", async () => {
    expect(await remoteOf2("ghp_abc@github.com:o/r")).toBe("github.com:o/r");
    expect(await remoteOf2("git@github.com:o/r")).toBe("git@github.com:o/r");
    expect(await remoteOf2("u:p@host:o/r")).toBe("host:o/r");
  });

  it("starts the deadline before metadata and checks it after the last generated batch", async () => {
    const root = await mkRoot();
    await put(root, "a.ts", "// @generated\n");
    await commitAll(root);
    let calls = 0;
    // calls 1 and 2 (deadline start, walk) see t=0; every later call is late
    const now = () => (++calls <= 2 ? 0 : 1000);
    const report = await observe({ root, maxMs: 10, now });
    expect(report.languages.collected).toBe(true);
    expect(report.generated).toMatchObject({ collected: false });
    expect(report.limits.truncated).toBe(true);
    expect(report.limits.reasons.join(" ")).toMatch(/time cap/);
  });

  it.skipIf(isWin)("refuses a symlinked CODEOWNERS with a note", async () => {
    const root = await messyRepo();
    const outside = await mkRoot();
    await fs.writeFile(path.join(outside, "CO"), "/secret/ @leak\n");
    await fs.rm(path.join(root, "CODEOWNERS"));
    await fs.symlink(path.join(outside, "CO"), path.join(root, "CODEOWNERS"));
    const report = await observe({ root });
    expect(items(report.dontTouch).map((d) => d.path)).not.toContain("secret/");
    expect(report.limits.reasons.join("\n")).toMatch(/CODEOWNERS.*symlink/);
  });

  it.skipIf(isWin)(
    "refuses a symlinked .gitattributes and pnpm-workspace.yaml",
    async () => {
      const root = await messyRepo();
      const outside = await mkRoot();
      await fs.writeFile(path.join(outside, "ga"), "*.ts linguist-generated\n");
      await fs.writeFile(path.join(outside, "pw"), "packages:\n  - '!**'\n");
      await fs.rm(path.join(root, ".gitattributes"));
      await fs.symlink(
        path.join(outside, "ga"),
        path.join(root, ".gitattributes"),
      );
      await fs.symlink(
        path.join(outside, "pw"),
        path.join(root, "pnpm-workspace.yaml"),
      );
      const report = await observe({ root });
      expect(items(report.generated).map((g) => g.path)).not.toContain(
        "src/index.ts",
      );
      expect(items(report.packages).length).toBeGreaterThan(0);
      const notes = report.limits.reasons.join("\n");
      expect(notes).toMatch(/\.gitattributes.*symlink/);
      expect(notes).toMatch(/pnpm-workspace\.yaml.*symlink/);
    },
  );

  it("exits 2 with a clear message for a missing --root, with and without --out", async () => {
    const missing = path.join(os.tmpdir(), "hexagen-observe-missing-root-xyz");
    for (const extra of [{}, { out: ".hexagen/o.json", yes: true }]) {
      const res = await runObserve({ root: missing, ...extra });
      expect(res.exitCode).toBe(2);
      expect(res.messages.join(" ")).toMatch(
        /--root .* (does not exist|not accessible)/,
      );
    }
  });

  it("exits 2 when a nested output parent is blocked by a file", async () => {
    const root = await messyRepo();
    await fs.mkdir(path.join(root, ".hexagen"));
    await fs.writeFile(path.join(root, ".hexagen", "nested"), "x");
    const res = await runObserve({
      root,
      out: ".hexagen/nested/o.json",
      yes: true,
    });
    expect(res.exitCode).toBe(2);
    expect(res.messages.join(" ")).toMatch(/could not write/);
  });

  it("never removes a directory at the temp path and reports the original error", async () => {
    const root = await messyRepo();
    const tmpDir = path.join(root, ".hexagen", "conflict.tmp");
    await fs.mkdir(tmpDir, { recursive: true });
    await fs.writeFile(path.join(tmpDir, "keep"), "k");
    const res = await runObserve({
      root,
      out: ".hexagen/observed.json",
      yes: true,
      tmpPath: () => tmpDir,
    });
    expect(res.exitCode).toBe(2);
    expect(res.messages.join(" ")).toMatch(/could not write.*(EEXIST|EISDIR)/);
    expect(await fs.readFile(path.join(tmpDir, "keep"), "utf8")).toBe("k");
  });

  it("does not delete a pre-existing temp file it did not create", async () => {
    const root = await messyRepo();
    const tmpFile = path.join(root, ".hexagen", "squat.tmp");
    await fs.mkdir(path.dirname(tmpFile), { recursive: true });
    await fs.writeFile(tmpFile, "mine");
    const res = await runObserve({
      root,
      out: ".hexagen/observed.json",
      yes: true,
      tmpPath: () => tmpFile,
    });
    expect(res.exitCode).toBe(2);
    expect(await fs.readFile(tmpFile, "utf8")).toBe("mine");
  });
});

async function commitAll2(root: string): Promise<void> {
  git(root, "add", "-A");
  git(root, "commit", "-q", "-m", "more", "--no-gpg-sign");
}
