import { afterEach, describe, expect, it } from "vitest";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ObservedReport } from "@hexagen/shared";
import {
  observe,
  observeCommander,
  runObserve,
} from "../../../src/commands/observe/index.js";
import { globToRegExp } from "../../../src/commands/observe/glob.js";

const tmpDirs: string[] = [];

async function put(root: string, rel: string, body: string): Promise<void> {
  const file = path.join(root, rel);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, body, "utf8");
}

function git(root: string, ...args: string[]): void {
  execFileSync(
    "git",
    ["-c", "user.name=t", "-c", "user.email=t@example.com", ...args],
    { cwd: root, stdio: "ignore" },
  );
}

async function commitAll(root: string): Promise<void> {
  git(root, "init", "-q");
  git(root, "add", "-A");
  git(root, "commit", "-q", "-m", "fixture", "--no-gpg-sign");
}

async function mkRoot(): Promise<string> {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "hexagen-observe-"));
  tmpDirs.push(root);
  return root;
}

/** No workspaces, mixed languages, scoped + mismatched names, vendored deps. */
async function messyRepo(): Promise<string> {
  const root = await mkRoot();
  await put(root, "package.json", JSON.stringify({ name: "@acme/solo" }));
  await put(root, "src/index.ts", "export const a = 1;\n");
  await put(root, "src/util.js", "module.exports = 1;\n");
  await put(root, "lib/helper.py", "x = 1\n");
  await put(root, "cmd/main.go", "package main\n");
  await put(root, "go.mod", "module example.test/m\n");
  await put(root, "Makefile", "all:\n");
  await put(
    root,
    "tools/odd-dir/package.json",
    JSON.stringify({ name: "totally-different" }),
  );
  await put(root, "tools/odd-dir/index.js", "1;\n");
  await put(root, "tools/odd-dir/.gitignore", "cache/\n"); // nested gitignore
  await put(root, "tools/odd-dir/cache/c.js", "1;\n");
  await put(root, "vendor/x/package.json", JSON.stringify({ name: "vend" }));
  await put(root, "node_modules/dep/package.json", '{"name":"dep"}');
  await put(root, "node_modules/dep/index.js", "1;\n");
  await put(root, ".gitignore", "dist/\n*.log\n");
  await put(root, "dist/out.js", "1;\n");
  await put(root, "debug.log", "x\n");
  await put(root, "gen/api.ts", "// @generated by codegen\nexport {};\n");
  await put(root, "src/late.ts", "\n\n\n\n\n// @generated (too late)\n");
  await put(root, "pb/a.pb.go", "package pb\n");
  await put(root, ".gitattributes", "*.pb.go linguist-generated=true\n");
  await put(
    root,
    "CODEOWNERS",
    "# comment\n/legacy/ @team-a @team-b\n*.md @docs\n/tools/odd-dir @ops\n",
  );
  await put(root, "legacy/old.js", "1;\n");
  await commitAll(root);
  return root;
}

async function pnpmRepo(): Promise<string> {
  const root = await mkRoot();
  await put(
    root,
    "package.json",
    JSON.stringify({ name: "mono", private: true }),
  );
  await put(
    root,
    "pnpm-workspace.yaml",
    "packages:\n  - 'packages/**'\n  - '!**/fixtures/**'\n",
  );
  await put(root, "packages/a/package.json", '{"name":"@s/a"}');
  await put(root, "packages/group/b/package.json", '{"name":"b-pkg"}');
  await put(root, "packages/a/fixtures/x/package.json", '{"name":"fx"}');
  await put(root, "apps/c/package.json", '{"name":"c"}');
  await put(root, "apps/noname/package.json", '{"private":true}');
  await commitAll(root);
  return root;
}

async function hashTree(root: string): Promise<Record<string, string>> {
  const out: Record<string, string> = {};
  async function rec(dir: string): Promise<void> {
    for (const e of await fs.readdir(dir, { withFileTypes: true })) {
      const p = path.join(dir, e.name);
      const rel = path.relative(root, p);
      if (e.isDirectory()) {
        out[rel + "/"] = "dir";
        await rec(p);
      } else {
        out[rel] = createHash("sha256")
          .update(await fs.readFile(p))
          .digest("hex");
      }
    }
  }
  await rec(root);
  return out;
}

function items<T>(s: { collected: boolean; items?: T[] }): T[] {
  if (!s.collected) throw new Error("section not collected");
  return s.items as T[];
}

afterEach(async () => {
  while (tmpDirs.length) {
    await fs.rm(tmpDirs.pop() as string, { recursive: true, force: true });
  }
});

describe("hexagen observe", () => {
  it("keeps package names exactly, never lists node_modules or vendor", async () => {
    const root = await messyRepo();
    const report = await observe({ root });
    const pkgs = items(report.packages);
    expect(pkgs).toContainEqual({
      name: "@acme/solo",
      root: ".",
      manifestFile: "package.json",
    });
    expect(pkgs).toContainEqual({
      name: "totally-different",
      root: "tools/odd-dir",
      manifestFile: "tools/odd-dir/package.json",
    });
    expect(pkgs.map((p) => p.name).sort()).toEqual([
      "@acme/solo",
      "totally-different",
    ]);
    expect(JSON.stringify(report)).not.toMatch(/node_modules|vendor/);
  });

  it("validates against the observed schema, with edges and unresolved not collected", async () => {
    const root = await messyRepo();
    const report = await observe({ root });
    expect(ObservedReport.safeParse(report).success).toBe(true);
    expect(report.edges).toEqual({
      collected: false,
      reason: "import pass not run (BW4b)",
    });
    expect(report.unresolved).toEqual({
      collected: false,
      reason: "import pass not run (BW4b)",
    });
    expect(report.limits.truncated).toBe(false);
  });

  it("emits no type, layer, plane or context key anywhere", async () => {
    const root = await messyRepo();
    const text = JSON.stringify(await observe({ root }));
    for (const key of ["type", "layer", "plane", "context"]) {
      expect(text).not.toMatch(new RegExp(`"${key}s?"\\s*:`));
    }
  });

  it("counts languages by extension and skips ignored and vendored trees", async () => {
    const root = await messyRepo();
    const langs = items((await observe({ root })).languages);
    const byName = Object.fromEntries(langs.map((l) => [l.name, l.fileCount]));
    // src/util.js + tools/odd-dir/index.js + legacy/old.js (dist/ and node_modules/ skipped)
    expect(byName.JavaScript).toBe(3);
    expect(byName.TypeScript).toBe(3);
    expect(byName.Python).toBe(1);
    expect(byName.Go).toBe(2);
  });

  it("reports build markers by repo-relative path", async () => {
    const root = await messyRepo();
    const build = items((await observe({ root })).build);
    expect(build).toContainEqual({ marker: "go.mod", path: "go.mod" });
    expect(build).toContainEqual({ marker: "Makefile", path: "Makefile" });
    expect(build).toContainEqual({
      marker: "package.json",
      path: "tools/odd-dir/package.json",
    });
    expect(build.map((b) => b.path)).not.toContain("vendor/x/package.json");
  });

  it("reports generated paths from linguist, header (first 5 lines) and gitignored dist", async () => {
    const root = await messyRepo();
    const gen = items((await observe({ root })).generated);
    expect(gen).toContainEqual({
      path: "pb/a.pb.go",
      source: "linguist-generated",
    });
    expect(gen).toContainEqual({ path: "gen/api.ts", source: "header" });
    expect(gen).toContainEqual({
      path: "dist/",
      source: "gitignored-build-dir",
    });
    expect(gen.map((g) => g.path)).not.toContain("src/late.ts");
  });

  it("reports dontTouch from the flag and CODEOWNERS, never as a rule", async () => {
    const root = await messyRepo();
    const dt = items(
      (await observe({ root, dontTouch: ["legacy", "src/index.ts"] }))
        .dontTouch,
    );
    expect(dt).toContainEqual({ path: "legacy/", source: "flag" });
    expect(dt).toContainEqual({ path: "src/index.ts", source: "flag" });
    expect(dt).toContainEqual({
      path: "legacy/",
      source: "codeowners",
      owner: "@team-a @team-b",
    });
    expect(dt).toContainEqual({
      path: "tools/odd-dir/",
      source: "codeowners",
      owner: "@ops",
    });
    // `*.md` is a glob: not representable as a path, so it is not invented.
    expect(dt.map((d) => d.path)).not.toContain("*.md");
  });

  it("handles a pnpm-workspace.yaml packages/** glob with a negation", async () => {
    const root = await pnpmRepo();
    const pkgs = items((await observe({ root })).packages);
    const names = pkgs.map((p) => p.name).sort();
    expect(names).toEqual(["@s/a", "b-pkg", "c", "mono", "apps/noname"].sort());
    expect(pkgs).toContainEqual({
      name: "b-pkg",
      root: "packages/group/b",
      manifestFile: "packages/group/b/package.json",
    });
    // negated workspace glob drops the fixture package
    expect(names).not.toContain("fx");
  });

  it("reads the npm/yarn {packages} workspaces form", async () => {
    const root = await mkRoot();
    await put(
      root,
      "package.json",
      JSON.stringify({ name: "r", workspaces: { packages: ["libs/*"] } }),
    );
    await put(root, "libs/one/package.json", '{"name":"@x/one"}');
    await commitAll(root);
    const pkgs = items((await observe({ root })).packages);
    expect(pkgs.map((p) => p.name).sort()).toEqual(["@x/one", "r"]);
  });

  it("leaves the fixture tree byte-identical, including --out-less runs", async () => {
    const root = await messyRepo();
    const before = await hashTree(root);
    await observe({ root, dontTouch: ["legacy"] });
    const res = await runObserve({ root });
    expect(res.exitCode).toBe(0);
    expect(JSON.parse(res.stdout ?? "")).toHaveProperty("schemaVersion");
    expect(await hashTree(root)).toEqual(before);
  });

  it("refuses --out outside <root>/.hexagen/ with exit 2 and writes nothing", async () => {
    const root = await messyRepo();
    const before = await hashTree(root);
    for (const out of [
      "observed.json",
      "../escape.json",
      ".hexagen/../observed.json",
      path.join(os.tmpdir(), "elsewhere.json"),
      ".hexagen",
      ".hexagen/",
    ]) {
      const res = await runObserve({ root, out, yes: true });
      expect(res.exitCode, out).toBe(2);
    }
    expect(await hashTree(root)).toEqual(before);
  });

  it("refuses --out through a symlinked .hexagen that escapes the root", async () => {
    const root = await messyRepo();
    const elsewhere = await mkRoot();
    await fs.symlink(elsewhere, path.join(root, ".hexagen"));
    const res = await runObserve({ root, out: ".hexagen/o.json", yes: true });
    expect(res.exitCode).toBe(2);
    expect(await fs.readdir(elsewhere)).toEqual([]);
  });

  it("prints the preflight line and needs --yes before writing under .hexagen/", async () => {
    const root = await messyRepo();
    const target = path.join(root, ".hexagen", "observed.json");
    const dry = await runObserve({ root, out: ".hexagen/observed.json" });
    expect(dry.exitCode).toBe(2);
    expect(dry.messages).toContain(`will write: ${target}`);
    await expect(fs.stat(target)).rejects.toThrow();

    const wet = await runObserve({
      root,
      out: ".hexagen/observed.json",
      yes: true,
    });
    expect(wet.exitCode).toBe(0);
    expect(wet.messages).toContain(`will write: ${target}`);
    const written = ObservedReport.parse(
      JSON.parse(await fs.readFile(target, "utf8")),
    );
    expect(written.repo.commit).toMatch(/^[0-9a-f]{40}$/);
  });

  it("stops at the file cap with collected:false sections and the reason in limits", async () => {
    const root = await messyRepo();
    const report = await observe({ root, maxFiles: 3 });
    expect(report.limits.truncated).toBe(true);
    expect(report.limits.maxFiles).toBe(3);
    expect(report.limits.reasons.join(" ")).toMatch(/file cap/);
    for (const s of [report.packages, report.languages, report.build]) {
      expect(s.collected).toBe(false);
    }
    expect(ObservedReport.safeParse(report).success).toBe(true);
  });

  it("stops at the time cap", async () => {
    const root = await messyRepo();
    let t = 0;
    const report = await observe({
      root,
      maxMs: 10,
      now: () => (t += 1000),
    });
    expect(report.limits.truncated).toBe(true);
    expect(report.limits.reasons.join(" ")).toMatch(/time cap/);
    expect(report.languages.collected).toBe(false);
  });

  it("is registered as its own command with the documented flags", () => {
    expect(observeCommander.name()).toBe("observe");
    const flags = observeCommander.options.map((o) => o.long);
    expect(flags).toEqual(
      expect.arrayContaining([
        "--root",
        "--out",
        "--yes",
        "--dont-touch",
        "--max-files",
        "--max-ms",
      ]),
    );
  });
});

describe("globToRegExp", () => {
  const m = (g: string, p: string) => globToRegExp(g).test(p);
  it("matches * within one segment only", () => {
    expect(m("packages/*", "packages/a")).toBe(true);
    expect(m("packages/*", "packages/a/b")).toBe(false);
  });
  it("matches ** across segments, with and without a trailing segment", () => {
    expect(m("packages/**", "packages/a/b/c")).toBe(true);
    expect(m("**/fixtures/**", "packages/a/fixtures/x")).toBe(true);
    expect(m("**/fixtures/**", "fixtures/x")).toBe(true);
    expect(m("a/**/z", "a/z")).toBe(true);
    expect(m("a/**/z", "a/b/c/z")).toBe(true);
  });
  it("supports ?, character classes and braces", () => {
    expect(m("a?c", "abc")).toBe(true);
    expect(m("a?c", "a/c")).toBe(false);
    expect(m("[ab]x", "bx")).toBe(true);
    expect(m("{apps,libs}/*", "libs/q")).toBe(true);
    expect(m("{apps,libs}/*", "docs/q")).toBe(false);
  });
  it("treats regex metacharacters literally", () => {
    expect(m("a.b", "axb")).toBe(false);
    expect(m("a+(b)", "a+(b)")).toBe(true);
  });
});
