export const LAYOUT_CONFIG = {
  CENTER_X: 400,
  CENTER_Y: 300,

  GROUP_SPACING: 1500,
  GROUP_MIN_WIDTH: 1400,
  GROUP_HEIGHT: 2200,

  ROOT_HEX_DIMENSION: 500,
  SATELLITE_HEX_DIMENSION: 360,

  HEX_POSITION_OFFSET_X: -300,
  HEX_POSITION_OFFSET_Y: -260,

  DOMAIN_NODE_X: 110,
  DOMAIN_NODE_Y: 340,
  USECASES_NODE_X: 275,
  USECASES_NODE_Y: 340,

  SATELLITE_DOMAIN_X: 100,
  SATELLITE_DOMAIN_Y: 280,
  SATELLITE_USECASES_X: 290,
  SATELLITE_USECASES_Y: 280,

  ENTITY_ROW_HEIGHT: 120,
  ENTITY_START_X: -170,
  ENTITY_START_Y: 750,

  SATELLITE_ENTITY_START_X: -220,
  SATELLITE_ENTITY_START_Y: 900,

  USECASE_ROW_HEIGHT: 120,
  USECASE_X_OFFSET: -20,
  USECASE_START_Y: 750,

  SATELLITE_USECASE_X_OFFSET: -20,
  SATELLITE_USECASE_START_Y: 900,

  NORTH_OFFSET_BASE: 280,
  NORTH_OFFSET_STEP: 120,
  SOUTH_OFFSET_BASE: 600,
  SOUTH_OFFSET_ADDITIONAL: 80,
  SOUTH_OFFSET_STEP: 180, // Increased from 120 to give more horizontal separation

  // Default dimensions for adapter nodes (matches useElkLayout default)
  ADAPTER_NODE_WIDTH: 180,

  WEST_PORT_OFFSET_X: -550, // Increased from -480 to push further out
  EAST_PORT_OFFSET_X: 845, // Increased from 775 to push further out
  PORT_OFFSET_BASE_Y: -40,
  PORT_OFFSET_STEP_Y: 100,

  PEER_OFFSET_LEFT: -400,
  PEER_OFFSET_RIGHT: 100,
  PEER_Y_STEP: 300,
} as const;

export function staggerYFor(index: number): number {
  if (index === 0) return 0;
  return index % 2 === 0 ? 150 : -150;
}
