// @generated by @hexagen/sync
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // Template source files are emitted verbatim into user projects — they are
    // not part of this package's own build and must not be linted here.
    ignores: ["dist/**", "node_modules/**", "templates/**"],
  },
);
