import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'HexaGen Frontend',
  description: 'Generated by HexaGen',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}