"use client";

import { useCallback, useEffect, useMemo, useRef } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { stepIndexById } from "../../project-wizard/config";
import { emptyFormValues } from "@/project-config-presets";

import {
  useSavedProjects,
  type SavedProject,
  type NewProjectLayer,
  type NewProjectLayerTurn,
  type ProjectLayerPatch,
} from "@/hooks/useSavedProjects";
import type { PersistenceError, ProjectLayerTurn } from "@hexagen/shared";
import { useActiveWorkspace } from "@/contexts/ActiveWorkspaceContext";
import { useProjectGenerationFlow } from "./useProjectGenerationFlow";
import { useProjectDialogHandlers } from "./useProjectDialogHandlers";
import type {
  UseWorkspaceShellUiReturn,
  WorkspaceShellState,
} from "./useWorkspaceShellUi";
import type { UseEditorSessionReturn } from "./useEditorSession";
import type { ManifestCompleteness } from "../../project-wizard/utils/analyzeManifestCompleteness";
import {
  discardProject as performDiscardProject,
  resetToGenesis as performResetToGenesis,
} from "@/lib/use-cases/project-lifecycle.use-case";
import { wizardToManifest } from "@hexagen/wizard-orchestration";

interface UseProjectLifecycleOptions {
  form: UseFormReturn<ProjectConfig>;
  ui: UseWorkspaceShellUiReturn;
  uiState: WorkspaceShellState;
  editor: Pick<
    UseEditorSessionReturn,
    | "setSessionId"
    | "clearSession"
    | "setActiveWorkspace"
    | "clearActiveWorkspace"
  >;
  totalSteps: number;
  onGoToStep: (index: number) => void;
}

export interface UseProjectLifecycleReturn {
  projects: SavedProject[];
  isGenerating: boolean;
  loadedProject: SavedProject | null;
  autoGeneratedSteps: ManifestCompleteness | null;

  deleteProject: (id: string) => void;
  renameProject: (id: string, name: string) => void;
  // Debounced autosave for stepless Plan-phase field edits. Writes ONLY
  // formState (never manifestYaml — see useSavedProjects.updateProjectFormState);
  // the Plan Workbench "Project settings" section drives it.
  updateProjectFormState: (id: string, formState: ProjectConfig) => void;

  // Layer mutations MUST run on this hook's own useSavedProjects instance: the
  // wizard autosave (handleNext/handleSaveAndNew → updateProject) writes the
  // whole projects array from THIS instance's snapshot, so a layer added via a
  // different instance would be silently clobbered on the next autosave.
  // (The mutations themselves are additionally clobber-safe: they commit via
  // the port's read-merge-write updateProjectRecord, not a whole-array save.)
  addLayer: (
    projectId: string,
    layer: NewProjectLayer,
  ) => Promise<string | null>;
  updateLayer: (
    projectId: string,
    layerId: string,
    patch: ProjectLayerPatch,
  ) => Promise<boolean>;
  appendLayerTurn: (
    projectId: string,
    layerId: string,
    turn: NewProjectLayerTurn,
    patch?: ProjectLayerPatch,
  ) => Promise<ProjectLayerTurn | null>;
  layersPersistError: PersistenceError | null;
  clearLayersPersistError: () => void;

  handleNext: () => Promise<void>;
  handleBack: () => void;
  handleLoadProject: (id: string) => Promise<void>;
  handleGenerate: () => Promise<void>;
  handleManifestLoaded: (yamlContent: string) => Promise<void>;
  handleCancelNewProject: () => void;
  handleSaveAndNew: () => void;
  handleDiscardAndNew: () => void;
  // Same single-instance constraint as addLayer above (clobber safety).
  removeLayer: (projectId: string, layerId: string) => Promise<boolean>;
}

export function useProjectLifecycle(
  options: UseProjectLifecycleOptions,
): UseProjectLifecycleReturn {
  const { form, ui, uiState, editor, totalSteps, onGoToStep } = options;

  const formRef = useRef(form);
  formRef.current = form;

  const {
    projects,
    loadProject: loadSavedProject,
    deleteProject,
    renameProject,
    updateProject,
    updateProjectFormState,
    saveProject,
    addLayer,
    updateLayer,
    appendLayerTurn,
    removeLayer,
    persistError,
    clearError,
  } = useSavedProjects();

  const { isLoading: isGenerating, execute: executeGeneration } =
    useProjectGenerationFlow({
      saveProject,
      setActiveWorkspace: editor.setActiveWorkspace,
      setEditorSessionId: editor.setSessionId,
    });

  const {
    autoGeneratedSteps,
    setAutoGeneratedSteps,
    handleManifestLoaded,
    handleCancelNewProject,
  } = useProjectDialogHandlers({
    form,
    ui,
    uiState,
    onGoToStep,
  });

  const { activeWorkspace } = useActiveWorkspace();

  // Derive only the fields the useEffect actually needs, so isDirty toggles
  // don't re-trigger the effect (which only cares about projectId identity).
  const activeProjectId = activeWorkspace?.projectId;

  useEffect(() => {
    if (uiState.kind === "edit") return;
    if (!activeProjectId || projects.length === 0) return;

    const saved = loadSavedProject(activeProjectId);
    if (saved) {
      formRef.current.reset(saved.formState);
      setAutoGeneratedSteps(null);
      ui.enterEditMode(activeProjectId);
    }
  }, [
    activeProjectId,
    uiState.kind,
    projects.length,
    loadSavedProject,
    setAutoGeneratedSteps,
    ui,
  ]);

  const handleNext = useCallback(async () => {
    const f = formRef.current;
    const isValid =
      ui.currentStepIndex !== stepIndexById("bounded_contexts") ||
      (await f.trigger("boundedContexts"));
    if (!isValid) return;

    if (ui.currentStepIndex === stepIndexById("peer_mappings"))
      ui.setMappingId("");
    const nextStep = Math.min(ui.currentStepIndex + 1, totalSteps - 1);

    if (uiState.kind === "edit") {
      const formValues = f.getValues();
      // Import round-trip integrity (Item 1.2, the autosave clobber): for a
      // manifest-first project the stored manifestYaml is the RICH copy and
      // `wizardToManifest` is a lossy projection of it — persist only the
      // formState and leave manifestYaml untouched (updateProjectFormState is
      // the record-level writer that never touches it). Wizard-authored
      // projects keep the regenerate-on-autosave behavior unchanged.
      if (formValues.manifestSource === "imported") {
        updateProjectFormState(uiState.projectId, formValues);
      } else {
        const manifestData = wizardToManifest(
          formValues as Parameters<typeof wizardToManifest>[0],
        );
        updateProject(
          uiState.projectId,
          formValues,
          JSON.stringify(manifestData),
        );
      }
    }

    onGoToStep(nextStep);
  }, [
    ui,
    totalSteps,
    onGoToStep,
    uiState,
    updateProject,
    updateProjectFormState,
  ]);

  const handleBack = useCallback(() => {
    if (ui.currentStepIndex === stepIndexById("peer_mappings"))
      ui.setMappingId("");
    onGoToStep(Math.max(ui.currentStepIndex - 1, 0));
  }, [ui, onGoToStep]);

  const handleLoadProject = useCallback(
    async (id: string) => {
      const saved = loadSavedProject(id);
      if (!saved) return;

      const f = formRef.current;
      f.reset(saved.formState);
      setAutoGeneratedSteps(null);
      ui.enterEditMode(id);
      onGoToStep(0);
      ui.closeDialog();
      // Editor session is keyed on the active project's id by useEditorSession
      // (see its effect) — setActiveWorkspace below drives it. A random session
      // here would just be overwritten and wouldn't persist across reloads.
      editor.setActiveWorkspace({
        projectId: saved.id,
        name: saved.name,
        isDirty: false,
        lastModifiedAt: Date.now(),
        wizardData: { ...saved.formState },
        manifestYaml: saved.manifestYaml,
      });

      const url = new URL(window.location.href);
      url.searchParams.set("project", id);
      window.history.replaceState(null, "", url.toString());
    },
    [loadSavedProject, ui, editor, setAutoGeneratedSteps, onGoToStep],
  );

  const handleGenerate = useCallback(async () => {
    // Item 1.5 (handleGenerate parity): for a loaded imported project, hand the
    // flow the SAVED manifestYaml so generation runs off the rich manifest, not
    // the degraded `wizardToManifest(formValues)` projection. Wizard-authored
    // and genesis flows pass null and keep the projection path.
    const saved =
      uiState.kind === "edit" ? loadSavedProject(uiState.projectId) : null;
    await executeGeneration(
      formRef.current.getValues(),
      saved?.manifestYaml ?? null,
    );
  }, [executeGeneration, uiState, loadSavedProject]);

  const handleSaveAndNew = useCallback(async () => {
    const f = formRef.current;
    if (uiState.kind === "edit") {
      const formValues = f.getValues();
      // Same imported-manifest autosave guard as handleNext (the only other
      // updateProject caller): never overwrite the rich manifestYaml with the
      // degraded wizard projection.
      if (formValues.manifestSource === "imported") {
        updateProjectFormState(uiState.projectId, formValues);
      } else {
        const manifestData = wizardToManifest(
          formValues as Parameters<typeof wizardToManifest>[0],
        );
        updateProject(
          uiState.projectId,
          formValues,
          JSON.stringify(manifestData),
        );
      }
    }

    f.reset(emptyFormValues);
    setAutoGeneratedSteps(null);
    onGoToStep(0);
    ui.enterGenesisMode();
    ui.closeDialog();
    editor.clearSession();
    editor.clearActiveWorkspace();
  }, [
    uiState,
    updateProject,
    updateProjectFormState,
    ui,
    editor,
    setAutoGeneratedSteps,
    onGoToStep,
  ]);

  const handleDiscardAndNew = useCallback(async () => {
    const projectId =
      uiState.kind === "edit" ? uiState.projectId : crypto.randomUUID();

    await performDiscardProject({ projectId });

    performResetToGenesis({
      onEnterGenesisMode: ui.enterGenesisMode,
      onClearSession: editor.clearSession,
      onClearActiveWorkspace: editor.clearActiveWorkspace,
      onResetForm: () => formRef.current.reset(emptyFormValues),
      onCloseDialog: ui.closeDialog,
      onSetStep: onGoToStep,
    });
  }, [ui, editor, uiState, onGoToStep]);

  const loadedProject =
    uiState.kind === "edit"
      ? (loadSavedProject(uiState.projectId) ?? null)
      : null;

  return useMemo(
    () => ({
      projects,
      isGenerating,
      loadedProject,
      autoGeneratedSteps,
      deleteProject,
      renameProject,
      updateProjectFormState,
      addLayer,
      updateLayer,
      appendLayerTurn,
      layersPersistError: persistError,
      clearLayersPersistError: clearError,
      handleNext,
      handleBack,
      handleLoadProject,
      handleGenerate,
      handleManifestLoaded,
      handleSaveAndNew,
      handleDiscardAndNew,
      handleCancelNewProject,
      removeLayer,
    }),
    [
      projects,
      isGenerating,
      loadedProject,
      autoGeneratedSteps,
      deleteProject,
      renameProject,
      updateProjectFormState,
      addLayer,
      updateLayer,
      appendLayerTurn,
      persistError,
      clearError,
      handleNext,
      handleBack,
      handleLoadProject,
      handleGenerate,
      handleManifestLoaded,
      handleSaveAndNew,
      handleDiscardAndNew,
      handleCancelNewProject,
      removeLayer,
    ],
  );
}
