"use client";

import { useCallback, useRef, useState } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";
import {
  analyzeManifestCompleteness,
  type ManifestCompleteness,
} from "../../project-wizard/utils/analyzeManifestCompleteness";
import type {
  UseWorkspaceShellUiReturn,
  WorkspaceShellState,
} from "./useWorkspaceShellUi";
import { useManifestImport } from "./useManifestImport";

interface UseProjectDialogHandlersOptions {
  form: UseFormReturn<ProjectConfig>;
  ui: UseWorkspaceShellUiReturn;
  uiState: WorkspaceShellState;
  onGoToStep: (index: number) => void;
}

export function useProjectDialogHandlers(
  options: UseProjectDialogHandlersOptions,
) {
  const { form, ui, onGoToStep } = options;
  const { importManifest } = useManifestImport();

  const formRef = useRef(form);
  formRef.current = form;

  const [autoGeneratedSteps, setAutoGeneratedSteps] =
    useState<ManifestCompleteness | null>(null);

  const handleManifestLoaded = useCallback(
    async (yamlContent: string) => {
      const outcome = await importManifest(yamlContent);
      if (outcome.kind === "success") {
        formRef.current.reset(outcome.formValues);
        const completeness = analyzeManifestCompleteness(outcome.formValues);
        setAutoGeneratedSteps(completeness);
        ui.enterEditMode("");
        ui.closeDialog();
        onGoToStep(completeness.firstIncompleteStepIndex);
      } else {
        window.alert(
          outcome.message ||
            "Failed to parse the generated manifest. Please try regenerating.",
        );
      }
    },
    [importManifest, ui, onGoToStep],
  );

  const handleCancelNewProject = useCallback(() => {
    ui.closeDialog();
  }, [ui]);

  return {
    autoGeneratedSteps,
    setAutoGeneratedSteps,
    handleManifestLoaded,
    handleCancelNewProject,
  };
}
