"use client";

import { useCallback, useState } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";
import {
  analyzeManifestCompleteness,
  type ManifestCompleteness,
} from "../../project-wizard/utils/analyzeManifestCompleteness";
import type {
  UseWorkspaceShellUiReturn,
  WorkspaceShellState,
} from "./useWorkspaceShellUi";
import type { WizardDraft } from "@hexagen/shared";
import { useManifestImport } from "./useManifestImport";
import { logger } from "../../../lib/structured-logger";

interface UseProjectDialogHandlersOptions {
  form: UseFormReturn<ProjectConfig>;
  ui: UseWorkspaceShellUiReturn;
  uiState: WorkspaceShellState;
  draft: WizardDraft | null;
  clearDraft: () => Promise<void>;
  saveProject: (
    name: string,
    formState: ProjectConfig,
    manifestYaml: string,
  ) => string;
  setActiveWorkspace: (workspace: {
    projectId: string;
    name: string;
    isDirty: boolean;
    lastModifiedAt: number;
    wizardData: Record<string, unknown>;
    manifestYaml: string;
  }) => void;
  setSessionId: (id: string) => void;
}

function deriveProjectName(yamlContent: string): string {
  const match = yamlContent.match(/^system:\s*(.+)$/m);
  if (match?.[1]) {
    const raw = match[1].trim().replace(/^["']|["']$/g, "");
    if (raw) {
      return raw.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    }
  }
  return "AI Generated Project";
}

export function useProjectDialogHandlers(
  options: UseProjectDialogHandlersOptions,
) {
  const {
    form,
    ui,
    uiState,
    draft,
    clearDraft,
    saveProject,
    setActiveWorkspace,
    setSessionId,
  } = options;
  const { importManifest } = useManifestImport();

  const [autoGeneratedSteps, setAutoGeneratedSteps] =
    useState<ManifestCompleteness | null>(null);
  const [pendingWelcomeManifest, setPendingWelcomeManifest] = useState<
    string | null
  >(null);

  const handleManifestLoaded = useCallback(
    async (yamlContent: string) => {
      logger.info("[DEBUG] handleManifestLoaded called");
      const outcome = await importManifest(yamlContent);
      if (outcome.kind === "success") {
        logger.info("[DEBUG] Import success", { hasFormValues: !!outcome.formValues });
        form.reset(outcome.formValues);
        const completeness = analyzeManifestCompleteness(outcome.formValues);
        logger.info("[DEBUG] Completeness", { firstIncomplete: completeness.firstIncompleteStepIndex });
        setAutoGeneratedSteps(completeness);
        ui.enterEditMode("");
        logger.info("[DEBUG] Called ui.enterEditMode('')");
        ui.closeDialog();
        logger.info("[DEBUG] Called ui.setStep", { step: completeness.firstIncompleteStepIndex });
        ui.setStep(completeness.firstIncompleteStepIndex);
      } else {
        logger.info("[DEBUG] Import failed", { message: outcome.message });
        window.alert(
          outcome.message ||
            "Failed to parse the generated manifest. Please try regenerating.",
        );
      }
    },
    [importManifest, form, ui],
  );

  const handleWelcomeManifestGenerated = useCallback(
    async (yamlContent: string) => {
      try {
        logger.info("[DEBUG] handleWelcomeManifestGenerated called", { uiStateKind: uiState.kind });
        
        // Welcome screen is for generating NEW manifests, not editing existing ones.
        // Always treat manifest acceptance as a genesis-mode operation.
        logger.info("[DEBUG] Always treating welcome manifest as genesis (new project)");
        
        logger.info("[DEBUG] Genesis branch - calling handleManifestLoaded");
        await handleManifestLoaded(yamlContent);
        logger.info("[DEBUG] After handleManifestLoaded", { hasFormValues: !!form.getValues() });
        const name = deriveProjectName(yamlContent);
        logger.info("[DEBUG] Derived project name", { name });
        const projectId = saveProject(name, form.getValues(), yamlContent);
        logger.info("[DEBUG] Saved project with ID", { projectId });
        ui.enterEditMode(projectId);
        logger.info("[DEBUG] Called ui.enterEditMode with projectId", { projectId });
        await clearDraft();
        setActiveWorkspace({
          projectId,
          name,
          isDirty: false,
          lastModifiedAt: Date.now(),
          wizardData: form.getValues() as unknown as Record<string, unknown>,
          manifestYaml: yamlContent,
        });
        setSessionId(crypto.randomUUID());
        logger.info("[DEBUG] Completed all updates");
      } catch (error) {
        logger.error("[DEBUG] Error in handleWelcomeManifestGenerated", { error: error instanceof Error ? error.message : String(error) });
      }
    },
    [
      ui,
      handleManifestLoaded,
      saveProject,
      setActiveWorkspace,
      setSessionId,
      form,
      clearDraft,
    ],
  );

  const handleResumeDraft = useCallback(() => {
    if (!draft) return;
    form.reset(draft.formState as ProjectConfig);
    setAutoGeneratedSteps(null);
    ui.setStep(0);
    ui.enterEditMode("");
    ui.closeDialog();
  }, [draft, form, ui]);

  const handleDiscardDraft = useCallback(async () => {
    await clearDraft();
    ui.closeDialog();
    ui.openDialog({ kind: "welcome-manifest" });
  }, [clearDraft, ui]);

  const handleCancelNewProject = useCallback(() => {
    setPendingWelcomeManifest(null);
    ui.closeDialog();
  }, [ui]);

  return {
    autoGeneratedSteps,
    setAutoGeneratedSteps,
    pendingWelcomeManifest,
    handleManifestLoaded,
    handleWelcomeManifestGenerated,
    handleResumeDraft,
    handleDiscardDraft,
    handleCancelNewProject,
  };
}
