"use client";

import { useCallback, useEffect, useState } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { emptyFormValues } from "../../project-wizard/config";

import { useSavedProjects, type SavedProject } from "@/hooks/useSavedProjects";
import { useWizardDraft } from "./useWizardDraft";
import { useManifestImport } from "./useManifestImport";
import { useProjectGenerationFlow } from "./useProjectGenerationFlow";
import { useWizardAutosave } from "./useWizardAutosave";
import { useBeforeUnloadWarning } from "./useBeforeUnloadWarning";
import type { WizardDraft } from "@hexagen/shared";
import {
  analyzeManifestCompleteness,
  type ManifestCompleteness,
} from "../../project-wizard/utils/analyzeManifestCompleteness";
import type {
  UseWorkspaceShellUiReturn,
  WorkspaceShellState,
} from "./useWorkspaceShellUi";
import type { UseEditorSessionReturn } from "./useEditorSession";
import {
  loadProject as performLoadProject,
  updateProject as performUpdateProject,
  discardProject as performDiscardProject,
  resetToGenesis as performResetToGenesis,
} from "@/lib/use-cases/project-lifecycle.use-case";

interface UseProjectLifecycleOptions {
  form: UseFormReturn<ProjectConfig>;
  ui: UseWorkspaceShellUiReturn;
  uiState: WorkspaceShellState;
  editor: Pick<
    UseEditorSessionReturn,
    | "setSessionId"
    | "clearSession"
    | "setActiveWorkspace"
    | "clearActiveWorkspace"
  >;
  totalSteps: number;
}

export interface UseProjectLifecycleReturn {
  projects: SavedProject[];
  draft: WizardDraft | null;
  isGenerating: boolean;
  loadedProject: SavedProject | null;
  autoGeneratedSteps: ManifestCompleteness | null;

  deleteProject: (id: string) => void;
  renameProject: (id: string, name: string) => void;

  handleNext: () => Promise<void>;
  handleBack: () => void;
  handleLoadProject: (id: string) => Promise<void>;
  handleGenerate: () => Promise<void>;
  handleManifestLoaded: (yamlContent: string) => Promise<void>;
  handleWelcomeManifestGenerated: (yamlContent: string) => Promise<void>;
  handleCancelNewProject: () => void;
  handleResumeDraft: () => void;
  handleDiscardDraft: () => Promise<void>;
  handleSaveAndNew: () => void;
  handleDiscardAndNew: () => void;
}

export function useProjectLifecycle(
  options: UseProjectLifecycleOptions,
): UseProjectLifecycleReturn {
  const { form, ui, uiState, editor, totalSteps } = options;

  const {
    projects,
    loadProject: loadSavedProject,
    deleteProject,
    renameProject,
    updateProject,
    saveProject,
  } = useSavedProjects();

  const {
    draft,
    saveDraft,
    clearDraft,
    loading: draftLoading,
  } = useWizardDraft();

  const { importManifest } = useManifestImport();

  const { isLoading: isGenerating, execute: executeGeneration } =
    useProjectGenerationFlow({
      saveProject,
      clearDraft,
      setActiveWorkspace: editor.setActiveWorkspace,
      setEditorSessionId: editor.setSessionId,
    });

  const [pendingWelcomeManifest, setPendingWelcomeManifest] = useState<
    string | null
  >(null);
  const [autoGeneratedSteps, setAutoGeneratedSteps] =
    useState<ManifestCompleteness | null>(null);

  const hasGenerated = uiState.kind === "edit";

  useWizardAutosave({
    currentStepIndex: ui.currentStepIndex,
    hasGenerated,
    draftLoading,
    saveDraft,
    getFormValues: form.getValues,
  });

  useBeforeUnloadWarning({
    hasDraft: draft !== null,
    hasGenerated,
  });

  useEffect(() => {
    if (!draftLoading && draft && uiState.kind !== "edit") {
      ui.openDialog({ kind: "resume-draft", projectId: "" });
    } else if (
      !draftLoading &&
      !draft &&
      projects.length === 0 &&
      uiState.kind !== "edit"
    ) {
      ui.openDialog({ kind: "welcome-manifest" });
    }
  }, [draftLoading, draft, projects.length, ui.openDialog, uiState.kind]);

  const handleNext = useCallback(async () => {
    const isValid =
      ui.currentStepIndex !== 1 || (await form.trigger("boundedContexts"));
    if (!isValid) return;

    if (ui.currentStepIndex === 2) ui.setMappingId("");
    const nextStep = Math.min(ui.currentStepIndex + 1, totalSteps - 1);
    ui.setStep(nextStep);
    saveDraft(form.getValues(), nextStep);
  }, [ui, form, totalSteps, saveDraft]);

  const handleBack = useCallback(() => {
    if (ui.currentStepIndex === 2) ui.setMappingId("");
    ui.setStep(Math.max(ui.currentStepIndex - 1, 0));
  }, [ui]);

  const handleLoadProject = useCallback(
    async (id: string) => {
      const saved = loadSavedProject(id);
      if (!saved) return;

      form.reset(saved.formState);
      setAutoGeneratedSteps(null);
      ui.enterEditMode(id);
      ui.setStep(0);
      ui.closeDialog();
      await performLoadProject(saved, clearDraft);
      editor.setSessionId(crypto.randomUUID());
      editor.setActiveWorkspace({
        projectId: saved.id,
        name: saved.name,
        isDirty: false,
        lastModifiedAt: Date.now(),
        wizardData: { ...saved.formState },
        manifestYaml: saved.manifestYaml,
      });
    },
    [loadSavedProject, form, ui, clearDraft, editor],
  );

  const handleGenerate = useCallback(async () => {
    await executeGeneration(form.getValues());
  }, [executeGeneration, form]);

  const handleManifestLoaded = useCallback(
    async (yamlContent: string) => {
      const outcome = await importManifest(yamlContent);
      if (outcome.kind === "success") {
        form.reset(outcome.formValues);
        const completeness = analyzeManifestCompleteness(outcome.formValues);
        setAutoGeneratedSteps(completeness);
        ui.enterEditMode("");
        ui.closeDialog();
        ui.setStep(completeness.firstIncompleteStepIndex);
      } else {
        window.alert(
          outcome.message ||
            "Failed to parse the generated manifest. Please try regenerating.",
        );
      }
    },
    [importManifest, form, ui],
  );

  const handleWelcomeManifestGenerated = useCallback(
    async (yamlContent: string) => {
      if (uiState.kind === "edit") {
        setPendingWelcomeManifest(yamlContent);
        ui.openDialog({ kind: "new-project" });
      } else {
        await handleManifestLoaded(yamlContent);
      }
    },
    [uiState.kind, ui, handleManifestLoaded],
  );

  const handleResumeDraft = useCallback(() => {
    if (!draft) return;
    form.reset(draft.formState as ProjectConfig);
    setAutoGeneratedSteps(null);
    ui.setStep(0);
    ui.enterEditMode("");
    ui.closeDialog();
  }, [draft, form, ui]);

  const handleDiscardDraft = useCallback(async () => {
    await clearDraft();
    ui.closeDialog();
    ui.openDialog({ kind: "welcome-manifest" });
  }, [clearDraft, ui]);

  const handleCancelNewProject = useCallback(() => {
    setPendingWelcomeManifest(null);
    ui.closeDialog();
  }, [ui]);

  const handleSaveAndNew = useCallback(async () => {
    if (uiState.kind === "edit") {
      performUpdateProject({
        projectId: uiState.projectId,
        formData: form.getValues(),
        updateProject,
      });
    }

    if (pendingWelcomeManifest) {
      const yamlContent = pendingWelcomeManifest;
      setPendingWelcomeManifest(null);
      await handleManifestLoaded(yamlContent);
      return;
    }

    form.reset(emptyFormValues);
    setAutoGeneratedSteps(null);
    ui.setStep(0);
    ui.enterGenesisMode();
    ui.closeDialog();
    editor.clearSession();
    editor.clearActiveWorkspace();
  }, [
    uiState,
    form,
    updateProject,
    ui,
    editor,
    pendingWelcomeManifest,
    handleManifestLoaded,
  ]);

  const handleDiscardAndNew = useCallback(async () => {
    const projectId =
      uiState.kind === "edit" ? uiState.projectId : crypto.randomUUID();

    await performDiscardProject({
      projectId,
      pendingWelcomeManifest,
      onSuccess: handleManifestLoaded,
    });

    if (pendingWelcomeManifest) {
      const yamlContent = pendingWelcomeManifest;
      setPendingWelcomeManifest(null);
      editor.clearSession();
      editor.clearActiveWorkspace();
      await handleManifestLoaded(yamlContent);
      return;
    }

    performResetToGenesis({
      onEnterGenesisMode: ui.enterGenesisMode,
      onClearSession: editor.clearSession,
      onClearActiveWorkspace: editor.clearActiveWorkspace,
      onResetForm: () => form.reset(emptyFormValues),
      onCloseDialog: ui.closeDialog,
      onSetStep: ui.setStep,
    });
  }, [form, ui, editor, uiState, pendingWelcomeManifest, handleManifestLoaded]);

  const loadedProject =
    uiState.kind === "edit"
      ? (loadSavedProject(uiState.projectId) ?? null)
      : null;

  return {
    projects,
    draft,
    isGenerating,
    loadedProject,
    autoGeneratedSteps,
    deleteProject,
    renameProject,
    handleNext,
    handleBack,
    handleLoadProject,
    handleGenerate,
    handleManifestLoaded,
    handleWelcomeManifestGenerated,
    handleResumeDraft,
    handleDiscardDraft,
    handleSaveAndNew,
    handleDiscardAndNew,
    handleCancelNewProject,
  };
}
