"use client";

import { useCallback, useEffect, useMemo, useRef } from "react";
import type { UseFormReturn } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { emptyFormValues } from "../../project-wizard/config";

import { useSavedProjects, type SavedProject } from "@/hooks/useSavedProjects";
import { useActiveWorkspace } from "@/contexts/ActiveWorkspaceContext";
import { useProjectGenerationFlow } from "./useProjectGenerationFlow";
import { useProjectDialogHandlers } from "./useProjectDialogHandlers";
import type {
  UseWorkspaceShellUiReturn,
  WorkspaceShellState,
} from "./useWorkspaceShellUi";
import type { UseEditorSessionReturn } from "./useEditorSession";
import type { ManifestCompleteness } from "../../project-wizard/utils/analyzeManifestCompleteness";
import {
  discardProject as performDiscardProject,
  resetToGenesis as performResetToGenesis,
} from "@/lib/use-cases/project-lifecycle.use-case";
import { wizardToManifest } from "@hexagen/wizard-orchestration";

interface UseProjectLifecycleOptions {
  form: UseFormReturn<ProjectConfig>;
  ui: UseWorkspaceShellUiReturn;
  uiState: WorkspaceShellState;
  editor: Pick<
    UseEditorSessionReturn,
    | "setSessionId"
    | "clearSession"
    | "setActiveWorkspace"
    | "clearActiveWorkspace"
  >;
  totalSteps: number;
  onGoToStep: (index: number) => void;
}

export interface UseProjectLifecycleReturn {
  projects: SavedProject[];
  isGenerating: boolean;
  loadedProject: SavedProject | null;
  autoGeneratedSteps: ManifestCompleteness | null;

  deleteProject: (id: string) => void;
  renameProject: (id: string, name: string) => void;

  handleNext: () => Promise<void>;
  handleBack: () => void;
  handleLoadProject: (id: string) => Promise<void>;
  handleGenerate: () => Promise<void>;
  handleManifestLoaded: (yamlContent: string) => Promise<void>;
  handleCancelNewProject: () => void;
  handleSaveAndNew: () => void;
  handleDiscardAndNew: () => void;
}

export function useProjectLifecycle(
  options: UseProjectLifecycleOptions,
): UseProjectLifecycleReturn {
  const { form, ui, uiState, editor, totalSteps, onGoToStep } = options;

  const formRef = useRef(form);
  formRef.current = form;

  const {
    projects,
    loadProject: loadSavedProject,
    deleteProject,
    renameProject,
    updateProject,
    saveProject,
  } = useSavedProjects();

  const { isLoading: isGenerating, execute: executeGeneration } =
    useProjectGenerationFlow({
      saveProject,
      setActiveWorkspace: editor.setActiveWorkspace,
      setEditorSessionId: editor.setSessionId,
    });

  const {
    autoGeneratedSteps,
    setAutoGeneratedSteps,
    handleManifestLoaded,
    handleCancelNewProject,
  } = useProjectDialogHandlers({
    form,
    ui,
    uiState,
    onGoToStep,
  });

  const { activeWorkspace } = useActiveWorkspace();

  // Derive only the fields the useEffect actually needs, so isDirty toggles
  // don't re-trigger the effect (which only cares about projectId identity).
  const activeProjectId = activeWorkspace?.projectId;

  useEffect(() => {
    if (uiState.kind === "edit") return;
    if (!activeProjectId || projects.length === 0) return;

    const saved = loadSavedProject(activeProjectId);
    if (saved) {
      formRef.current.reset(saved.formState);
      setAutoGeneratedSteps(null);
      ui.enterEditMode(activeProjectId);
    }
  }, [
    activeProjectId,
    uiState.kind,
    projects.length,
    loadSavedProject,
    setAutoGeneratedSteps,
    ui,
  ]);

  const handleNext = useCallback(async () => {
    const currentForm = formRef.current;
    const isValid =
      ui.currentStepIndex !== 1 ||
      (await currentForm.trigger("boundedContexts"));
    if (!isValid) return;

    if (ui.currentStepIndex === 2) ui.setMappingId("");
    const nextStep = Math.min(ui.currentStepIndex + 1, totalSteps - 1);

    if (uiState.kind === "edit") {
      const formValues = currentForm.getValues();
      const manifestData = wizardToManifest(
        formValues as Parameters<typeof wizardToManifest>[0],
      );
      updateProject(
        uiState.projectId,
        formValues,
        JSON.stringify(manifestData),
      );
    }

    onGoToStep(nextStep);
  }, [ui, totalSteps, onGoToStep, uiState, updateProject]);

  const handleBack = useCallback(() => {
    if (ui.currentStepIndex === 2) ui.setMappingId("");
    onGoToStep(Math.max(ui.currentStepIndex - 1, 0));
  }, [ui, onGoToStep]);

  const handleLoadProject = useCallback(
    async (id: string) => {
      const saved = loadSavedProject(id);
      if (!saved) return;

      formRef.current.reset(saved.formState);
      setAutoGeneratedSteps(null);
      ui.enterEditMode(id);
      onGoToStep(0);
      ui.closeDialog();
      editor.setSessionId(crypto.randomUUID());
      editor.setActiveWorkspace({
        projectId: saved.id,
        name: saved.name,
        isDirty: false,
        lastModifiedAt: Date.now(),
        wizardData: { ...saved.formState },
        manifestYaml: saved.manifestYaml,
      });

      const url = new URL(window.location.href);
      url.searchParams.set("project", id);
      window.history.replaceState(null, "", url.toString());
    },
    [loadSavedProject, ui, editor, setAutoGeneratedSteps, onGoToStep],
  );

  const handleGenerate = useCallback(async () => {
    await executeGeneration(formRef.current.getValues());
  }, [executeGeneration]);

  const handleSaveAndNew = useCallback(async () => {
    const currentForm = formRef.current;
    if (uiState.kind === "edit") {
      const formValues = currentForm.getValues();
      const manifestData = wizardToManifest(
        formValues as Parameters<typeof wizardToManifest>[0],
      );
      updateProject(
        uiState.projectId,
        formValues,
        JSON.stringify(manifestData),
      );
    }

    currentForm.reset(emptyFormValues);
    setAutoGeneratedSteps(null);
    onGoToStep(0);
    ui.enterGenesisMode();
    ui.closeDialog();
    editor.clearSession();
    editor.clearActiveWorkspace();
  }, [uiState, updateProject, ui, editor, setAutoGeneratedSteps, onGoToStep]);

  const handleDiscardAndNew = useCallback(async () => {
    const projectId =
      uiState.kind === "edit" ? uiState.projectId : crypto.randomUUID();

    await performDiscardProject({ projectId });

    performResetToGenesis({
      onEnterGenesisMode: ui.enterGenesisMode,
      onClearSession: editor.clearSession,
      onClearActiveWorkspace: editor.clearActiveWorkspace,
      onResetForm: () => formRef.current.reset(emptyFormValues),
      onCloseDialog: ui.closeDialog,
      onSetStep: onGoToStep,
    });
  }, [ui, editor, uiState, onGoToStep]);

  const loadedProject =
    uiState.kind === "edit"
      ? (loadSavedProject(uiState.projectId) ?? null)
      : null;

  return useMemo(
    () => ({
      projects,
      isGenerating,
      loadedProject,
      autoGeneratedSteps,
      deleteProject,
      renameProject,
      handleNext,
      handleBack,
      handleLoadProject,
      handleGenerate,
      handleManifestLoaded,
      handleSaveAndNew,
      handleDiscardAndNew,
      handleCancelNewProject,
    }),
    [
      projects,
      isGenerating,
      loadedProject,
      autoGeneratedSteps,
      deleteProject,
      renameProject,
      handleNext,
      handleBack,
      handleLoadProject,
      handleGenerate,
      handleManifestLoaded,
      handleSaveAndNew,
      handleDiscardAndNew,
      handleCancelNewProject,
    ],
  );
}
