import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import lodash from 'lodash';
const { kebabCase } = lodash;
import { fileURLToPath } from 'node:url';

import { createConsoleLogger } from './logger.js';
import {
  ArchitectureManifestSchema,
  type ArchitectureManifest,
} from './manifest-schema.js';

// Global logger (respects --quiet)
const args = process.argv.slice(2);
const quiet = args.includes('--quiet');
const logger = createConsoleLogger(quiet);

const force = args.includes('--force');
const forceRoot = args.includes('--force-root');
const dryRun = args.includes('--dry-run');
const strict = args.includes('--strict');

if (force) logger.info('Running in --force mode (non-root files)');
if (forceRoot) logger.info('Running in --force-root mode (root files allowed)');
if (dryRun) logger.info('Running in --dry-run mode (no writes performed)');
if (strict) logger.info('Running in --strict mode (lint failure blocks sync)');

const GENERATED_HEADER = `// Auto-generated by yarn sync — do not edit manually
// Changes will be overwritten on next sync
// Edit .architecture.yaml and run yarn sync instead
`;

const EXPECTED_GENERATOR_VERSION = '0.2.0';

const PROTECTED_ROOT_FILES = [
  'tsconfig.base.json',
  'tsconfig.json',
  'turbo.json',
  'package.json',
  'eslint.config.js',
  '.eslintrc.json',
  '.architecture.yaml',
  'yarn.lock',
];

function toPascalCase(str: string): string {
  return str
    .split(/[-_ ]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

async function isProtectedRoot(filePath: string): Promise<boolean> {
  const rel = path.relative(process.cwd(), filePath);
  return PROTECTED_ROOT_FILES.some((p) => rel === p || rel.startsWith(p + '/'));
}

async function isGeneratedFile(filePath: string): Promise<boolean> {
  try {
    const content = await fs.readFile(filePath, 'utf-8');
    return content.trim().startsWith(GENERATED_HEADER.trim());
  } catch {
    return false;
  }
}

async function safeWriteFile(
  filePath: string,
  content: string,
  forceOverride = false,
  dryRunMode = false
): Promise<'created' | 'updated' | 'unchanged' | 'skipped'> {
  if (dryRunMode) {
    logger.info(
      `[dry-run] Would ${forceOverride ? 'force-' : ''}write to ${filePath}`
    );
    return 'created';
  }

  if ((await isProtectedRoot(filePath)) && !forceOverride) {
    logger.warn(`Protected root file skipped: ${filePath} (use --force-root)`);
    return 'skipped';
  }

  const exists = await fs
    .access(filePath)
    .then(() => true)
    .catch(() => false);

  if (exists) {
    const isGen = await isGeneratedFile(filePath);
    if (!isGen && !forceOverride) {
      logger.warn(
        `Skipping non-generated file: ${filePath} (use --force to overwrite)`
      );
      return 'skipped';
    }

    const existing = await fs.readFile(filePath, 'utf-8');
    if (existing === content) {
      return 'unchanged';
    }
  }

  await fs.writeFile(filePath, content);
  return exists ? 'updated' : 'created';
}

async function loadAndValidateManifest(
  rootDir: string
): Promise<ArchitectureManifest> {
  const manifestPath = path.join(rootDir, '.architecture.yaml');

  let fileContent: string;
  try {
    fileContent = await fs.readFile(manifestPath, 'utf-8');
  } catch (err) {
    throw new Error(
      `Failed to read .architecture.yaml: ${(err as Error).message}`
    );
  }

  let rawManifest: unknown;
  try {
    rawManifest = yaml.load(fileContent);
  } catch (err) {
    throw new Error(
      `Invalid YAML in .architecture.yaml: ${(err as Error).message}`
    );
  }

  const result = ArchitectureManifestSchema.safeParse(rawManifest);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `${i.path.join('.')} - ${i.message}`)
      .join('\n');
    throw new Error(`Manifest validation failed:\n${issues}`);
  }

  const manifest = result.data;

  const currentVersion = manifest.generator?.version;
  if (currentVersion && currentVersion !== EXPECTED_GENERATOR_VERSION) {
    logger.warn(
      `manifest generator.version (${currentVersion}) does not match expected (${EXPECTED_GENERATOR_VERSION}). ` +
        `Update manifest or generator code to avoid drift.`
    );
  }

  logger.info(`Loaded and validated manifest for system: ${manifest.system}`);
  logger.info(`Found ${manifest.modules.length} modules`);

  return manifest;
}

async function ensureLayerFolders(
  moduleDir: string,
  layersConfig: Record<string, string> = {},
  dryRunMode: boolean = false
) {
  const defaultLayers = {
    domain: 'domain',
    application: 'application',
    infrastructure: 'infrastructure',
  };

  const effectiveLayers = { ...defaultLayers, ...layersConfig };

  for (const [layerName, folderName] of Object.entries(effectiveLayers)) {
    const layerPath = path.join(moduleDir, 'src', folderName);
    if (dryRunMode) {
      logger.info(`[dry-run] Would ensure layer folder: ${layerPath}`);
    } else {
      await fs.mkdir(layerPath, { recursive: true });
      logger.info(`Ensured layer folder: ${layerPath}`);
    }

    if (layerName === 'application') {
      const subfolders = ['use-cases', 'ports/in', 'ports/out'];
      for (const sub of subfolders) {
        const subPath = path.join(layerPath, sub);
        if (dryRunMode) {
          logger.info(`[dry-run] Would ensure application subfolder: ${sub}`);
        } else {
          await fs.mkdir(subPath, { recursive: true });
        }
      }
      if (!dryRunMode)
        logger.info(`Ensured application subfolders: ${subfolders.join(', ')}`);
    }

    if (layerName === 'infrastructure') {
      const subPath = path.join(layerPath, 'adapters');
      if (dryRunMode) {
        logger.info(
          `[dry-run] Would ensure infrastructure subfolder: adapters`
        );
      } else {
        await fs.mkdir(subPath, { recursive: true });
        logger.info(`Ensured infrastructure subfolder: adapters`);
      }
    }
  }
}

async function ensureNonEmptyLayerBarrel(
  layerPath: string,
  layerName: string,
  forceOverride = false,
  dryRunMode = false,
  reexportStyle: 'named' | 'star' = 'star'
) {
  const barrelPath = path.join(layerPath, 'index.ts');
  let content = `// ${layerName} layer barrel — generated by sync.ts\n`;

  content += 'export {};\n';

  const status = await safeWriteFile(
    barrelPath,
    content,
    forceOverride,
    dryRunMode
  );
  if (status !== 'unchanged' && status !== 'skipped') {
    logger.info(`Non-empty layer barrel ${status}: ${barrelPath}`);
  }
}

async function generateLayerBarrel(
  layerPath: string,
  layerName: string,
  reexportStyle: 'named' | 'star' = 'star',
  force: boolean = false,
  dryRun: boolean = false
) {
  await ensureNonEmptyLayerBarrel(
    layerPath,
    layerName,
    force,
    dryRun,
    reexportStyle
  );
}

async function generateOrUpdatePackageJson(
  moduleDir: string,
  moduleName: string,
  manifest: ArchitectureManifest,
  force: boolean = false,
  dryRun: boolean = false
) {
  const pkgPath = path.join(moduleDir, 'package.json');
  const scope = manifest.scope || 'hexagen';
  const pkgName = `@${scope}/${kebabCase(moduleName)}`;

  const defaults = manifest.generator?.sync?.packageJson ?? {
    private: true,
    version: '0.1.0',
    license: 'MIT',
    scripts: {
      build: 'tsc --build',
      lint: 'eslint src --ext .ts,.tsx',
      typecheck: 'tsc --noEmit',
    },
    baseDependencies: {},
    baseDevDependencies: {
      typescript: '^5.5.4',
      '@typescript-eslint/eslint-plugin': '^8.0.0',
      '@typescript-eslint/parser': '^8.0.0',
      eslint: '^9.0.0',
      'eslint-config-prettier': '^9.1.0',
    },
  };

  const moduleOverrides =
    manifest.modules.find((m) => m.name === moduleName)?.generator ?? {};
  const deps = {
    ...defaults.baseDependencies,
    ...moduleOverrides.dependencies,
  };
  const devDeps = {
    ...defaults.baseDevDependencies,
    ...moduleOverrides.devDependencies,
  };

  const newPkg = {
    name: pkgName,
    version: defaults.version,
    private: defaults.private,
    license: defaults.license,
    scripts: { ...defaults.scripts, ...manifest.workspaceDefaults?.scripts },
    dependencies: deps,
    devDependencies: devDeps,
  };

  const newContent = JSON.stringify(newPkg, null, 2) + '\n';
  const status = await safeWriteFile(pkgPath, newContent, force, dryRun);
  logger.info(`package.json ${status} for ${pkgName}`);
  return status;
}

async function generateOrUpdatePackageTsConfig(
  moduleDir: string,
  moduleName: string,
  manifest: ArchitectureManifest,
  force: boolean = false,
  dryRun: boolean = false
) {
  const tsConfigPath = path.join(moduleDir, 'tsconfig.json');

  const defaultTsConfig = {
    extends: './../../tsconfig.base.json',
    compilerOptions: {
      rootDir: 'src',
      outDir: 'dist',
      declaration: true,
      emitDeclarationOnly: true,
      declarationMap: true,
      composite: true,
      ...manifest.generator?.sync?.tsconfig?.compilerOptions,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist'],
  };

  const newContent = JSON.stringify(defaultTsConfig, null, 2) + '\n';
  const status = await safeWriteFile(tsConfigPath, newContent, force, dryRun);
  logger.info(`tsconfig.json ${status} for @hexagen/${kebabCase(moduleName)}`);
  return status;
}

async function syncRootTsConfigReferences(
  rootDir: string,
  manifest: ArchitectureManifest,
  force: boolean = false,
  dryRun: boolean = false
) {
  const rootTsConfigPath = path.join(
    rootDir,
    manifest.tsConfigRootFile || 'tsconfig.base.json'
  );

  let existingTsConfig: Record<string, any> = {};
  try {
    const content = await fs.readFile(rootTsConfigPath, 'utf-8');
    existingTsConfig = JSON.parse(content);
  } catch {
    logger.warn(`Root tsconfig not found or invalid – creating basic one`);
  }

  const newReferences = manifest.modules.map((mod) => ({
    path: `./packages/${mod.name}`,
  }));

  const newPaths: Record<string, string[]> = {};
  manifest.modules.forEach((mod) => {
    const kebab = kebabCase(mod.name);
    newPaths[`@hexagen/${kebab}`] = [`packages/${mod.name}/src/index.ts`];
    newPaths[`@hexagen/${kebab}/*`] = [`packages/${mod.name}/src/*`];
  });

  const updatedTsConfig = {
    ...existingTsConfig,
    compilerOptions: {
      ...existingTsConfig.compilerOptions,
      paths: {
        ...(existingTsConfig.compilerOptions?.paths || {}),
        ...newPaths,
      },
    },
    references: newReferences,
  };

  const newContent = JSON.stringify(updatedTsConfig, null, 2) + '\n';
  const status = await safeWriteFile(
    rootTsConfigPath,
    newContent,
    force,
    dryRun
  );
  logger.info(`Root tsconfig.base.json ${status}`);
  return status;
}

async function generateModuleRootBarrel(
  moduleDir: string,
  effectiveLayers: Record<string, string>,
  force: boolean = false,
  dryRun: boolean = false
) {
  const barrelPath = path.join(moduleDir, 'src', 'index.ts');
  const header = `// Auto-generated root barrel — edits will be overwritten on next sync\n\n`;

  const exports = Object.keys(effectiveLayers)
    .map((layer) => `export * from './${effectiveLayers[layer]}';`)
    .join('\n');

  const content = `${header}${exports}\n`;

  const status = await safeWriteFile(barrelPath, content, force, dryRun);
  if (status !== 'unchanged' && status !== 'skipped') {
    logger.info(`Root barrel ${status}`);
  }
  return status;
}

async function generateBarrelsForModule(
  moduleDir: string,
  manifest: ArchitectureManifest,
  force: boolean = false,
  dryRun: boolean = false
) {
  const barrelsConfig = manifest.generator?.sync?.barrels ?? {
    autoGenerate: true,
    perLayer: true,
    reexportStyle: 'star',
  };

  if (!barrelsConfig.autoGenerate) return;

  const layers = manifest.generator?.sync?.layers ?? {
    domain: 'domain',
    application: 'application',
    infrastructure: 'infrastructure',
  };

  for (const [layerName, folderName] of Object.entries(layers)) {
    const layerPath = path.join(moduleDir, 'src', folderName);
    if (barrelsConfig.perLayer) {
      await generateLayerBarrel(
        layerPath,
        layerName,
        barrelsConfig.reexportStyle,
        force,
        dryRun
      );
    }
  }

  await generateModuleRootBarrel(moduleDir, layers, force, dryRun);
}

// Entity / Value Object stub generator
async function generateEntityOrValueObjectStub(
  moduleDir: string,
  name: string,
  isValueObject = false,
  force = false,
  dryRun = false
) {
  const pascal = toPascalCase(name);
  const kebab = kebabCase(name);
  const entityDir = path.join(moduleDir, 'src', 'domain', 'model', kebab);
  const entityPath = path.join(entityDir, `${kebab}.ts`);

  const type = isValueObject ? 'Value Object' : 'Entity';
  const content = `// ${pascal} ${type} — generated by sync.ts

export class ${pascal} {
  constructor(
    // TODO: properties from manifest
  ) {}

  // TODO: behavior / invariants
}
`;

  if (dryRun) {
    logger.info(`[dry-run] Would generate ${type}: ${entityPath}`);
    return 'created';
  }

  await fs.mkdir(entityDir, { recursive: true });
  const status = await safeWriteFile(entityPath, content, force, dryRun);
  logger.info(`${type} ${status}: ${entityPath}`);
  return status;
}

// Use Case stub generator
async function generateUseCaseStub(
  moduleDir: string,
  name: string,
  force = false,
  dryRun = false
) {
  const pascal = toPascalCase(name);
  const kebab = kebabCase(name);
  const useCasePath = path.join(
    moduleDir,
    'src',
    'application',
    'use-cases',
    `${kebab}.ts`
  );

  const content = `// ${pascal} Use Case — generated by sync.ts

import type { I${pascal}Port } from '../ports/in/${kebab}.port';

export class ${pascal}UseCase implements I${pascal}Port {
  async execute(data: unknown): Promise<unknown> {
    // TODO: implement use case logic
    return {};
  }
}
`;

  if (dryRun) {
    logger.info(`[dry-run] Would generate Use Case: ${useCasePath}`);
    return 'created';
  }

  const status = await safeWriteFile(useCasePath, content, force, dryRun);
  logger.info(`Use Case ${status}: ${useCasePath}`);
  return status;
}

// Port stub generator
async function generatePortStub(
  moduleDir: string,
  name: string,
  isInbound = false,
  force = false,
  dryRun = false
) {
  const pascal = toPascalCase(name);
  const kebab = kebabCase(name);
  const portsDir = path.join(
    moduleDir,
    'src',
    'application',
    'ports',
    isInbound ? 'in' : 'out'
  );
  const portPath = path.join(portsDir, `${kebab}.port.ts`);

  const content = isInbound
    ? `// Inbound Port for ${pascal} — generated by sync.ts

export interface I${pascal}Port {
  execute(data: unknown): Promise<unknown>;
}
`
    : `// Outbound Port for ${pascal} — generated by sync.ts

export interface I${pascal}Port {
  // TODO: define outbound operations
}
`;

  if (dryRun) {
    logger.info(
      `[dry-run] Would generate ${isInbound ? 'Inbound' : 'Outbound'} Port: ${portPath}`
    );
    return 'created';
  }

  const status = await safeWriteFile(portPath, content, force, dryRun);
  logger.info(
    `${isInbound ? 'Inbound' : 'Outbound'} Port ${status}: ${portPath}`
  );
  return status;
}

// Orchestrator for all stubs in a module
async function generateStubsForModule(
  moduleDir: string,
  module: ArchitectureManifest['modules'][number],
  force = false,
  dryRun = false
) {
  if (dryRun) {
    logger.info(`[dry-run] Generating stubs for module: ${module.name}`);
  }

  // Entities
  for (const entity of module.entities ?? []) {
    await generateEntityOrValueObjectStub(
      moduleDir,
      entity,
      false,
      force,
      dryRun
    );
  }

  // Value Objects
  for (const vo of module.value_objects ?? []) {
    await generateEntityOrValueObjectStub(moduleDir, vo, true, force, dryRun);
  }

  // Use Cases + Inbound Ports
  for (const uc of module.use_cases ?? []) {
    await generateUseCaseStub(moduleDir, uc, force, dryRun);
    await generatePortStub(moduleDir, uc, true, force, dryRun); // inbound
  }

  // Outbound Ports
  for (const port of module.ports?.out ?? []) {
    await generatePortStub(moduleDir, port, false, force, dryRun);
  }
}

async function runArchLinter(rootDir: string, strict: boolean = false) {
  logger.info('[sync] Running arch-linter for self-verification...');
  try {
    const { stdout, stderr } = await execPromise(
      'yarn workspace @hexagen/arch-linter run lint',
      {
        cwd: rootDir,
      }
    );
    logger.info(`[arch-linter] Output: ${stdout.trim()}`);
    if (stderr) logger.warn(`[arch-linter] Warnings/Errors: ${stderr.trim()}`);
    logger.info('[sync] Arch-linter passed successfully');
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`[sync] Arch-linter failed: ${msg}`);
    if (strict) {
      logger.error('[sync] --strict mode: lint failure blocks sync');
      process.exit(1);
    }
  }
}

async function main() {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const rootDir = path.resolve(__dirname, '../../..');

  let created = 0;
  let updated = 0;
  let skipped = 0;
  let unchanged = 0;

  const updateCounters = (
    status: 'created' | 'updated' | 'unchanged' | 'skipped'
  ) => {
    if (status === 'created') created++;
    else if (status === 'updated') updated++;
    else if (status === 'skipped') skipped++;
    else if (status === 'unchanged') unchanged++;
  };

  try {
    const manifest = await loadAndValidateManifest(rootDir);

    for (const currentModule of manifest.modules) {
      const moduleDir = path.join(rootDir, 'packages', currentModule.name);
      logger.info(`Processing module: ${currentModule.name} → ${moduleDir}`);

      const srcDir = path.join(moduleDir, 'src');
      if (dryRun) {
        logger.info(`[dry-run] Would ensure src folder: ${srcDir}`);
      } else {
        await fs.mkdir(srcDir, { recursive: true });
      }

      const layersConfig = manifest.generator?.sync?.layers ?? {};
      await ensureLayerFolders(moduleDir, layersConfig, dryRun);

      updateCounters(
        await generateOrUpdatePackageJson(
          moduleDir,
          currentModule.name,
          manifest,
          force,
          dryRun
        )
      );
      updateCounters(
        await generateOrUpdatePackageTsConfig(
          moduleDir,
          currentModule.name,
          manifest,
          force,
          dryRun
        )
      );

      await generateBarrelsForModule(moduleDir, manifest, force, dryRun);

      // Generate all domain stubs for this module
      await generateStubsForModule(moduleDir, currentModule, force, dryRun);
    }

    updateCounters(
      await syncRootTsConfigReferences(rootDir, manifest, forceRoot, dryRun)
    );

    logger.info('\n[sync] Summary:');
    logger.info(`  Created:   ${created}`);
    logger.info(`  Updated:   ${updated}`);
    logger.info(`  Unchanged: ${unchanged}`);
    logger.info(`  Skipped:   ${skipped}`);

    if (dryRun) {
      logger.info('\n[dry-run] No files were actually written.');
      logger.info('Protected root files skipped unless --force-root used.');
      logger.info('Non-empty barrels ensured in all layers.');
    }

    if (!dryRun) {
      await runArchLinter(rootDir, strict);
    }

    logger.info(
      '[sync] Step 8 complete – self-verified, version checked, stubs generated'
    );
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`Sync failed: ${msg}`);
    process.exit(1);
  }
}

main().catch((err) => {
  const msg = err instanceof Error ? err.message : String(err);
  logger.error(`Sync failed: ${msg}`);
  process.exit(1);
});
