// @generated by @hexagen/sync
import type { Manifest } from "../../../domain/model/manifest-schema/manifest-schema";
import type { RenderedManifest } from "@hexagen/agentic-interaction";

export interface RenderManifestPort {
  execute(input: Manifest): Promise<RenderedManifest>;
}
