// @generated by @hexagen/sync
import type { Manifest } from "../../../domain/model/manifest-schema/manifest-schema";

export interface RenderedManifest {
  yaml: string;
  diagnostics: Array<{ code: string; message: string; path?: string }>;
  token: string;
}

export interface RenderManifestPort {
  execute(input: Manifest): Promise<RenderedManifest>;
}
