export function generateDataBuilder(entity: string): string {
  const builderClass = `${entity}Builder`;

  return `// @generated test data builder — edit freely
/**
 * Test data builder for ${entity}
 *
 * Provides fluent API for creating test instances with sensible defaults.
 * Generated by HexaGen test generator.
 */

import type { ${entity} } from '../../domain/model/${entity.toLowerCase()}.js';

export class ${builderClass} {
  private data: Partial<${entity}> = {
    // TODO: Add default values for ${entity} properties
    // Example:
    // id: 'test-id',
    // createdAt: new Date(),
  };

  /**
   * Override default values with custom data
   */
  with(overrides: Partial<${entity}>): this {
    this.data = { ...this.data, ...overrides };
    return this;
  }

  // TODO: Add fluent setter methods for each property
  // Example:
  // withId(id: string): this {
  //   this.data.id = id;
  //   return this;
  // }

  /**
   * Build the ${entity} instance
   */
  build(): ${entity} {
    // TODO: Validate required fields are present
    return this.data as ${entity};
  }

  /**
   * Build multiple instances with sequential IDs
   */
  buildMany(count: number): ${entity}[] {
    return Array.from({ length: count }, (_, i) => {
      // TODO: Customize sequential data (e.g., id, name)
      return this.build();
    });
  }
}

// Made with Bob
`;
}
