export function generateEnhancedTestDouble(
  port: string,
  methods: string[],
): string {
  const portName = port.replace(/Port$/i, "");
  const fakeClass = `${portName}Fake`;

  return `// @generated enhanced test double — edit freely
/**
 * Enhanced fake implementation of ${port}
 *
 * Includes:
 * - Configurable behavior stubs
 * - Spy functionality for interaction verification
 * - Helper methods for test setup
 *
 * Generated by HexaGen test generator.
 */

import type { ${port} } from '../../application/ports/out/${port.toLowerCase()}.js';
import type { Result } from '@hexagen/shared';

export class ${fakeClass} implements ${port} {
  // Spy tracking
  public calls: Map<string, unknown[][]> = new Map();

  // Configurable responses
  private responses: Map<string, unknown> = new Map();

  ${methods
    .map(
      (method) => `
  /**
   * ${method} implementation with spy tracking
   */
  async ${method}(...args: unknown[]): Promise<Result<unknown, Error>> {
    // Track call
    if (!this.calls.has('${method}')) {
      this.calls.set('${method}', []);
    }
    this.calls.get('${method}')!.push(args);

    // Return configured response or default
    const response = this.responses.get('${method}');
    if (response !== undefined) {
      return response as Result<unknown, Error>;
    }

    // Default success response
    return { success: true, value: null };
  }

  /**
   * Configure response for ${method}
   */
  given${method.charAt(0).toUpperCase() + method.slice(1)}Returns(response: Result<unknown, Error>): void {
    this.responses.set('${method}', response);
  }

  /**
   * Verify ${method} was called
   */
  verify${method.charAt(0).toUpperCase() + method.slice(1)}Called(times?: number): boolean {
    const calls = this.calls.get('${method}') || [];
    return times === undefined ? calls.length > 0 : calls.length === times;
  }

  /**
   * Get arguments from ${method} calls
   */
  get${method.charAt(0).toUpperCase() + method.slice(1)}Calls(): unknown[][] {
    return this.calls.get('${method}') || [];
  }
  `,
    )
    .join("\n")}

  /**
   * Reset all spy data and configured responses
   */
  reset(): void {
    this.calls.clear();
    this.responses.clear();
  }
}

// Made with Bob
`;
}
