export function generateIntegrationTest(useCase: string): string {
  const useCaseClass = useCase;

  return `// @generated integration test template — edit freely
/**
 * Integration tests for ${useCaseClass}
 *
 * Tests the use case with real adapters and dependencies.
 * Generated by HexaGen test generator.
 */

import { describe, it, beforeAll, afterAll } from 'node:test';
import assert from 'node:assert/strict';
import { ${useCaseClass} } from '../../application/use-cases/${useCase.toLowerCase().replace(/usecase$/i, "")}.use-case.js';
// TODO: Import real adapters

describe('${useCaseClass} (Integration)', () => {
  // TODO: Add setup for real dependencies (database, external services, etc.)

  beforeAll(async () => {
    // TODO: Initialize test environment
    // - Set up test database
    // - Configure external service mocks
    // - Initialize dependency container
  });

  afterAll(async () => {
    // TODO: Clean up test environment
    // - Close database connections
    // - Clean up test data
    // - Shut down services
  });

  describe('end-to-end flow', () => {
    it('should complete full workflow with real adapters', async () => {
      // Arrange
      // TODO: Set up test data in database
      const input = {
        // TODO: Add test input data
      };

      // Act
      // TODO: Wire up use case with real adapters
      // const useCase = new ${useCaseClass}(realAdapter1, realAdapter2);
      // const result = await useCase.execute(input);

      // Assert
      // TODO: Verify database state
      // TODO: Verify external service calls
      // assert.strictEqual(result.success, true);
    });

    it('should handle real-world error scenarios', async () => {
      // Arrange
      // TODO: Set up error condition (e.g., database constraint violation)

      // Act
      // TODO: Execute use case

      // Assert
      // TODO: Verify error handling and rollback
    });
  });
});

// Made with Bob
`;
}
