export function generateUnitTest(useCase: string, outPorts: string[]): string {
  const useCaseClass = useCase;
  const testDoubles = outPorts
    .map((port) => {
      const portName = port.replace(/Port$/i, "");
      const fakeName = `${portName}Fake`;
      return { port, portName, fakeName };
    })
    .filter((d) => d.portName);

  const imports = [
    `import { describe, it, beforeEach } from 'node:test';`,
    `import assert from 'node:assert/strict';`,
    `import { ${useCaseClass} } from '../../application/use-cases/${useCase.toLowerCase().replace(/usecase$/i, "")}.use-case.js';`,
    ...testDoubles.map(
      (d) =>
        `import { ${d.fakeName} } from '../doubles/ports/${d.portName.toLowerCase()}.fake.js';`,
    ),
  ].join("\n");

  const setupVars = testDoubles
    .map((d) => `  let ${d.portName.toLowerCase()}: ${d.fakeName};`)
    .join("\n");

  const setupInit = testDoubles
    .map((d) => `    ${d.portName.toLowerCase()} = new ${d.fakeName}();`)
    .join("\n");

  const constructorArgs = testDoubles
    .map((d) => d.portName.toLowerCase())
    .join(", ");

  return `// @generated unit test scaffold — edit freely
/**
 * Unit tests for ${useCaseClass}
 *
 * Generated by HexaGen test generator.
 * Follow AAA pattern: Arrange, Act, Assert
 */

${imports}

describe('${useCaseClass}', () => {
  let useCase: ${useCaseClass};
${setupVars}

  beforeEach(() => {
${setupInit}
    useCase = new ${useCaseClass}(${constructorArgs});
  });

  describe('execute', () => {
    it('should execute successfully with valid input', async () => {
      // Arrange
      const input = {
        // TODO: Add test input data
      };

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, true);
      // TODO: Add more assertions
    });

    it('should handle invalid input', async () => {
      // Arrange
      const input = {
        // TODO: Add invalid input data
      };

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, false);
      // TODO: Verify error details
    });

    it('should handle port failures gracefully', async () => {
      // Arrange
      const input = {
        // TODO: Add test input data
      };
      // TODO: Configure test double to simulate failure

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, false);
      // TODO: Verify error handling
    });
  });
});

// Made with Bob
`;
}
