// @generated by @hexagen/sync

export { generateRecursiveBarrels, CircularExportError } from "./recursive.js";
export type { BarrelGenerationReport } from "./recursive.js";
export {
  isGeneratedFile,
  generateBarrelContent,
  detectCircularExports,
  parseBarrelExports,
  isSourceFile,
  contentHash,
  GENERATED_MARKER,
  LEGACY_GENERATED_MARKER,
} from "./utils.js";
export type { CircularCheckResult, ExportEntry } from "./utils.js";
export {
  isExcludedDirectory,
  BARREL_EXCLUSIONS,
} from "../../config/barrel-exclusions.js";
