// @generated by @hexagen/sync

import crypto from "node:crypto";

/**
 * Markers used to identify generated files.
 * Files with these markers can be safely overwritten by the sync engine.
 */
export const GENERATED_MARKER = "// @generated by @hexagen/sync";
export const LEGACY_GENERATED_MARKER = "— generated by sync.ts";

/**
 * Check if file content was generated by the sync tool.
 * Recognizes both current and legacy markers.
 */
export function isGeneratedFile(content: string): boolean {
  return (
    content.includes(GENERATED_MARKER) ||
    content.includes(LEGACY_GENERATED_MARKER)
  );
}

/**
 * Compute SHA-256 hash of content for change detection.
 */
export function contentHash(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

/**
 * Result of circular dependency detection.
 */
export interface CircularCheckResult {
  hasCircular: boolean;
  cycle: string[] | null;
}

/**
 * Detect circular exports in a barrel export graph.
 *
 * @param exportGraph - Map of barrel path to list of paths it exports
 * @returns Result indicating if circular dependency exists and the cycle path
 */
export function detectCircularExports(
  exportGraph: Map<string, string[]>,
): CircularCheckResult {
  const visited = new Set<string>();
  const recursionStack = new Set<string>();
  const path: string[] = [];

  function dfs(node: string): string[] | null {
    if (recursionStack.has(node)) {
      // Found cycle — return the cycle path
      const cycleStart = path.indexOf(node);
      return [...path.slice(cycleStart), node];
    }

    if (visited.has(node)) {
      return null;
    }

    visited.add(node);
    recursionStack.add(node);
    path.push(node);

    const exports = exportGraph.get(node) ?? [];
    for (const exportPath of exports) {
      const cycle = dfs(exportPath);
      if (cycle) {
        return cycle;
      }
    }

    path.pop();
    recursionStack.delete(node);
    return null;
  }

  for (const node of exportGraph.keys()) {
    const cycle = dfs(node);
    if (cycle) {
      return { hasCircular: true, cycle };
    }
  }

  return { hasCircular: false, cycle: null };
}

/**
 * Export entry with type information.
 */
export interface ExportEntry {
  name: string;
  isDirectory: boolean;
}

/**
 * Generate barrel content for a list of export targets.
 *
 * @param entries - List of export entries with name and type info
 * @returns Generated barrel file content with marker
 */
export function generateBarrelContent(entries: ExportEntry[]): string | null {
  if (entries.length === 0) {
    return null; // Skip creating barrel for empty directories
  }

  const exportLines = entries
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((entry) => {
      // Directories export from ./name/index.js, files from ./name.js
      const path = entry.isDirectory
        ? `./${entry.name}/index.js`
        : `./${entry.name}.js`;
      return `export * from '${path}';`;
    });

  return `${GENERATED_MARKER}\n\n${exportLines.join("\n")}\n`;
}

/**
 * Extract export targets from barrel content.
 * Parses `export * from './foo.js';` statements.
 *
 * @param content - Barrel file content
 * @returns List of exported module names (without .js extension)
 */
export function parseBarrelExports(content: string): string[] {
  const exportRegex = /export \* from ['"]\.\/([^'"]+)\.js['"];/g;
  const exports: string[] = [];
  let match;

  while ((match = exportRegex.exec(content)) !== null) {
    exports.push(match[1]);
  }

  return exports;
}

/**
 * Determine if a file is a TypeScript source file (not declaration or test).
 */
export function isSourceFile(filename: string): boolean {
  return (
    filename.endsWith(".ts") &&
    !filename.endsWith(".d.ts") &&
    !filename.endsWith(".test.ts") &&
    !filename.endsWith(".spec.ts") &&
    filename !== "index.ts"
  );
}
