/**
 * Wave C 6.7(a)-FIX (HEX-025 prereq) — machine gate for the twice-bitten trap.
 *
 * 6.7(a) changes `packages/sync/src/generators/layer-folders.ts` so unused
 * hexagonal layer folders stop being emitted. Two prior PRs gated that emitter
 * on Hexagen self-regen only and missed external / foreign trees. This suite
 * checks in a **non-Hexagen** repo fixture and spawns the real built binaries
 * (`hexagen-lint` → `dist/cli.js`, `hexagen sync --check` → packages/sync
 * `dist/cli.js`) against it.
 *
 * The fixture is a boring Node library (`lib/index.js`), not a generated
 * Hexagen app: no `// @generated by @hexagen/sync` markers, no `src/domain`
 * layout. A conventional-only tree would make the later empty-folder change
 * invisible. `generator.sync.layers` is still declared so the emitter is
 * armed. 6.7(a) stopped unused-folder emission; the Layers pin is 0
 * created — proof the emitter was re-run on this external tree, not
 * only against Hexagen self-regen.
 */
import { describe, it, beforeAll, expect } from "vitest";
import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURE = path.join(__dirname, "external-repo");
const LINT_CLI = path.join(__dirname, "..", "dist", "cli.js");
const SYNC_CLI = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "packages",
  "sync",
  "dist",
  "cli.js",
);

const SKIP_NON_POSIX = false; // PROBE(explore/win32-unskip): run everything on Windows to see what breaks
const GENERATED_MARKER = "@generated by @hexagen/sync";
const SKIP_DIR_NAMES = new Set(["node_modules", ".git", "dist"]);

interface RunResult {
  code: number;
  stdout: string;
  stderr: string;
}

function describeResult(r: RunResult): string {
  return `exit=${r.code}\n--- stdout ---\n${r.stdout}\n--- stderr ---\n${r.stderr}`;
}

function runNode(
  scriptPath: string,
  args: string[],
  cwd: string,
): Promise<RunResult> {
  return new Promise((resolve, reject) => {
    execFile(
      process.execPath,
      [scriptPath, ...args],
      { cwd, timeout: 120_000, maxBuffer: 10 * 1024 * 1024 },
      (error, stdout, stderr) => {
        if (error && typeof error.code !== "number") {
          reject(
            new Error(
              `${scriptPath} did not exit on its own (${error.code ?? error.signal ?? error.message})\n--- stdout ---\n${stdout}\n--- stderr ---\n${stderr}`,
            ),
          );
          return;
        }
        resolve({
          code: typeof error?.code === "number" ? error.code : 0,
          stdout,
          stderr,
        });
      },
    );
  });
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await fs.stat(target);
    return true;
  } catch {
    return false;
  }
}

/**
 * Regular files under `root` that a reviewer can inspect. Skips
 * dependency / VCS / build noise that should never be in this fixture.
 */
async function listInspectableFiles(root: string): Promise<string[]> {
  const files: string[] = [];
  async function walk(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (SKIP_DIR_NAMES.has(entry.name)) continue;
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(abs);
      } else if (entry.isFile()) {
        files.push(abs);
      }
    }
  }
  await walk(root);
  return files;
}

describe(
  "6.7(a)-FIX — non-Hexagen external-repo fixture",
  { skip: SKIP_NON_POSIX },
  () => {
    beforeAll(async () => {
      expect(
        await pathExists(LINT_CLI),
        `missing ${LINT_CLI} — build @hexagen/arch-linter before running this suite`,
      ).toBe(true);
      expect(
        await pathExists(SYNC_CLI),
        `missing ${SYNC_CLI} — build @hexagen/sync before running this suite`,
      ).toBe(true);
    });

    it("checks in a non-Hexagen tree with inspectable files (anti-vacuity)", async () => {
      const stat = await fs.stat(FIXTURE);
      expect(stat.isDirectory(), `fixture directory missing: ${FIXTURE}`).toBe(
        true,
      );

      const files = await listInspectableFiles(FIXTURE);
      expect(
        files.length,
        `fixture ${FIXTURE} has no inspectable files`,
      ).toBeGreaterThan(0);

      const rel = files.map((abs) => path.relative(FIXTURE, abs));
      expect(rel).toEqual(
        expect.arrayContaining(["lib/index.js", "package.json"]),
      );
      expect(
        rel.some((p) => p === "src/domain" || p.startsWith("src/domain/")),
      ).toBe(false);
      expect(await pathExists(path.join(FIXTURE, "src", "domain"))).toBe(false);

      for (const abs of files) {
        const text = await fs.readFile(abs, "utf8");
        expect(
          text.includes(GENERATED_MARKER),
          `${path.relative(FIXTURE, abs)} carries a Hexagen generated marker`,
        ).toBe(false);
      }
    });

    it("spawns built hexagen-lint against the fixture", async () => {
      const files = await listInspectableFiles(FIXTURE);
      expect(files.length).toBeGreaterThan(0);

      const r = await runNode(LINT_CLI, ["--root", FIXTURE], FIXTURE);
      const combined = `${r.stdout}\n${r.stderr}`;

      // Exit 0: ran to completion, tree is compliant (cli.ts exit-code vocab).
      // Exit 2 would mean the gate never ran (zero files / missing tsconfig).
      expect(r.code, describeResult(r)).toBe(0);
      expect(combined, describeResult(r)).toMatch(/files scanned:\s*[1-9]\d*/i);
      expect(combined, describeResult(r)).toMatch(/Architecture is compliant/);
      // Root-resolution canary: --root must land on this fixture, not the host.
      expect(combined, describeResult(r)).toContain(FIXTURE);
      expect(combined, describeResult(r)).not.toMatch(
        /zero resolvable (source )?files/i,
      );
    });

    it("spawns built hexagen sync --check against the fixture", async () => {
      const files = await listInspectableFiles(FIXTURE);
      expect(files.length).toBeGreaterThan(0);

      // --allow-dirty: the fixture lives inside the host git worktree; without
      // it the self-regen git-clean check would fail on host dirt. --check
      // implies --dry-run (no writes, preflight skipped).
      const r = await runNode(
        SYNC_CLI,
        ["sync", "--check", "--allow-dirty"],
        FIXTURE,
      );
      const combined = `${r.stdout}\n${r.stderr}`;

      // Host-resolution canary: findWorkspaceRoot walks up for a workspaces
      // array, then falls back to the CLI's __dirname. If either probe leaked
      // onto this monorepo, we would process dozens of Hexagen contexts.
      expect(combined, describeResult(r)).toMatch(/Processed 1 modules/);
      expect(combined, describeResult(r)).toMatch(/string-kit/);
      expect(combined, describeResult(r)).not.toMatch(/manifest-generation/);

      // Documented fail-closed code: --check exits 1 when a plain sync would
      // change anything (cli.ts). This tree is not Hexagen-shaped, so other
      // generators (package.json / tsconfig / eslint) still plan creates.
      // Unused layer folders must NOT be among them.
      expect(r.code, describeResult(r)).toBe(1);
      expect(combined, describeResult(r)).toMatch(/Drift detected/);
      expect(combined, describeResult(r)).toMatch(/• Layers :/);

      // 6.7(a) tripwire. Pre-change the emitter mkdir'd every declared
      // layer on this foreign tree (`Layers : 12 created`). After unused-
      // folder emission stops the count is 0 — proving the emitter was
      // re-run here, not only against Hexagen self-regen. Keep the exact
      // pin: a looser pattern would let a partial skip pass.
      expect(combined, describeResult(r)).toMatch(/• Layers : 0 created/);
    });
  },
);
