import { z } from 'zod';
export declare const projectConfigSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    rootName: z.ZodString;
    workspaceScope: z.ZodDefault<z.ZodString>;
    contextName: z.ZodDefault<z.ZodString>;
    entities: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    useCases: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    persistenceAdapter: z.ZodDefault<z.ZodEnum<["Prisma", "TypeORM", "Mongoose", "Drizzle"]>>;
    messagingAdapter: z.ZodDefault<z.ZodEnum<["BullMQ", "Temporal", "RabbitMQ"]>>;
    telemetryProvider: z.ZodDefault<z.ZodOptional<z.ZodEnum<["OpenTelemetry", "None"]>>>;
    apiFramework: z.ZodDefault<z.ZodOptional<z.ZodEnum<["Fastify", "Express", "NestJS"]>>>;
    uiFramework: z.ZodDefault<z.ZodOptional<z.ZodEnum<["Next.js", "React Router", "Remix", "Angular"]>>>;
    externalApiPorts: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    withLlm: z.ZodDefault<z.ZodBoolean>;
    withBlockchain: z.ZodDefault<z.ZodBoolean>;
    llmProviders: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    blockchainNetworks: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
}, "strip", z.ZodTypeAny, {
    rootName: string;
    workspaceScope: string;
    contextName: string;
    entities: string[];
    useCases: string[];
    persistenceAdapter: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle";
    messagingAdapter: "BullMQ" | "Temporal" | "RabbitMQ";
    telemetryProvider: "OpenTelemetry" | "None";
    apiFramework: "Fastify" | "Express" | "NestJS";
    uiFramework: "Next.js" | "React Router" | "Remix" | "Angular";
    externalApiPorts: string[];
    withLlm: boolean;
    withBlockchain: boolean;
    llmProviders: string[];
    blockchainNetworks: string[];
}, {
    rootName: string;
    workspaceScope?: string | undefined;
    contextName?: string | undefined;
    entities?: string[] | undefined;
    useCases?: string[] | undefined;
    persistenceAdapter?: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle" | undefined;
    messagingAdapter?: "BullMQ" | "Temporal" | "RabbitMQ" | undefined;
    telemetryProvider?: "OpenTelemetry" | "None" | undefined;
    apiFramework?: "Fastify" | "Express" | "NestJS" | undefined;
    uiFramework?: "Next.js" | "React Router" | "Remix" | "Angular" | undefined;
    externalApiPorts?: string[] | undefined;
    withLlm?: boolean | undefined;
    withBlockchain?: boolean | undefined;
    llmProviders?: string[] | undefined;
    blockchainNetworks?: string[] | undefined;
}>, {
    rootName: string;
    workspaceScope: string;
    contextName: string;
    entities: string[];
    useCases: string[];
    persistenceAdapter: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle";
    messagingAdapter: "BullMQ" | "Temporal" | "RabbitMQ";
    telemetryProvider: "OpenTelemetry" | "None";
    apiFramework: "Fastify" | "Express" | "NestJS";
    uiFramework: "Next.js" | "React Router" | "Remix" | "Angular";
    externalApiPorts: string[];
    withLlm: boolean;
    withBlockchain: boolean;
    llmProviders: string[];
    blockchainNetworks: string[];
}, {
    rootName: string;
    workspaceScope?: string | undefined;
    contextName?: string | undefined;
    entities?: string[] | undefined;
    useCases?: string[] | undefined;
    persistenceAdapter?: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle" | undefined;
    messagingAdapter?: "BullMQ" | "Temporal" | "RabbitMQ" | undefined;
    telemetryProvider?: "OpenTelemetry" | "None" | undefined;
    apiFramework?: "Fastify" | "Express" | "NestJS" | undefined;
    uiFramework?: "Next.js" | "React Router" | "Remix" | "Angular" | undefined;
    externalApiPorts?: string[] | undefined;
    withLlm?: boolean | undefined;
    withBlockchain?: boolean | undefined;
    llmProviders?: string[] | undefined;
    blockchainNetworks?: string[] | undefined;
}>, {
    rootName: string;
    workspaceScope: string;
    contextName: string;
    entities: string[];
    useCases: string[];
    persistenceAdapter: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle";
    messagingAdapter: "BullMQ" | "Temporal" | "RabbitMQ";
    telemetryProvider: "OpenTelemetry" | "None";
    apiFramework: "Fastify" | "Express" | "NestJS";
    uiFramework: "Next.js" | "React Router" | "Remix" | "Angular";
    externalApiPorts: string[];
    withLlm: boolean;
    withBlockchain: boolean;
    llmProviders: string[];
    blockchainNetworks: string[];
}, {
    rootName: string;
    workspaceScope?: string | undefined;
    contextName?: string | undefined;
    entities?: string[] | undefined;
    useCases?: string[] | undefined;
    persistenceAdapter?: "Prisma" | "TypeORM" | "Mongoose" | "Drizzle" | undefined;
    messagingAdapter?: "BullMQ" | "Temporal" | "RabbitMQ" | undefined;
    telemetryProvider?: "OpenTelemetry" | "None" | undefined;
    apiFramework?: "Fastify" | "Express" | "NestJS" | undefined;
    uiFramework?: "Next.js" | "React Router" | "Remix" | "Angular" | undefined;
    externalApiPorts?: string[] | undefined;
    withLlm?: boolean | undefined;
    withBlockchain?: boolean | undefined;
    llmProviders?: string[] | undefined;
    blockchainNetworks?: string[] | undefined;
}>;
export type ProjectConfig = z.infer<typeof projectConfigSchema>;
//# sourceMappingURL=schema.d.ts.map