import path from "node:path";
import fs from "node:fs/promises";
import { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";
import { safeWriteFileAtomic } from "../fs-utils.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

export async function generateBarrels(
  moduleDir: string,
  config: SyncConfig,
  report?: { record: (type: string, target: string, message?: string) => void },
): Promise<GeneratorResult> {
  const result = createEmptyResult();
  const layers = ["domain", "application", "infrastructure"];

  for (const layer of layers) {
    const layerDir = path.join(moduleDir, layer);
    const filePath = path.join(layerDir, "index.ts");
    const exportLines: string[] = [];

    try {
      const entries = await fs.readdir(layerDir, { withFileTypes: true });
      for (const entry of entries) {
        if (
          entry.name === "index.ts" ||
          entry.name.startsWith(".") ||
          entry.name.endsWith(".d.ts") ||
          entry.name.endsWith(".d.ts.map")
        )
          continue;

        const name = entry.isDirectory()
          ? entry.name
          : entry.name.replace(/\.ts$/, "");
        exportLines.push(`export * from './${name}.js';`);
      }
    } catch (_) {
      /* Directory might not exist yet */
    }

    // NOTE: Shared kernel re-exports removed.
    // Each package imports from @hexagen/shared directly where needed.
    // Re-exporting from another package violates barrel-ownership-boundary.

    const content =
      exportLines.length > 0
        ? `${GENERATED_MARKER}\n\n${exportLines.join("\n")}\n`
        : `${GENERATED_MARKER}\n\n// No exports yet\n`;

    const status = await safeWriteFileAtomic(filePath, content, config, report);
    if (status === "created" || status === "updated") {
      result[status].push(filePath);
      result.totalOps++;
    }
  }

  return result;
}
