import path from "node:path";
import fs from "node:fs/promises";
import { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";
import { safeWriteFile } from "../fs-utils.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

/**
 * Generates barrel re-export files for each layer (domain, application, infrastructure).
 * Uses safeWriteFile for dry-run safety, protection, and idempotency.
 */
export async function generateBarrels(
  moduleDir: string,
  config: SyncConfig,
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  const layers = ["domain", "application", "infrastructure"];

  for (const layer of layers) {
    const filePath = path.join(moduleDir, layer, "index.ts");

    // Read all .ts files in the layer directory (excluding this index.ts)
    const exportLines: string[] = [];
    try {
      const entries = await fs.readdir(path.join(moduleDir, layer), {
        withFileTypes: true,
      });
      for (const entry of entries) {
        if (
          entry.isFile() &&
          entry.name.endsWith(".ts") &&
          entry.name !== "index.ts"
        ) {
          const base = entry.name.replace(/\.ts$/, "");
          // Export with .js extension for ESM compliance
          exportLines.push(`export * from './${base}.js';`);
        }
      }
    } catch (_) {
      // If directory missing, continue; safeWriteFile will create empty barrel
    }

    // Ensure shared kernel re‑exports (Result & ok) are present
    exportLines.unshift(
      `export * from '../shared/result.js';`,
      `export * from '../shared/ok.js';`,
    );

    const content = `${GENERATED_MARKER}\n\n${exportLines.join("\n")}\n`;

    const status = await safeWriteFile(filePath, content, config);

    if (status === "created") result.created.push(filePath);
    if (status === "updated") result.updated.push(filePath);
    if (status === "skipped" || status === "protected")
      result.skipped.push(filePath);
    result.totalOps += status === "created" || status === "updated" ? 1 : 0;
  }

  return result;
}
