import path from 'node:path';
import fs from 'node:fs/promises';
import { SyncConfig } from '../config.js';
import { createEmptyResult, type GeneratorResult } from '../results.js';
import { safeWriteFile } from '../fs-utils.js';

const GENERATED_MARKER = '// @generated by @hexagen/sync';

export async function generateBarrels(
  moduleDir: string,
  config: SyncConfig,
  allowShared: boolean = true // Passed from the invariant check in SyncEngine
): Promise<GeneratorResult> {
  const result = createEmptyResult();
  const layers = ['domain', 'application', 'infrastructure'];

  for (const layer of layers) {
    const layerDir = path.join(moduleDir, layer);
    const filePath = path.join(layerDir, 'index.ts');
    const exportLines: string[] = [];

    try {
      const entries = await fs.readdir(layerDir, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.name === 'index.ts' || entry.name.startsWith('.')) continue;

        // Upward reachability: export files as .js and folders as directories
        const name = entry.isDirectory()
          ? entry.name
          : entry.name.replace(/\.ts$/, '');
        exportLines.push(`export * from './${name}.js';`);
      }
    } catch (_) {
      /* Directory might not exist yet */
    }

    // Enforce Architectural Invariant: Shared Kernel Re-exports
    if (allowShared) {
      exportLines.unshift(
        `export * from '../shared/result.js';`,
        `export * from '../shared/ok.js';`
      );
    }

    const content = `${GENERATED_MARKER}\n\n${
      exportLines.length > 0 ? exportLines.join('\n') : 'export {};'
    }\n`;

    const status = await safeWriteFile(filePath, content, config);
    if (status === 'created' || status === 'updated') {
      result[status].push(filePath);
      result.totalOps++;
    }
  }

  return result;
}
