import path from "node:path";
import type { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";
import { safeWriteFileAtomic } from "../fs-utils.js";
import { interpolate } from "../template-engine.js";
import {
  resolveScope,
  type EslintConfig,
  type Manifest,
} from "../types/manifest.js";
import type { ReportRecorder } from "../domain/types.js";

/**
 * Marker inserted as the first line of the emitted `eslint.config.js` so that
 * `safeWriteFileAtomic` (via `isGeneratedFile`) recognises self-regenerated
 * configs and is willing to overwrite them, while leaving hand-written configs
 * (which lack the marker) protected on subsequent runs.
 *
 * `.js` files tolerate the comment natively — unlike JSON artefacts such as
 * `tsconfig.json`, where we cannot embed a marker and must rely on content
 * hashing for skip detection.
 */
const GENERATED_MARKER_LINE = "// @generated by @hexagen/sync";

/**
 * Built-in fallback template used when neither
 * `monorepo.workspaceDefaults.eslint.template` nor
 * `bounded_contexts[<name>].generator.eslint.template` is declared.
 *
 * Ported verbatim from the legacy `generateEslintConfig` in
 * `packages/project-generation/src/infrastructure/adapters/root-files.ts`
 * (adapter behaviour pre–Wave 6a), so projects generated without any manifest
 * eslint declaration keep their current working config.
 *
 * The `{packageName}` / `{scope}` placeholders the template engine supports
 * are not referenced here — the fallback is a static template, so
 * interpolation is effectively a no-op and produces zero warnings.
 */
const BUILTIN_FALLBACK_TEMPLATE = `import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
    },
  },
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
);
`;

/**
 * Resolve the eslint template body for a given bounded context using the
 * three-level merge cascade (mirrors {@link generateTsconfig} in
 * `packages/sync/src/generators/tsconfig.ts`):
 *
 *   per-context override > workspaceDefaults > built-in fallback
 *
 * `EslintConfig` currently carries only a single `template` string field, so
 * "merge" degenerates to "first populated wins" — we never splice partial
 * templates together. If a future structured form is added to
 * {@link EslintConfig}, this function is the sole point of change.
 */
function resolveTemplate(
  manifest: Manifest,
  moduleName: string,
  usePerContextOverride: boolean,
): { template: string; source: "per-context" | "workspace" | "fallback" } {
  // Per-context overrides are keyed by bounded-context name. Apps live in a
  // different namespace, so an app whose name happens to collide with a bounded
  // context must NOT inherit that context's package-intended eslint template —
  // callers pass usePerContextOverride: false for apps (workspace + fallback only).
  const contextOverride: EslintConfig | undefined = usePerContextOverride
    ? manifest.bounded_contexts?.find((c) => c.name === moduleName)?.generator
        ?.eslint
    : undefined;
  if (contextOverride?.template !== undefined) {
    return { template: contextOverride.template, source: "per-context" };
  }

  // Workspace defaults are canonically nested under `monorepo.workspaceDefaults`
  // but a legacy root-level `workspaceDefaults` is also supported (see the same
  // pattern in tsconfig.ts). Check root first so a future simplification wins
  // cleanly without a dedicated migration.
  const rootLevel: EslintConfig | undefined =
    manifest.workspaceDefaults?.eslint;
  if (rootLevel?.template !== undefined) {
    return { template: rootLevel.template, source: "workspace" };
  }
  const monorepoLevel: EslintConfig | undefined =
    manifest.monorepo?.workspaceDefaults?.eslint;
  if (monorepoLevel?.template !== undefined) {
    return { template: monorepoLevel.template, source: "workspace" };
  }

  return { template: BUILTIN_FALLBACK_TEMPLATE, source: "fallback" };
}

/**
 * Ensure the emitted content starts with the `@generated by @hexagen/sync`
 * marker, adding it only if missing. Manifest authors who embed the marker
 * themselves (e.g. to exercise a regeneration test fixture) will not see it
 * duplicated.
 */
function withGeneratedMarker(content: string): string {
  if (content.startsWith(GENERATED_MARKER_LINE)) {
    return content;
  }
  // A trailing newline on `content` is preserved; an absent trailing newline
  // stays absent — this function does not reformat the author's template.
  return `${GENERATED_MARKER_LINE}\n${content}`;
}

/**
 * Generate the `eslint.config.js` file for one bounded-context package.
 *
 * Pipeline:
 *
 *  1. Resolve the template via the three-level merge cascade
 *     (`resolveTemplate`).
 *  2. Interpolate `{packageName}` and `{scope}` — most eslint configs won't
 *     use these, so interpolation is typically a no-op.
 *  3. Prepend the `// @generated by @hexagen/sync` marker so a subsequent
 *     self-regen recognises our output and is allowed to overwrite it, while
 *     hand-written configs (no marker) remain protected by
 *     `safeWriteFileAtomic`'s `isGeneratedFile` check.
 *  4. Write atomically via `safeWriteFileAtomic` with
 *     `skipGeneratedCheck=false` (the default semantics).
 *
 * Interpolation warnings — placeholders that appeared in the template but
 * were absent from the variable map — are surfaced through the optional
 * `report` recorder as `"warning"` entries, and to the module logger via
 * `config.logger.warn`. Generation is NOT aborted: the placeholder is left
 * visible in the output (per `template-engine.ts` design), making the
 * authoring mistake obvious in the generated file.
 *
 * Errors encountered during resolution or writing are captured on the
 * returned {@link GeneratorResult} (`result.error` + `result.summary`) and
 * cause the generator to skip this package rather than abort the whole
 * engine run — consistent with {@link generateTsconfig} and per the
 * "Missing template + missing fallback → log error, skip" rule in the
 * Wave 2e task description.
 *
 * @param moduleDir  - Absolute path of the package directory (e.g.
 *                     `<targetRoot>/packages/<name>`).
 * @param moduleName - Bounded-context name, used as the manifest lookup key
 *                     and as the `{packageName}` interpolation value.
 * @param config     - Full {@link SyncConfig}, including the parsed
 *                     `manifest` and `workspaceRoot`.
 * @param report     - Optional recorder for structured reporting. Receives
 *                     `"warning"` entries for missing interpolation vars and
 *                     `"error"` entries for catastrophic failures.
 * @returns A {@link GeneratorResult} with the single `eslint.config.js` path
 *          categorised into `created` / `updated` / `skipped`.
 */
export async function generateEslintConfig(
  moduleDir: string,
  moduleName: string,
  config: SyncConfig,
  report?: ReportRecorder,
  options: { usePerContextOverride?: boolean } = {},
): Promise<GeneratorResult> {
  const result = createEmptyResult();
  const filePath = path.join(moduleDir, "eslint.config.js");

  try {
    const { template, source } = resolveTemplate(
      config.manifest,
      moduleName,
      options.usePerContextOverride ?? true,
    );

    // Defensive check: the built-in fallback is a static non-empty string, so
    // this branch is not reachable under normal use. It exists to honour the
    // Wave 2e "Missing template + missing fallback → log error, skip" contract
    // in case a future refactor replaces `BUILTIN_FALLBACK_TEMPLATE` with a
    // manifest-sourced default.
    if (typeof template !== "string" || template.length === 0) {
      const message = `No eslint template resolved for ${moduleName} (source: ${source}); skipping`;
      config.logger.error(message);
      if (report) report.record("error", filePath, message);
      result.skipped.push(filePath);
      result.summary = message;
      return result;
    }

    const scope = resolveScope(config.manifest);
    const { output: interpolated, warnings } = interpolate(template, {
      packageName: moduleName,
      scope,
    });

    for (const missingVar of warnings) {
      const message = `Missing interpolation variable "${missingVar}" in eslint template for ${moduleName} (source: ${source}); placeholder left verbatim`;
      config.logger.warn(message);
      if (report) report.record("warning", filePath, message);
    }

    const content = withGeneratedMarker(interpolated);

    const status = await safeWriteFileAtomic(
      filePath,
      content,
      config,
      report,
      false,
    );

    if (status === "created") result.created.push(filePath);
    if (status === "updated") result.updated.push(filePath);
    if (status === "skipped" || status === "protected")
      result.skipped.push(filePath);
    result.totalOps += status === "created" || status === "updated" ? 1 : 0;

    return result;
  } catch (err) {
    // Explicit error handling per AGENTS.md §5 / §9 — never silently swallow.
    const message = err instanceof Error ? err.message : String(err);
    result.error =
      err instanceof Error
        ? err
        : new Error(`eslint generation failed for ${moduleName}: ${message}`);
    result.summary = `eslint generation failed for ${moduleName}: ${message}`;
    config.logger.error(result.summary);
    if (report) report.record("error", filePath, result.summary);
    // Per Wave 2e error-handling contract: skip this package, do not abort.
    return result;
  }
}
