import path from 'node:path';
import yaml from 'js-yaml';
import fs from 'node:fs/promises';
import { SyncConfig } from '../config.js';
import { createEmptyResult, type GeneratorResult } from '../results.js';
import { safeWriteFile } from '../fs-utils.js';

// Typed shape for layers from .architecture/manifest.yaml
interface LayerConfig {
  folder: string;
  subfolders?: string[];
}

/**
 * Ensures layer folders exist for a module (domain, application, infrastructure).
 * Creates subfolders and barrels if missing.
 * Uses safeWriteFile for dry-run safety, protection, and idempotency.
 */
async function loadYaml<T>(filePath: string): Promise<T> {
  const content = await fs.readFile(filePath, 'utf8');
  return yaml.load(content) as T;
}

export async function ensureLayerFolders(
  moduleDir: string,
  layers: Record<string, LayerConfig>,
  config: SyncConfig
): Promise<GeneratorResult> {
  const result = createEmptyResult();
  // Load architectural invariants
  const layerRulesPath = path.join(
    config.workspaceRoot,
    '.architecture',
    'invariants',
    'layer-rules.yaml'
  );
  const linterConfigPath = path.join(
    config.workspaceRoot,
    '.architecture',
    'invariants',
    'linter-config.yaml'
  );
  const layerRules = await loadYaml<any>(layerRulesPath);
  const linterConfig = await loadYaml<any>(linterConfigPath);

  for (const [layerName, layerConfig] of Object.entries(layers)) {
    const layerPath = path.join(moduleDir, layerConfig.folder);

    try {
      await fs.mkdir(layerPath, { recursive: true });
      result.created.push(layerPath);
      result.totalOps += 1;
    } catch (e) {
      if (e instanceof Error && 'code' in e && e.code === 'EEXIST') {
        result.skipped.push(layerPath);
      } else {
        throw e;
      }
    }

    // Determine if this layer is allowed to re-export shared kernel utilities
    const rule = layerRules?.layers?.[layerName];
    // Determine shared re‑export eligibility based on layer rules and linter config
    let allowShared =
      rule?.allowed_imports?.some((imp: string) =>
        imp.includes('@hexagen/shared')
      ) ?? false;
    // Override if linter config explicitly restricts this package from importing shared
    const pkgRule = linterConfig?.package_rules?.find(
      (r: any) => r.name === layerName
    );
    if (
      pkgRule?.restricted_to?.some((imp: string) =>
        imp.includes('@hexagen/shared')
      )
    ) {
      allowShared = false;
    }

    // Ensure index.ts barrel if layer has subfolders or is leaf
    const barrelPath = path.join(layerPath, 'index.ts');
    // Generate export statements for all .ts files in this layer (excluding index.ts)
    const exportLines: string[] = [];
    try {
      const entries = await fs.readdir(layerPath, { withFileTypes: true });
      for (const entry of entries) {
        if (
          entry.isFile() &&
          entry.name.endsWith('.ts') &&
          entry.name !== 'index.ts'
        ) {
          const base = entry.name.replace(/\\.ts$/, '');
          exportLines.push(`export * from './${base}.js';`);
        }
      }
    } catch (_) {
      // ignore errors, fallback to empty barrel
    }
    // Conditionally add shared kernel re‑exports based on rule
    if (allowShared) {
      exportLines.unshift(
        `export * from '../shared/result.js';`,
        `export * from '../shared/ok.js';`
      );
    }
    const barrelContent = `// @generated by @hexagen/sync\n\n${exportLines.join('\n')}\n`;
    const barrelStatus = await safeWriteFile(barrelPath, barrelContent, config);

    if (barrelStatus === 'created') result.created.push(barrelPath);
    if (barrelStatus === 'updated') result.updated.push(barrelPath);
    if (barrelStatus === 'skipped' || barrelStatus === 'protected')
      result.skipped.push(barrelPath);
    result.totalOps +=
      barrelStatus === 'created' || barrelStatus === 'updated' ? 1 : 0;

    // Recurse into subfolders
    const subfolders = layerConfig.subfolders ?? [];
    for (const sub of subfolders) {
      const subPath = path.join(layerPath, sub);
      try {
        await fs.mkdir(subPath, { recursive: true });
        result.created.push(subPath);
        result.totalOps += 1;
      } catch (e) {
        if (e instanceof Error && 'code' in e && e.code === 'EEXIST') {
          result.skipped.push(subPath);
        } else {
          throw e;
        }
      }

      // Subfolder barrel – reuse same exportLines (shared re‑exports already applied above)
      const subBarrelPath = path.join(subPath, 'index.ts');
      const subBarrelStatus = await safeWriteFile(
        subBarrelPath,
        barrelContent,
        config
      );

      if (subBarrelStatus === 'created') result.created.push(subBarrelPath);
      if (subBarrelStatus === 'updated') result.updated.push(subBarrelPath);
      if (subBarrelStatus === 'skipped' || subBarrelStatus === 'protected')
        result.skipped.push(subBarrelPath);
      result.totalOps +=
        subBarrelStatus === 'created' || subBarrelStatus === 'updated' ? 1 : 0;
    }
  }

  return result;
}
