import path from "node:path";
import yaml from "js-yaml";
import fs from "node:fs/promises";
import { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";
import { safeWriteFileAtomic } from "../fs-utils.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

// Typed shape for layers from .architecture/manifest.yaml
interface LayerConfig {
  folder: string;
  subfolders?: string[];
}

/**
 * Safely load a YAML file, returning null if the file doesn't exist.
 */
async function loadYamlSafe<T>(filePath: string): Promise<T | null> {
  try {
    const content = await fs.readFile(filePath, "utf8");
    return yaml.load(content) as T;
  } catch (e: unknown) {
    if (
      e instanceof Error &&
      "code" in e &&
      (e as { code?: string }).code === "ENOENT"
    ) {
      return null;
    }
    throw e;
  }
}

/**
 * Generate barrel content by scanning a directory for .ts files and subdirectories.
 */
async function generateBarrelContent(dirPath: string): Promise<string> {
  const exportLines: string[] = [];

  try {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name === "index.ts" || entry.name.startsWith(".")) continue;

      if (entry.isFile() && entry.name.endsWith(".ts")) {
        const base = entry.name.replace(/\.ts$/, "");
        exportLines.push(`export * from './${base}.js';`);
      } else if (entry.isDirectory()) {
        // Re-export subdirectory barrels
        exportLines.push(`export * from './${entry.name}/index.js';`);
      }
    }
  } catch (e: unknown) {
    if (
      e instanceof Error &&
      "code" in e &&
      (e as { code?: string }).code === "ENOENT"
    ) {
      // Directory may not exist yet
    } else {
      throw e;
    }
  }

  // NOTE: Shared kernel re-exports removed.
  // Each package imports from the project's own shared kernel directly where needed.
  // Re-exporting from another package violates barrel-ownership-boundary.

  return exportLines.length > 0
    ? `${GENERATED_MARKER}\n\n${exportLines.join("\n")}\n`
    : `${GENERATED_MARKER}\n\n// No exports yet\n`;
}

/**
 * Ensures layer folders exist for a module (domain, application, infrastructure).
 * Creates subfolders and barrels if missing.
 * Uses safeWriteFile for dry-run safety, protection, and idempotency.
 */
export async function ensureLayerFolders(
  moduleDir: string,
  layers: Record<string, LayerConfig>,
  config: SyncConfig,
  report?: { record: (type: string, target: string, message?: string) => void },
): Promise<GeneratorResult> {
  const result = createEmptyResult();
  const { logger } = config;

  // Load architectural invariants with graceful fallback
  const layerRulesPath = path.join(
    config.workspaceRoot,
    ".architecture",
    "invariants",
    "layer-rules.yaml",
  );
  const layerRules =
    await loadYamlSafe<Record<string, unknown>>(layerRulesPath);

  if (!layerRules) {
    logger.warn("layer-rules.yaml not found — skipping layer rule enforcement");
  }

  for (const [, layerConfig] of Object.entries(layers)) {
    const layerPath = path.join(moduleDir, layerConfig.folder);

    try {
      await fs.mkdir(layerPath, { recursive: true });
      result.created.push(layerPath);
      result.totalOps += 1;
    } catch (e) {
      if (e instanceof Error && "code" in e && e.code === "EEXIST") {
        result.skipped.push(layerPath);
      } else {
        throw e;
      }
    }

    // Generate barrel for this layer
    const barrelPath = path.join(layerPath, "index.ts");
    const barrelContent = await generateBarrelContent(layerPath);
    const barrelStatus = await safeWriteFileAtomic(
      barrelPath,
      barrelContent,
      config,
      report,
    );

    if (barrelStatus === "created") result.created.push(barrelPath);
    if (barrelStatus === "updated") result.updated.push(barrelPath);
    if (barrelStatus === "skipped" || barrelStatus === "protected")
      result.skipped.push(barrelPath);
    result.totalOps +=
      barrelStatus === "created" || barrelStatus === "updated" ? 1 : 0;

    // Recurse into subfolders
    const subfolders = layerConfig.subfolders ?? [];
    for (const sub of subfolders) {
      const subPath = path.join(layerPath, sub);
      try {
        await fs.mkdir(subPath, { recursive: true });
        result.created.push(subPath);
        result.totalOps += 1;
      } catch (e) {
        if (e instanceof Error && "code" in e && e.code === "EEXIST") {
          result.skipped.push(subPath);
        } else {
          throw e;
        }
      }

      // Subfolder barrel — scan its own contents, not parent's
      const subBarrelPath = path.join(subPath, "index.ts");
      const subBarrelContent = await generateBarrelContent(subPath);
      const subBarrelStatus = await safeWriteFileAtomic(
        subBarrelPath,
        subBarrelContent,
        config,
        report,
      );

      if (subBarrelStatus === "created") result.created.push(subBarrelPath);
      if (subBarrelStatus === "updated") result.updated.push(subBarrelPath);
      if (subBarrelStatus === "skipped" || subBarrelStatus === "protected")
        result.skipped.push(subBarrelPath);
      result.totalOps +=
        subBarrelStatus === "created" || subBarrelStatus === "updated" ? 1 : 0;
    }
  }

  return result;
}
