const BUILTIN_PACKAGE_JSON_TEMPLATE = `{
  "name": "{system}",
  "private": true,
  "type": "module",
  "packageManager": "{packageManager}",
  "workspaces": {workspaces},
  "scripts": {
    "build": "turbo build",
    "dev": "turbo dev",
    "lint": "turbo lint",
    "typecheck": "turbo typecheck",
    "test": "turbo test",
    "clean": "turbo clean",
    "sync": "hexagen sync",
    "sync:dry": "hexagen sync --dry-run",
    "sync:force": "hexagen sync --force",
    "lint:arch": "hexagen arch validate",
    "templates:add": "hexagen add",
    "templates:validate": "hexagen validate-templates",
    "format": "prettier --write \\"**/*.{ts,tsx,md}\\""
  },
  "devDependencies": {
    "turbo": "^2.0.0",
    "typescript": "^5.5.4",
    "eslint": "^9.0.0",
    "prettier": "^3.0.0",
    "@hexagen-monaco/sync": "^0.1.0",
    "@hexagen-monaco/arch-linter": "^0.1.0"
  }
}`;

const BUILTIN_TSCONFIG_BASE_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "composite": true,
    "declaration": true,
    "emitDeclarationOnly": true,
    "paths": {
      "@{scope}/*": [
        "./packages/*/src/index.ts"
      ]
    }
  }
}`;

const BUILTIN_TURBO_TEMPLATE = `{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": [
        "^build"
      ],
      "outputs": [
        "dist/**"
      ]
    },
    "dev": {
      "cache": false,
      "persistent": true
    },
    "lint": {
      "dependsOn": [
        "^build"
      ]
    },
    "typecheck": {
      "outputs": [],
      "cache": true
    },
    "test": {
      "dependsOn": [
        "^build"
      ]
    }
  }
}`;

const BUILTIN_GITIGNORE_TEMPLATE = `# Dependencies
node_modules/
.yarn/cache
.yarn/install-state.gz
.pnp.*

# Build output
dist/
.turbo/
.next/
out/

# Test / coverage
coverage/

# Environment
.env
.env.*
!.env.example

# Logs & OS
*.log
.DS_Store
`;

const BUILTIN_YARNRC_TEMPLATE = `# Generated by hexagen. Corepack reads \`packageManager\` in package.json to
# select the Yarn version; the node-modules linker keeps installs conventional.
nodeLinker: node-modules
`;

// First-push bootstrap doc. {packageManager} is the manifest's package manager
// (e.g. yarn@4.12.0). One-time — see the note about deleting it after setup.
const BUILTIN_SETUP_MD_TEMPLATE = `# Setup

This project was scaffolded by hexagen. Before your first push:

\`\`\`bash
corepack enable                 # activate the pinned package manager
yarn install                    # resolves dependencies, writes yarn.lock
git add yarn.lock && git commit -m "chore: add lockfile"
git push
\`\`\`

Once \`yarn.lock\` is committed, you can switch CI to a reproducible install by
adding \`--immutable\` to the \`yarn install\` step in
\`.github/workflows/ci.yml\` (npm: \`npm ci\`; pnpm: \`pnpm install --frozen-lockfile\`).

**Notes**

- CI reads your package-manager version from \`package.json\` (\`packageManager\`)
  via Corepack, so bumping it stays in sync automatically — nothing to edit in
  \`ci.yml\`.
- **This file is a one-time bootstrap doc — delete it after your first push.**
  Its pre-lockfile guidance goes stale once \`yarn.lock\` is committed. (Run
  \`hexagen sync\` won't bring it back — it's a protected root file.)
`;

export {
  BUILTIN_PACKAGE_JSON_TEMPLATE,
  BUILTIN_TSCONFIG_BASE_TEMPLATE,
  BUILTIN_TURBO_TEMPLATE,
  BUILTIN_GITIGNORE_TEMPLATE,
  BUILTIN_YARNRC_TEMPLATE,
  BUILTIN_SETUP_MD_TEMPLATE,
};
