import path from "node:path";
import fs from "node:fs/promises";
import type { SyncConfig } from "../config.js";
import {
  createEmptyResult,
  recordWriteStatus,
  type GeneratorResult,
} from "../results.js";
import { safeWriteFileAtomic, isInScope } from "../fs-utils.js";
import type { ReportRecorder } from "../domain/types.js";

/**
 * The Result kernel written into a generated project's `shared` package. Mirrors
 * `@hexagen/shared`'s `Result` (a `{ success }`-discriminated union) so the
 * generic use-case stub's `return { success: false, error: ... }` typechecks.
 */
const RESULT_KERNEL = `// @generated by @hexagen/sync — shared Result kernel (edit freely)
/**
 * Result is the explicit success/failure type generated use-cases return.
 * Mirrors @hexagen/shared's Result. Created once, then preserved on re-sync.
 */
export type Result<T, E = unknown> =
  | { success: true; value: T }
  | { success: false; error: E };

export const ok = <T>(value: T): Result<T, never> => ({ success: true, value });
export const err = <E>(error: E): Result<never, E> => ({
  success: false,
  error,
});
`;

/**
 * Ensure the scaffolded `shared` package exports a `Result` type (#246).
 *
 * The generic use-case stub imports `Result` from `@{scope}/shared`; without a
 * matching export the generated project fails to typecheck (TS2305 — the package
 * resolves via the package-root barrel since #249, but has no `Result`). The
 * kernel is written under the `domain` layer so the recursive package-root barrel
 * (external mode) re-exports it automatically.
 *
 * EXTERNAL (API-driven) generation only. In `self-regen` (this monorepo) the
 * `shared` package is hand-maintained and already provides `Result` (from
 * `errors/result.ts`); writing a second `domain/result.ts` would re-export
 * `Result` twice and break the build (TS2308) — the same two-worlds hazard as the
 * package-root barrel (#249/#250). Only runs when a `shared` bounded context
 * exists (the convention the use-case import assumes; `wizardToManifest` always
 * emits one). Write-if-absent so a user's customized Result survives re-sync.
 * Must run before the pass-2 barrels.
 */
export async function generateSharedKernel(
  config: SyncConfig,
  report?: ReportRecorder,
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  if (config.mode !== "external") return result;

  const hasShared = (config.manifest.bounded_contexts ?? []).some(
    (bc) => bc.name?.toLowerCase() === "shared",
  );
  if (!hasShared) return result;

  const kernelPath = path.join(
    config.workspaceRoot,
    "packages",
    "shared",
    "src",
    "domain",
    "result.ts",
  );

  // Out-of-scope under --only: skip before the stat/mkdir so no directory is
  // created (safeWriteFileAtomic enforces the same check for the write).
  if (!isInScope(kernelPath, config)) {
    result.skipped.push(kernelPath);
    return result;
  }

  // Write-if-absent — preserve any user customization across re-syncs. (External
  // mode uses forceRoot, which bypasses safeWriteFileAtomic's preserve branch, so
  // we guard on existence explicitly here.)
  try {
    await fs.stat(kernelPath);
    result.skipped.push(kernelPath);
    return result;
  } catch (err) {
    // Only ENOENT (absent → create below) is expected; surface anything else
    // (EACCES, EISDIR, …) instead of masking it with a confusing write error.
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }

  // PR-A2: gate the mkdir under dry-run (it ran even with --dry-run; fires
  // whenever the kernel file is absent, i.e. every dry-run on a fresh target).
  if (!config.dryRun) {
    await fs.mkdir(path.dirname(kernelPath), { recursive: true });
  }
  const status = await safeWriteFileAtomic(
    kernelPath,
    RESULT_KERNEL,
    config,
    report,
    false,
  );
  recordWriteStatus(result, kernelPath, status);
  return result;
}
