import path from 'node:path';
import fs from 'node:fs/promises';
import { SyncConfig } from '../config.js';
import { createEmptyResult, type GeneratorResult } from '../results.js';
import { safeWriteFile } from '../fs-utils.js';

/**
 * Generates stub barrel files for missing domain/application/infrastructure pieces.
 * Uses safeWriteFile for dry-run safety, protection, and idempotency.
 * Stamps each barrel with @generated marker.
 */
export async function generateStubs(
  moduleDir: string,
  config: SyncConfig
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  const stubs = [
    // Domain barrel
    {
      dir: 'domain',
      file: 'index.ts',
      content: `// @generated by @hexagen/sync\n\nexport {};\n`,
    },
    // Application ports/in barrel
    {
      dir: 'application/ports/in',
      file: 'index.ts',
      content: `// @generated by @hexagen/sync\n\nexport {};\n`,
    },
    // Application ports/out barrel
    {
      dir: 'application/ports/out',
      file: 'index.ts',
      content: `// @generated by @hexagen/sync\n\nexport {};\n`,
    },
    // Application use-cases barrel
    {
      dir: 'application/use-cases',
      file: 'index.ts',
      content: `// @generated by @hexagen/sync\n\nexport {};\n`,
    },
    // Infrastructure adapters barrel
    {
      dir: 'infrastructure/adapters',
      file: 'index.ts',
      content: `// @generated by @hexagen/sync\n\nexport {};\n`,
    },
  ];

  for (const stub of stubs) {
    const filePath = path.join(moduleDir, stub.dir, stub.file);
    // Generate export statements for all .ts files in the stub directory (excluding index.ts)
    let exportLines: string[] = [];
    try {
      const entries = await fs.readdir(path.join(moduleDir, stub.dir), {
        withFileTypes: true,
      });
      for (const entry of entries) {
        if (
          entry.isFile() &&
          entry.name.endsWith('.ts') &&
          entry.name !== 'index.ts'
        ) {
          const base = entry.name.replace(/\\.ts$/, '');
          exportLines.push(`export * from './${base}.js';`);
        }
      }
    } catch (_) {
      // ignore errors, fallback to empty barrel
    }
    // Ensure shared kernel re‑exports (Result & ok) are present
    exportLines.unshift(
      `export * from '../shared/result.js';`,
      `export * from '../shared/ok.js';`
    );
    const content = `// @generated by @hexagen/sync\n\n${exportLines.join('\n')}\n`;
    const status = await safeWriteFile(filePath, content, config);

    if (status === 'created') result.created.push(filePath);
    if (status === 'updated') result.updated.push(filePath);
    if (status === 'skipped' || status === 'protected')
      result.skipped.push(filePath);
    result.totalOps += status === 'created' || status === 'updated' ? 1 : 0;
  }

  return result;
}
