import path from "node:path";
import fs from "node:fs/promises";
import { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";
import { safeWriteFileAtomic } from "../fs-utils.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

/**
 * Generates stub barrel files for missing domain/application/infrastructure pieces.
 * Uses safeWriteFile for dry-run safety, protection, and idempotency.
 * Stamps each barrel with @generated marker.
 */
export async function generateStubs(
  moduleDir: string,
  config: SyncConfig,
  report?: { record: (type: string, target: string, message?: string) => void },
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  const stubDirs = [
    "domain",
    "application/ports/in",
    "application/ports/out",
    "application/use-cases",
    "infrastructure/adapters",
  ];

  for (const stubDir of stubDirs) {
    const dirPath = path.join(moduleDir, stubDir);
    const filePath = path.join(dirPath, "index.ts");

    // Generate export statements for all .ts files in the directory (excluding index.ts)
    const exportLines: string[] = [];
    try {
      const entries = await fs.readdir(dirPath, { withFileTypes: true });
      for (const entry of entries) {
        if (entry.name === "index.ts" || entry.name.startsWith(".")) continue;

        if (entry.isFile() && entry.name.endsWith(".ts")) {
          const base = entry.name.replace(/\.ts$/, "");
          exportLines.push(`export * from './${base}.js';`);
        } else if (entry.isDirectory()) {
          // Re-export subdirectory barrels
          exportLines.push(`export * from './${entry.name}/index.js';`);
        }
      }
    } catch (_) {
      // Directory might not exist yet — will be created by ensureLayerFolders
    }

    // NOTE: Shared kernel re-exports removed.
    // Each package imports from @hexagen/shared directly where needed.
    // Re-exporting from another package violates barrel-ownership-boundary.

    const content =
      exportLines.length > 0
        ? `${GENERATED_MARKER}\n\n${exportLines.join("\n")}\n`
        : `${GENERATED_MARKER}\n\n// No exports yet\n`;

    const status = await safeWriteFileAtomic(filePath, content, config, report);

    if (status === "created") result.created.push(filePath);
    if (status === "updated") result.updated.push(filePath);
    if (status === "skipped" || status === "protected")
      result.skipped.push(filePath);
    result.totalOps += status === "created" || status === "updated" ? 1 : 0;
  }

  return result;
}
