import path from 'node:path';
import fs from 'node:fs/promises';
import { SyncConfig } from '../config.js';
import { createEmptyResult, type GeneratorResult } from '../results.js';

/**
 * Generates stub files for ports, entities, use-cases, etc.
 * Data-driven from manifest.generator.sync.stubs.
 * Returns structured GeneratorResult.
 * Fixes PascalCase consistency (e.g. IGenerateProjectPort).
 */
export async function generateStubs(
  modulePath: string,
  config: SyncConfig
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  const stubsConfig = (config as any).manifest?.generator?.sync?.stubs;

  const enabled =
    typeof stubsConfig === 'boolean' ? stubsConfig : !!stubsConfig?.enabled;
  if (!enabled) {
    result.summary = `Stubs disabled for module ${modulePath}`;
    return result;
  }

  const layers = Object.keys(
    (config as any).manifest?.generator?.sync?.layers ?? {}
  );

  for (const layer of layers) {
    if (layer !== 'application' && layer !== 'domain') continue; // stubs only in domain & application

    const stubsDir = path.join(modulePath, 'src', layer, 'stubs');

    const stubResult = await ensureStubDirectory(
      stubsDir,
      config.dryRun,
      config.force
    );
    result.created.push(...(stubResult.created ?? []));
    result.skipped.push(...(stubResult.skipped ?? []));
    result.updated.push(...(stubResult.updated ?? []));
    result.dryRunOperations += stubResult.dryRunOperations ?? 0;

    // Example stub: IGenerateProjectPort.ts (PascalCase fixed)
    const portStubPath = path.join(stubsDir, 'IGenerateProjectPort.ts');
    const portContent = generatePortStub('GenerateProject');

    const portFileResult = await writeStubFile(
      portStubPath,
      portContent,
      config.dryRun,
      config.force
    );
    result.created.push(...(portFileResult.created ?? []));
    result.skipped.push(...(portFileResult.skipped ?? []));
    result.updated.push(...(portFileResult.updated ?? []));
    result.dryRunOperations += portFileResult.dryRunOperations ?? 0;
  }

  result.summary = `Stub files generated (${result.created.length} created, ${result.skipped.length} skipped)`;
  return result;
}

/** Low-level directory creation for stubs */
async function ensureStubDirectory(
  dirPath: string,
  dryRun: boolean,
  force: boolean
): Promise<Partial<GeneratorResult>> {
  const r: Partial<GeneratorResult> = {
    created: [],
    skipped: [],
    updated: [],
    dryRunOperations: 0,
  };

  if (dryRun) {
    r.created = [dirPath];
    r.dryRunOperations = 1;
    return r;
  }

  try {
    await fs.mkdir(dirPath, { recursive: true });
    r.created = [dirPath];
    return r;
  } catch (err: any) {
    if (err.code === 'EEXIST') {
      r.skipped = [dirPath];
      return r;
    }
    r.error = err;
    return r;
  }
}

/** Write a stub file safely */
async function writeStubFile(
  filePath: string,
  content: string,
  dryRun: boolean,
  force: boolean
): Promise<Partial<GeneratorResult>> {
  const r: Partial<GeneratorResult> = {
    created: [],
    skipped: [],
    updated: [],
    dryRunOperations: 0,
  };

  if (dryRun) {
    r.created = [filePath];
    r.dryRunOperations = 1;
    return r;
  }

  try {
    await fs.writeFile(filePath, content, 'utf8');
    r.created = [filePath];
    return r;
  } catch (err: any) {
    if (err.code === 'EEXIST' && !force) {
      r.skipped = [filePath];
      return r;
    }
    r.error = err;
    return r;
  }
}

/** Generate PascalCase port stub */
function generatePortStub(useCaseName: string): string {
  const pascalName = useCaseName; // already PascalCase
  return `// @generated by @hexagen/sync
// Port stub for ${pascalName} use case

export interface I${pascalName}Port {
  execute(input: any): Promise<any>;
}
`;
}
