// test-generator.ts – Test scaffolding generator for unit tests, integration tests, and test data builders
// Part of Phase 4: Agent-Friendly Scaffolding
//
// This generator automatically creates:
// 1. Unit test scaffolds with AAA pattern (Arrange-Act-Assert)
// 2. Integration test templates with real adapter wiring
// 3. Test data builders for domain entities
//
// Reduces test writing time from 15-20 minutes to ~5 minutes per use case.

import fs from "node:fs";
import path from "node:path";
import type { SyncConfig } from "../config.js";
import { createEmptyResult, type GeneratorResult } from "../results.js";

/**
 * Reporter shape for diagnostic output
 */
type ReportRecorder = {
  record: (level: string, file: string, message: string) => void;
};

/**
 * Test generator configuration
 */
interface TestConfig {
  enabled?: boolean;
  unitTests?: {
    enabled?: boolean;
    outputPath?: string;
  };
  integrationTests?: {
    enabled?: boolean;
    outputPath?: string;
  };
  dataBuilders?: {
    enabled?: boolean;
    outputPath?: string;
  };
}

/**
 * Generate unit test scaffold for a use case
 */
function generateUnitTest(useCase: string, outPorts: string[]): string {
  const useCaseClass = useCase;
  const testDoubles = outPorts
    .map((port) => {
      const portName = port.replace(/Port$/i, "");
      const fakeName = `${portName}Fake`;
      return { port, portName, fakeName };
    })
    .filter((d) => d.portName);

  const imports = [
    `import { describe, it, beforeEach } from 'node:test';`,
    `import assert from 'node:assert/strict';`,
    `import { ${useCaseClass} } from '../../application/use-cases/${useCase.toLowerCase().replace(/usecase$/i, "")}.use-case.js';`,
    ...testDoubles.map(
      (d) =>
        `import { ${d.fakeName} } from '../doubles/ports/${d.portName.toLowerCase()}.fake.js';`,
    ),
  ].join("\n");

  const setupVars = testDoubles
    .map((d) => `  let ${d.portName.toLowerCase()}: ${d.fakeName};`)
    .join("\n");

  const setupInit = testDoubles
    .map((d) => `    ${d.portName.toLowerCase()} = new ${d.fakeName}();`)
    .join("\n");

  const constructorArgs = testDoubles
    .map((d) => d.portName.toLowerCase())
    .join(", ");

  return `// @generated unit test scaffold — edit freely
/**
 * Unit tests for ${useCaseClass}
 *
 * Generated by HexaGen test generator.
 * Follow AAA pattern: Arrange, Act, Assert
 */

${imports}

describe('${useCaseClass}', () => {
  let useCase: ${useCaseClass};
${setupVars}

  beforeEach(() => {
${setupInit}
    useCase = new ${useCaseClass}(${constructorArgs});
  });

  describe('execute', () => {
    it('should execute successfully with valid input', async () => {
      // Arrange
      const input = {
        // TODO: Add test input data
      };

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, true);
      // TODO: Add more assertions
    });

    it('should handle invalid input', async () => {
      // Arrange
      const input = {
        // TODO: Add invalid input data
      };

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, false);
      // TODO: Verify error details
    });

    it('should handle port failures gracefully', async () => {
      // Arrange
      const input = {
        // TODO: Add test input data
      };
      // TODO: Configure test double to simulate failure

      // Act
      const result = await useCase.execute(input);

      // Assert
      assert.strictEqual(result.success, false);
      // TODO: Verify error handling
    });
  });
});

// Made with Bob
`;
}

/**
 * Generate integration test template
 */
function generateIntegrationTest(useCase: string): string {
  const useCaseClass = useCase;

  return `// @generated integration test template — edit freely
/**
 * Integration tests for ${useCaseClass}
 *
 * Tests the use case with real adapters and dependencies.
 * Generated by HexaGen test generator.
 */

import { describe, it, beforeAll, afterAll } from 'node:test';
import assert from 'node:assert/strict';
import { ${useCaseClass} } from '../../application/use-cases/${useCase.toLowerCase().replace(/usecase$/i, "")}.use-case.js';
// TODO: Import real adapters

describe('${useCaseClass} (Integration)', () => {
  // TODO: Add setup for real dependencies (database, external services, etc.)

  beforeAll(async () => {
    // TODO: Initialize test environment
    // - Set up test database
    // - Configure external service mocks
    // - Initialize dependency container
  });

  afterAll(async () => {
    // TODO: Clean up test environment
    // - Close database connections
    // - Clean up test data
    // - Shut down services
  });

  describe('end-to-end flow', () => {
    it('should complete full workflow with real adapters', async () => {
      // Arrange
      // TODO: Set up test data in database
      const input = {
        // TODO: Add test input data
      };

      // Act
      // TODO: Wire up use case with real adapters
      // const useCase = new ${useCaseClass}(realAdapter1, realAdapter2);
      // const result = await useCase.execute(input);

      // Assert
      // TODO: Verify database state
      // TODO: Verify external service calls
      // assert.strictEqual(result.success, true);
    });

    it('should handle real-world error scenarios', async () => {
      // Arrange
      // TODO: Set up error condition (e.g., database constraint violation)

      // Act
      // TODO: Execute use case

      // Assert
      // TODO: Verify error handling and rollback
    });
  });
});

// Made with Bob
`;
}

/**
 * Generate test data builder for an entity
 */
function generateDataBuilder(entity: string): string {
  const builderClass = `${entity}Builder`;

  return `// @generated test data builder — edit freely
/**
 * Test data builder for ${entity}
 *
 * Provides fluent API for creating test instances with sensible defaults.
 * Generated by HexaGen test generator.
 */

import type { ${entity} } from '../../domain/model/${entity.toLowerCase()}.js';

export class ${builderClass} {
  private data: Partial<${entity}> = {
    // TODO: Add default values for ${entity} properties
    // Example:
    // id: 'test-id',
    // createdAt: new Date(),
  };

  /**
   * Override default values with custom data
   */
  with(overrides: Partial<${entity}>): this {
    this.data = { ...this.data, ...overrides };
    return this;
  }

  // TODO: Add fluent setter methods for each property
  // Example:
  // withId(id: string): this {
  //   this.data.id = id;
  //   return this;
  // }

  /**
   * Build the ${entity} instance
   */
  build(): ${entity} {
    // TODO: Validate required fields are present
    return this.data as ${entity};
  }

  /**
   * Build multiple instances with sequential IDs
   */
  buildMany(count: number): ${entity}[] {
    return Array.from({ length: count }, (_, i) => {
      // TODO: Customize sequential data (e.g., id, name)
      return this.build();
    });
  }
}

// Made with Bob
`;
}

/**
 * Generate enhanced test double with behavior stubs and spies
 * (Available for future use if needed)
 *
 * @internal Reserved for future enhancement
 */
export function generateEnhancedTestDouble(
  port: string,
  methods: string[],
): string {
  const portName = port.replace(/Port$/i, "");
  const fakeClass = `${portName}Fake`;

  return `// @generated enhanced test double — edit freely
/**
 * Enhanced fake implementation of ${port}
 *
 * Includes:
 * - Configurable behavior stubs
 * - Spy functionality for interaction verification
 * - Helper methods for test setup
 *
 * Generated by HexaGen test generator.
 */

import type { ${port} } from '../../application/ports/out/${port.toLowerCase()}.js';
import type { Result } from '@hexagen/shared';

export class ${fakeClass} implements ${port} {
  // Spy tracking
  public calls: Map<string, unknown[][]> = new Map();

  // Configurable responses
  private responses: Map<string, unknown> = new Map();

  ${methods
    .map(
      (method) => `
  /**
   * ${method} implementation with spy tracking
   */
  async ${method}(...args: unknown[]): Promise<Result<unknown, Error>> {
    // Track call
    if (!this.calls.has('${method}')) {
      this.calls.set('${method}', []);
    }
    this.calls.get('${method}')!.push(args);

    // Return configured response or default
    const response = this.responses.get('${method}');
    if (response !== undefined) {
      return response as Result<unknown, Error>;
    }

    // Default success response
    return { success: true, value: null };
  }

  /**
   * Configure response for ${method}
   */
  given${method.charAt(0).toUpperCase() + method.slice(1)}Returns(response: Result<unknown, Error>): void {
    this.responses.set('${method}', response);
  }

  /**
   * Verify ${method} was called
   */
  verify${method.charAt(0).toUpperCase() + method.slice(1)}Called(times?: number): boolean {
    const calls = this.calls.get('${method}') || [];
    return times === undefined ? calls.length > 0 : calls.length === times;
  }

  /**
   * Get arguments from ${method} calls
   */
  get${method.charAt(0).toUpperCase() + method.slice(1)}Calls(): unknown[][] {
    return this.calls.get('${method}') || [];
  }
  `,
    )
    .join("\n")}

  /**
   * Reset all spy data and configured responses
   */
  reset(): void {
    this.calls.clear();
    this.responses.clear();
  }
}

// Made with Bob
`;
}

/**
 * Main test generator function
 */
export async function generateTests(
  moduleDir: string,
  moduleName: string,
  config: SyncConfig,
  report?: ReportRecorder,
): Promise<GeneratorResult> {
  const result = createEmptyResult();

  // Access test config through unknown cast since it's not in the type yet
  const testConfig: TestConfig | undefined = (
    config.manifest.generator?.sync as unknown as { tests?: TestConfig }
  )?.tests;

  // Opt-in: must be explicitly enabled
  if (!testConfig || testConfig.enabled !== true) {
    return result;
  }

  const context = config.manifest.bounded_contexts?.find(
    (c) => c.name === moduleName,
  );

  if (!context) {
    config.logger.debug(
      `generateTests: no bounded context named '${moduleName}' in manifest`,
    );
    return result;
  }

  const useCases = context.layers?.application?.use_cases || [];
  const outPorts = context.layers?.application?.ports?.out || [];
  const entities = context.layers?.domain?.entities || [];

  if (useCases.length === 0) {
    config.logger.debug(
      `generateTests: no use cases found in '${moduleName}', skipping`,
    );
    return result;
  }

  // Generate unit tests if enabled
  if (testConfig.unitTests?.enabled) {
    const unitTestDir = path.join(
      moduleDir,
      testConfig.unitTests.outputPath || "__tests__/unit",
    );

    for (const useCase of useCases) {
      const testPath = path.join(
        unitTestDir,
        `${useCase.toLowerCase().replace(/usecase$/i, "")}.test.ts`,
      );

      const testContent = generateUnitTest(useCase, outPorts);

      // Write unit test file
      fs.mkdirSync(path.dirname(testPath), { recursive: true });
      fs.writeFileSync(testPath, testContent, "utf-8");

      result.created.push(testPath);
      config.logger.debug(
        `generateTests: created unit test for ${useCase} at ${testPath}`,
      );
    }

    if (report) {
      report.record(
        "info",
        unitTestDir,
        `Generated ${useCases.length} unit test scaffolds`,
      );
    }
  }

  // Generate integration tests if enabled
  if (testConfig.integrationTests?.enabled) {
    const integrationTestDir = path.join(
      moduleDir,
      testConfig.integrationTests.outputPath || "__tests__/integration",
    );

    for (const useCase of useCases) {
      const testPath = path.join(
        integrationTestDir,
        `${useCase.toLowerCase().replace(/usecase$/i, "")}.integration.test.ts`,
      );

      const testContent = generateIntegrationTest(useCase);

      // Write integration test file
      fs.mkdirSync(path.dirname(testPath), { recursive: true });
      fs.writeFileSync(testPath, testContent, "utf-8");

      result.created.push(testPath);
      config.logger.debug(
        `generateTests: created integration test for ${useCase} at ${testPath}`,
      );
    }

    if (report) {
      report.record(
        "info",
        integrationTestDir,
        `Generated ${useCases.length} integration test templates`,
      );
    }
  }

  // Generate test data builders if enabled
  if (testConfig.dataBuilders?.enabled && entities.length > 0) {
    const buildersDir = path.join(
      moduleDir,
      testConfig.dataBuilders.outputPath || "__tests__/builders",
    );

    for (const entity of entities) {
      const builderPath = path.join(
        buildersDir,
        `${entity.toLowerCase()}.builder.ts`,
      );

      const builderContent = generateDataBuilder(entity);

      // Write data builder file
      fs.mkdirSync(path.dirname(builderPath), { recursive: true });
      fs.writeFileSync(builderPath, builderContent, "utf-8");

      result.created.push(builderPath);
      config.logger.debug(
        `generateTests: created data builder for ${entity} at ${builderPath}`,
      );
    }

    if (report) {
      report.record(
        "info",
        buildersDir,
        `Generated ${entities.length} test data builders`,
      );
    }
  }

  return result;
}

// Made with Bob
