import {
  WorkspaceGovernanceStep,
  BoundedContextStep,
  PeerContextMappingStep,
  PortConfigurationStep,
  SummaryStep,
} from "./steps";
import { wizardSteps } from "./config";
import type { ViewMode } from "@/types/view-mode";

// eslint-disable-next-line hexagen-ui/no-feature-slice-imports
import { useWizardLifecycleContext } from "../workspace-shell/contexts/WizardLifecycleContext";

/**
 * Props for the WizardStepRouter component.
 */
interface WizardStepRouterProps {
  currentStepIndex: number;
  totalSteps: number;
  onViewModeChange: (mode: ViewMode) => void;
  activeContextId: string;
  activeMappingId: string;
  onContextSelect: (id: string) => void;
  onMappingSelect: (id: string) => void;
}

/**
 * Routes and renders the correct wizard step component based on the current step index.
 * Consumes lifecycle values from WizardLifecycleContext.
 */
export function WizardStepRouter({
  currentStepIndex,
  totalSteps,
  onViewModeChange,
  activeContextId,
  activeMappingId,
  onContextSelect,
  onMappingSelect,
}: WizardStepRouterProps) {
  const lifecycle = useWizardLifecycleContext();
  const currentStepConfig = wizardSteps[currentStepIndex];
  const title = currentStepConfig?.title ?? "";
  const description = currentStepConfig?.description ?? "";

  switch (currentStepIndex) {
    case 0:
      return (
        <WorkspaceGovernanceStep
          onNext={lifecycle.handleNext}
          canProceed={lifecycle.canProceed(1)}
          currentStep={1}
          totalSteps={totalSteps}
          title={title}
          description={description}
          readOnly={lifecycle.autoGeneratedSteps?.governance}
        />
      );
    case 1:
      return (
        <BoundedContextStep
          onNext={lifecycle.handleNext}
          onBack={lifecycle.handleBack}
          canProceed={lifecycle.canProceed(2)}
          activeContextId={activeContextId}
          onContextSelect={onContextSelect}
          currentStep={2}
          totalSteps={totalSteps}
          title={title}
          description={description}
          readOnly={lifecycle.autoGeneratedSteps?.boundedContexts}
        />
      );
    case 2:
      return (
        <PeerContextMappingStep
          onNext={lifecycle.handleNext}
          onBack={lifecycle.handleBack}
          canProceed={lifecycle.canProceed(3)}
          activeMappingId={activeMappingId}
          onMappingSelect={onMappingSelect}
          currentStep={3}
          totalSteps={totalSteps}
          title={title}
          description={description}
          readOnly={lifecycle.autoGeneratedSteps?.peerMappings}
        />
      );
    case 3:
      return (
        <PortConfigurationStep
          onNext={lifecycle.handleNext}
          onBack={lifecycle.handleBack}
          canProceed={lifecycle.canProceed(4)}
          currentStep={4}
          totalSteps={totalSteps}
          title={title}
          description={description}
          readOnly={lifecycle.autoGeneratedSteps?.portConfiguration}
        />
      );
    case 4:
      return (
        <SummaryStep
          onBack={lifecycle.handleBack}
          onGenerate={lifecycle.handleGenerate}
          canProceed={lifecycle.canProceed(5)}
          isGenerating={lifecycle.isGenerating}
          onViewModeChange={onViewModeChange}
          currentStep={5}
          totalSteps={totalSteps}
          title={title}
          description={description}
        />
      );
    default:
      return null;
  }
}
