"use client";

import { useCallback, useRef } from "react";
import { useRouter } from "next/navigation";
import { FormProvider } from "react-hook-form";

import { ResizableLayout } from "./ResizableLayout";
import { GovernancePanelWrapper } from "../governance-assistant/GovernancePanelWrapper";
import { WizardStepRouter } from "../project-wizard/WizardStepRouter";
import { wizardSteps } from "../project-wizard/config";

import { useWizardForm } from "./hooks/useWizardForm";
import { useEditorSession } from "./hooks/useEditorSession";
import { useWorkspaceShellUi } from "./hooks/useWorkspaceShellUi";
import { useProjectLifecycle } from "./hooks/useProjectLifecycle";
import { ExportProvider } from "@/contexts/ExportContext";

import { Header } from "./Header";
import { ArchitecturePreviewPane } from "./ArchitecturePreviewPane";
import { NewProjectConfirmDialog } from "./NewProjectConfirmDialog";

import type { ViewMode } from "@/types/view-mode";

export interface ProjectWorkspaceProps {
  currentStepIndex: number;
  viewMode: ViewMode;
  onViewModeChange: (mode: ViewMode) => void;
  onCloseMiddlePanel: () => void;
  onCloseRightPanel: () => void;
  onGoToStep: (index: number) => void;
  onNavigateToProjects?: () => void;
  children?: React.ReactNode;
}

export function ProjectWorkspace({
  currentStepIndex,
  viewMode,
  onViewModeChange,
  onCloseMiddlePanel,
  onCloseRightPanel,
  onGoToStep,
  onNavigateToProjects,
  children,
}: ProjectWorkspaceProps) {
  const router = useRouter();
  const totalSteps = wizardSteps.length;

  const { form, wizardData, canProceed, contentHash } = useWizardForm();
  const ui = useWorkspaceShellUi({ currentStepIndex, viewMode });
  const editor = useEditorSession();
  const lifecycle = useProjectLifecycle({
    form,
    contentHash,
    ui,
    uiState: ui.state,
    editor,
    totalSteps,
    onGoToStep,
  });

  const isEditing = ui.state.kind === "edit";

  const pendingRoute = useRef<string | null>(null);

  const navigateWithConfirm = useCallback(
    (route: string) => {
      if (isEditing) {
        pendingRoute.current = route;
        ui.openDialog({ kind: "new-project" });
      } else {
        router.push(route);
      }
    },
    [isEditing, ui, router],
  );

  return (
    <ExportProvider>
      <div className="flex flex-col h-screen w-full overflow-hidden bg-background text-foreground">
        <Header
          onLoadManifest={() => navigateWithConfirm("/projects/new/import")}
          isEditing={isEditing}
          onNewProject={() => navigateWithConfirm("/projects/new")}
          onOpenWelcomeManifest={() => navigateWithConfirm("/projects/new/ai")}
          onNavigateToProjects={onNavigateToProjects}
        />

        <main className="flex-1 flex flex-col overflow-hidden">
          <ResizableLayout
            leftTitle="HexaGen Project Wizard"
            rightTitle="AI Governance"
            onRightPanelClose={onCloseRightPanel}
            onLeftPanelClose={onCloseMiddlePanel}
            left={
              <FormProvider {...form}>
                <WizardStepRouter
                  currentStepIndex={currentStepIndex}
                  totalSteps={totalSteps}
                  canProceed={canProceed(currentStepIndex)}
                  isGenerating={lifecycle.isGenerating}
                  activeContextId={ui.activeContextId ?? ""}
                  activeMappingId={ui.activeMappingId ?? ""}
                  autoGeneratedSteps={lifecycle.autoGeneratedSteps}
                  onContextSelect={ui.setContextId}
                  onMappingSelect={ui.setMappingId}
                  onNext={lifecycle.handleNext}
                  onBack={lifecycle.handleBack}
                  onGenerate={lifecycle.handleGenerate}
                  onViewModeChange={onViewModeChange}
                />
              </FormProvider>
            }
            middle={
              <ArchitecturePreviewPane
                wizardData={wizardData}
                viewMode={viewMode}
                selectedFileId={editor.selectedFileId}
                editedFiles={editor.editedFiles}
                onViewModeChange={onViewModeChange}
                onFileSelect={editor.selectFile}
                onFileContentChange={editor.updateFile}
                onFileSave={editor.markFileSaved}
              />
            }
            right={
              <GovernancePanelWrapper
                wizardData={wizardData}
                currentStepIndex={currentStepIndex}
              />
            }
          />
        </main>

        <NewProjectConfirmDialog
          open={ui.dialog.kind === "new-project"}
          onClose={lifecycle.handleCancelNewProject}
          loadedProject={lifecycle.loadedProject}
          onSaveAndNew={async () => {
            const route = pendingRoute.current;
            try {
              await lifecycle.handleSaveAndNew();
            } finally {
              pendingRoute.current = null;
            }
            if (route) router.push(route);
          }}
          onDiscardAndNew={async () => {
            const route = pendingRoute.current;
            try {
              await lifecycle.handleDiscardAndNew();
            } finally {
              pendingRoute.current = null;
            }
            if (route) router.push(route);
          }}
          onCancel={lifecycle.handleCancelNewProject}
        />
      </div>
      {children}
    </ExportProvider>
  );
}
