"use client";

import { useRouter } from "next/navigation";
import { FormProvider } from "react-hook-form";

import { ResizableLayout } from "./ResizableLayout";
import { GovernancePanelWrapper } from "../governance-assistant/GovernancePanelWrapper";
import { WizardStepRouter } from "../project-wizard/WizardStepRouter";
import { SavedProjectsList } from "../project-wizard/SavedProjectsList";
import { wizardSteps } from "../project-wizard/config";

import { useWizardForm } from "./hooks/useWizardForm";
import { useEditorSession } from "./hooks/useEditorSession";
import { useWorkspaceShellUi } from "./hooks/useWorkspaceShellUi";
import { useProjectLifecycle } from "./hooks/useProjectLifecycle";
import { ExportProvider } from "@/contexts/ExportContext";

import { Header } from "./Header";
import { ArchitecturePreviewPane } from "./ArchitecturePreviewPane";
import { NewProjectConfirmDialog } from "./NewProjectConfirmDialog";

import type { ViewMode } from "@/types/view-mode";

export interface ProjectWorkspaceProps {
  currentStepIndex: number;
  viewMode: ViewMode;
  middlePanel?: string;
  rightPanel?: string;
  onViewModeChange: (mode: ViewMode) => void;
  onCloseMiddlePanel: () => void;
  onCloseRightPanel: () => void;
  onGoToStep: (index: number) => void;
  onNavigateToProjects?: () => void;
  children?: React.ReactNode;
}

export function ProjectWorkspace({
  currentStepIndex,
  viewMode,
  onViewModeChange,
  onCloseMiddlePanel,
  onCloseRightPanel,
  onGoToStep,
  onNavigateToProjects,
  children,
}: ProjectWorkspaceProps) {
  const router = useRouter();
  const totalSteps = wizardSteps.length;

  const { form, wizardData, canProceed } = useWizardForm();
  const ui = useWorkspaceShellUi({ currentStepIndex, viewMode });
  const editor = useEditorSession();
  const lifecycle = useProjectLifecycle({
    form,
    ui,
    uiState: ui.state,
    editor,
    totalSteps,
    onGoToStep,
  });

  const isEditing = ui.state.kind === "edit";
  const showSavedProjects = ui.dialog.kind === "saved-projects";
  const loadedProjectId = ui.state.kind === "edit" ? ui.state.projectId : null;

  return (
    <ExportProvider>
      <div className="flex flex-col h-screen w-full overflow-hidden bg-background text-foreground">
        <Header
          onLoadManifest={() => router.push("/projects/new/import")}
          isEditing={isEditing}
          onNewProject={() => router.push("/projects/new")}
          onOpenWelcomeManifest={() => router.push("/projects/new/ai")}
          onLoadSavedProject={(project) =>
            lifecycle.handleLoadProject(project.id)
          }
          onNavigateToProjects={onNavigateToProjects}
        />

        <main className="flex-1 flex flex-col overflow-hidden">
          <FormProvider {...form}>
            <ResizableLayout
              leftTitle="HexaGen Project Wizard"
              rightTitle="AI Governance"
              onRightPanelClose={onCloseRightPanel}
              onLeftPanelClose={onCloseMiddlePanel}
              left={
                showSavedProjects ? (
                  <SavedProjectsList
                    projects={lifecycle.projects}
                    onLoad={lifecycle.handleLoadProject}
                    onDelete={lifecycle.deleteProject}
                    onRename={lifecycle.renameProject}
                    onBackToWizard={ui.closeDialog}
                    loadedProjectId={loadedProjectId}
                  />
                ) : (
                  <WizardStepRouter
                    currentStepIndex={currentStepIndex}
                    totalSteps={totalSteps}
                    canProceed={canProceed(currentStepIndex)}
                    isGenerating={lifecycle.isGenerating}
                    activeContextId={ui.activeContextId ?? ""}
                    activeMappingId={ui.activeMappingId ?? ""}
                    autoGeneratedSteps={lifecycle.autoGeneratedSteps}
                    onContextSelect={ui.setContextId}
                    onMappingSelect={ui.setMappingId}
                    onNext={lifecycle.handleNext}
                    onBack={lifecycle.handleBack}
                    onShowSavedProjects={() =>
                      ui.openDialog({ kind: "saved-projects" })
                    }
                    onGenerate={lifecycle.handleGenerate}
                    onViewModeChange={onViewModeChange}
                  />
                )
              }
              middle={
                <ArchitecturePreviewPane
                  wizardData={wizardData}
                  viewMode={viewMode}
                  selectedFileId={editor.selectedFileId}
                  editedFiles={editor.editedFiles}
                  onViewModeChange={onViewModeChange}
                  onFileSelect={editor.selectFile}
                  onFileContentChange={editor.updateFile}
                  onFileSave={editor.markFileSaved}
                />
              }
              right={
                <GovernancePanelWrapper
                  wizardData={wizardData}
                  currentStepIndex={currentStepIndex}
                />
              }
            />
          </FormProvider>
        </main>

        <NewProjectConfirmDialog
          open={ui.dialog.kind === "new-project"}
          onClose={lifecycle.handleCancelNewProject}
          loadedProject={lifecycle.loadedProject}
          onSaveAndNew={lifecycle.handleSaveAndNew}
          onDiscardAndNew={lifecycle.handleDiscardAndNew}
          onCancel={lifecycle.handleCancelNewProject}
        />
      </div>
      {children}
    </ExportProvider>
  );
}
