"use client";

import { FormProvider } from "react-hook-form";

import { ResizableLayout } from "./ResizableLayout";
import { GovernancePanelWrapper } from "../governance-assistant/GovernancePanelWrapper";
import { WizardStepRouter } from "../project-wizard/WizardStepRouter";
import { SavedProjectsList } from "../project-wizard/SavedProjectsList";
import { wizardSteps } from "../project-wizard/config";

import { useWizardForm } from "./hooks/useWizardForm";
import { useEditorSession } from "./hooks/useEditorSession";
import { useWorkspaceShellUi } from "./hooks/useWorkspaceShellUi";
import { useProjectLifecycle } from "./hooks/useProjectLifecycle";
import { ExportProvider } from "@/contexts/ExportContext";

import { Header } from "./Header";
import { ArchitecturePreviewPane } from "./ArchitecturePreviewPane";
import { LoadManifestDialog } from "./LoadManifestDialog";
import { ResumeDraftDialog } from "./ResumeDraftDialog";
import { NewProjectConfirmDialog } from "./NewProjectConfirmDialog";
import { WelcomeManifestDialog } from "./WelcomeManifestDialog";

/**
 * Root layout for the project workspace. Pure composition — no state,
 * no handlers, no effects. All concerns delegated to domain hooks:
 *
 * - useWizardForm       — form state + derived wizard data
 * - useWorkspaceShellUi — dialogs, view mode, step index, selection IDs
 * - useEditorSession    — editor workspace + active workspace
 * - useProjectLifecycle — orchestrated handlers composing the above
 */
export function ProjectWorkspace() {
  const totalSteps = wizardSteps.length;

  const { form, wizardData, canProceed } = useWizardForm();
  const ui = useWorkspaceShellUi();
  const editor = useEditorSession();
  const lifecycle = useProjectLifecycle({
    form,
    ui,
    uiState: ui.state,
    editor,
    totalSteps,
  });

  const isEditing = ui.state.kind === "edit";
  const showSavedProjects = ui.dialog.kind === "saved-projects";
  const loadedProjectId = ui.state.kind === "edit" ? ui.state.projectId : null;

  return (
    <ExportProvider>
      <div className="flex flex-col h-screen w-full overflow-hidden bg-background text-foreground">
        <Header
          onLoadManifest={() => ui.openDialog({ kind: "load-manifest" })}
          isEditing={isEditing}
          onNewProject={() => ui.openDialog({ kind: "new-project" })}
          onOpenWelcomeManifest={() => ui.openDialog({ kind: "welcome-manifest" })}
          onLoadSavedProject={(project) =>
            lifecycle.handleLoadProject(project.id)
          }
        />

        <main className="flex-1 flex flex-col overflow-hidden">
          <FormProvider {...form}>
            <ResizableLayout
              leftTitle="HexaGen Project Wizard"
              rightTitle="AI Governance"
              left={
                showSavedProjects ? (
                  <SavedProjectsList
                    projects={lifecycle.projects}
                    onLoad={lifecycle.handleLoadProject}
                    onDelete={lifecycle.deleteProject}
                    onRename={lifecycle.renameProject}
                    onBackToWizard={ui.closeDialog}
                    draft={lifecycle.draft}
                    onResumeDraft={lifecycle.handleResumeDraft}
                    onDiscardDraft={lifecycle.handleDiscardDraft}
                    loadedProjectId={loadedProjectId}
                  />
                ) : (
                    <WizardStepRouter
                      currentStepIndex={ui.currentStepIndex}
                      totalSteps={totalSteps}
                      canProceed={canProceed(ui.currentStepIndex)}
                      isGenerating={lifecycle.isGenerating}
                      activeContextId={ui.activeContextId ?? ""}
                      activeMappingId={ui.activeMappingId ?? ""}
                      autoGeneratedSteps={lifecycle.autoGeneratedSteps}
                      onContextSelect={ui.setContextId}
                      onMappingSelect={ui.setMappingId}
                      onNext={lifecycle.handleNext}
                      onBack={lifecycle.handleBack}
                      onShowSavedProjects={() =>
                        ui.openDialog({ kind: "saved-projects" })
                      }
                      onGenerate={lifecycle.handleGenerate}
                      onViewModeChange={ui.setViewMode}
                    />
                )
              }
              middle={
                <ArchitecturePreviewPane
                  wizardData={wizardData}
                  viewMode={ui.viewMode}
                  selectedFileId={editor.selectedFileId}
                  editedFiles={editor.editedFiles}
                  onViewModeChange={ui.setViewMode}
                  onFileSelect={editor.selectFile}
                  onFileContentChange={editor.updateFile}
                  onFileSave={editor.markFileSaved}
                />
              }
              right={
                <GovernancePanelWrapper
                  wizardData={wizardData}
                  currentStepIndex={ui.currentStepIndex}
                />
              }
            />
          </FormProvider>
        </main>

        <LoadManifestDialog
          open={ui.dialog.kind === "load-manifest"}
          onClose={ui.closeDialog}
          onFileLoaded={lifecycle.handleManifestLoaded}
        />

        <ResumeDraftDialog
          open={ui.dialog.kind === "resume-draft"}
          onClose={ui.closeDialog}
          draft={lifecycle.draft}
          totalSteps={totalSteps}
          onResume={lifecycle.handleResumeDraft}
          onDiscard={lifecycle.handleDiscardDraft}
        />

        <NewProjectConfirmDialog
          open={ui.dialog.kind === "new-project"}
          onClose={lifecycle.handleCancelNewProject}
          loadedProject={lifecycle.loadedProject}
          onSaveAndNew={lifecycle.handleSaveAndNew}
          onDiscardAndNew={lifecycle.handleDiscardAndNew}
          onCancel={lifecycle.handleCancelNewProject}
        />

        <WelcomeManifestDialog
          open={ui.dialog.kind === "welcome-manifest"}
          onClose={ui.closeDialog}
          onUseManifest={lifecycle.handleWelcomeManifestGenerated}
        />
      </div>
    </ExportProvider>
  );
}
