// @generated by @hexagen/sync

// Domain exports
export type { Identifier } from "./domain/identifier.js";
export { CustomError } from "./domain/custom-error.js";
export { LogLevel } from "./domain/log-level.js";
export type { LogContext } from "./domain/log-context.js";
export type { LoggerConfig } from "./domain/logger-config.js";
export type { LoggerPort } from "./domain/logger-port.js";
export { MonacoSession } from "./domain/monaco-session.js";
export type { SessionMetadata } from "./domain/session-metadata.js";
export type { PersistenceError } from "./domain/persistence-error.js";
export type { SavedProject } from "./domain/saved-project.js";
export type { GenerationResult } from "./domain/types/generation-result.js";
// NOTE: ProjectSpecification moved to @hexagen/project-configuration (canonical: ProjectSpec)
// See: Architectural Remediation Report Phase 1, Item 1.4
export type {
  PersistedEditorWorkspace,
  PersistedEditorWorkspaceFile,
} from "./domain/persisted-editor-workspace.js";
export type {
  PersistedCanvasLayout,
  NodePosition,
} from "./domain/persisted-canvas-layout.js";
export type {
  FileTreeNode,
  FileSystemNodeType,
} from "./domain/file-tree-node.js";

// Application exports
export type { MonacoPersistencePort } from "./application/ports/monaco-persistence.port.js";
export type { EditorWorkspacePersistencePort } from "./application/ports/editor-workspace-persistence.port.js";
export type { CanvasLayoutPersistencePort } from "./application/ports/canvas-layout-persistence.port.js";
export type {
  WizardPersistencePort,
  WizardDraft,
} from "./application/ports/wizard-persistence.port.js";
export type { SavedProjectsPersistencePort } from "./application/ports/saved-projects-persistence.port.js";
export type { GenerationResultPersistencePort } from "./application/ports/generation-result-persistence.port.js";

// Canvas / wizard exports
// NOTE: Wizard domain types are now owned by @hexagen/project-configuration
// See: Architectural Remediation Report (2026-04-25), Phase 1
// These types should be imported from @hexagen/project-configuration instead
// NOTE: deriveActiveContext and ContextUpdateCallback were dead code (never used) and have been removed

// Error/Result exports
export type { Result } from "./errors/result.js";
export { ok, err } from "./errors/result-helpers.js";
export { BaseError } from "./errors/base.error.js";

// Infrastructure exports
export {
  MODEL_PREFERENCE_KEYS,
  getAutoLoadEnabled,
  getHasEnabledLocalModels,
  getHasEnabledLocalModelsFlag,
  removeEnginePreferenceKeys,
  saveEngineInitSuccess,
  backfillHasEnabledForMigration,
  resetLocalAIConfig,
  type ModelPreferencesStorage,
} from "./infrastructure/index.js";

// Types
export * from "./types/index.js";
