import { DownloadProjectPort } from '../../domain/ports/out/download-project.port';
import type { Project } from '../../domain/project.entity';

/**
 * Adapter for project preview and download operations using WebContainer.
 *
 * Current phase: Minimal implementation that prepares project structure for download.
 * Future extensions:
 *   - Real @webcontainer/api mount & boot
 *   - Live preview iframe injection
 *   - Zip generation fallback when WebContainer unavailable
 */
export class WebContainerPreviewAdapter implements DownloadProjectPort {
  /**
   * Initiate project preview/download flow.
   *
   * @param project - The Project entity containing full spec & generated structure
   * @returns Promise resolving to download metadata (e.g. blob URL or success flag)
   * @throws DownloadError on critical failure
   */
  async downloadProject(
    project: Project
  ): Promise<{ success: boolean; downloadUrl?: string; message: string }> {
    try {
      // Phase 1: Prepare minimal zip-like structure representation
      // (In real WebContainer flow this would mount files into in-memory FS)
      const projectFiles = this.prepareProjectFiles(project);

      // Placeholder: Simulate download preparation
      // Future: Use JSZip or WebContainer fs API to create downloadable blob
      const blob = new Blob([JSON.stringify(projectFiles, null, 2)], {
        type: 'application/json',
      });
      const downloadUrl = URL.createObjectURL(blob);

      return {
        success: true,
        downloadUrl,
        message: `Project "${project.spec.name}" prepared for preview/download (${projectFiles.fileCount} files)`,
      };
    } catch (err) {
      console.warn('WebContainer preview/download failed', err);
      throw new Error(
        `Failed to prepare project download: ${err instanceof Error ? err.message : 'Unknown error'}`
      );
    }
  }

  /**
   * Internal helper: Flatten project entity into a simple file map for preview/download.
   * This is temporary — real adapter will use proper FS tree.
   */
  private prepareProjectFiles(project: Project): {
    fileCount: number;
    files: Record<string, string>;
  } {
    const files: Record<string, string> = {};

    // Example: Root files
    if (project.rootFiles?.['package.json']) {
      files['package.json'] = project.rootFiles['package.json'];
    }

    // Traverse bounded contexts / layers (simplified projection)
    project.boundedContexts.forEach((ctx) => {
      const ctxPath = `packages/${ctx.name}/src/`;
      // Add placeholder for main barrels / entities
      files[`${ctxPath}index.ts`] = '// Barrel file generated by HexaGen\n';
      // ... more files would be added from generator results
    });

    return {
      fileCount: Object.keys(files).length,
      files,
    };
  }

  /**
   * Cleanup any temporary resources (e.g. revoke object URLs).
   * Called by use-case on completion or error.
   */
  async cleanup(): Promise<void> {
    // Currently no-op; future: revoke Blob URLs, unmount WebContainer instance
  }
}
