import type { Result } from "@hexagen/shared";
import type {
  DownloadError,
  DownloadProjectPort,
} from "../../application/ports/out/download-project.port";
import type { Project } from "../../domain/project.entity";

export class WebContainerPreviewAdapter implements DownloadProjectPort {
  async downloadProject(
    project: Project,
  ): Promise<Result<{ downloadUrl?: string }, DownloadError>> {
    try {
      const projectFiles = this.prepareProjectFiles(project);
      const blob = new Blob([JSON.stringify(projectFiles, null, 2)], {
        type: "application/json",
      });
      const downloadUrl = URL.createObjectURL(blob);
      return { success: true, value: { downloadUrl } };
    } catch (err) {
      return {
        success: false,
        error: {
          code: "DOWNLOAD_FAILED",
          message: `Failed to prepare project download`,
          cause: err,
        },
      };
    }
  }

  async cleanup(): Promise<Result<void, DownloadError>> {
    return { success: true, value: undefined };
  }

  private prepareProjectFiles(project: Project): {
    fileCount: number;
    files: Record<string, string>;
  } {
    const files: Record<string, string> = {};
    if (project.rootFiles?.["package.json"]) {
      files["package.json"] = project.rootFiles["package.json"];
    }
    project.boundedContexts.forEach((ctx) => {
      const ctxPath = `packages/${ctx.name}/src/`;
      files[`${ctxPath}index.ts`] = "// Barrel file generated by HexaGen\n";
    });
    return { fileCount: Object.keys(files).length, files };
  }
}
