"use client";

import { useState, useEffect } from "react";
import { useFormContext, useWatch } from "react-hook-form";
import type { BoundedContext, ProjectConfig } from "@hexagen/project-configuration";

import { StepHeader } from "./StepHeader";
import { WizardFooter } from "../WizardFooter";
import {
  ContextList,
  ContextForm,
  createEmptyContext,
} from "./bounded-context-step";

interface BoundedContextStepProps {
  onNext: () => void;
  onBack: () => void;
  canProceed: boolean;
  activeContextId?: string;
  onContextSelect?: (id: string) => void;
  currentStep?: number;
  totalSteps?: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
}

export function BoundedContextStep({
  onNext,
  onBack,
  canProceed,
  activeContextId,
  onContextSelect,
  currentStep = 2,
  totalSteps = 6,
  title,
  description,
  readOnly,
}: BoundedContextStepProps) {
  const { control, getValues, setValue } = useFormContext<ProjectConfig>();

  const boundedContexts = useWatch({ control, name: "boundedContexts" }) || [];

  const [viewMode, setViewMode] = useState<"menu" | "form">("menu");
  const [localActiveId, setLocalActiveId] = useState<string>(
    activeContextId || "",
  );
  const [deleteId, setDeleteId] = useState<string | null>(null);

  useEffect(() => {
    if (activeContextId && activeContextId !== localActiveId) {
      setLocalActiveId(activeContextId);
    }
  }, [activeContextId]);

  const activeIndex = boundedContexts.findIndex(
    (c: BoundedContext) => c.id === localActiveId,
  );
  const activeContext: BoundedContext | undefined =
    activeIndex >= 0 ? boundedContexts[activeIndex] : undefined;

  useEffect(() => {
    if (viewMode === "form" && !activeContext) {
      setViewMode("menu");
    }
  }, [activeContext, viewMode]);

  const isNextDisabled =
    !canProceed || boundedContexts.some((c: BoundedContext) => !c.name?.trim());

  const handleSelectContext = (id: string) => {
    if (!id) return;
    setLocalActiveId(id);
    setViewMode("form");
    onContextSelect?.(id);
  };

  const handleAddContext = () => {
    const current = getValues("boundedContexts") || [];
    const next = createEmptyContext();
    setValue("boundedContexts", [...current, next], {
      shouldDirty: true,
      shouldValidate: true,
    });
    setLocalActiveId(next.id);
    setViewMode("form");
    onContextSelect?.(next.id);
  };

  const handleConfirmDelete = (contextId: string) => {
    const current = getValues("boundedContexts") || [];
    const index = current.findIndex((c: BoundedContext) => c.id === contextId);
    if (index >= 0) {
      const updated = [...current];
      updated.splice(index, 1);
      setValue("boundedContexts", updated, {
        shouldDirty: true,
        shouldValidate: true,
      });
    }
    setDeleteId(null);
    if (localActiveId === contextId) {
      setLocalActiveId("");
      setViewMode("menu");
      onContextSelect?.("");
    }
  };

  return (
    <div className="flex flex-col h-full bg-card">
      <StepHeader
        currentStep={currentStep}
        totalSteps={totalSteps}
        title={title || "Bounded Contexts"}
        description={description || "Add and configure bounded contexts."}
        autoGenerated={readOnly}
      />

      <div className="flex-1 min-h-0 overflow-hidden flex flex-col">
        {viewMode === "menu" || !activeContext ? (
          <ContextList
            contexts={boundedContexts}
            activeContextId={localActiveId}
            confirmDeleteId={deleteId}
            onSelectContext={handleSelectContext}
            onAddContext={handleAddContext}
            onRequestDelete={setDeleteId}
            onConfirmDelete={handleConfirmDelete}
            onCancelDelete={() => setDeleteId(null)}
            readOnly={readOnly}
          />
        ) : (
          <ContextForm
            // key={activeContext.id} forces a full remount on context switch,
            // preventing RHF's uncontrolled DOM nodes from retaining stale
            // values across fieldPrefix changes.
            //
            // CRITICAL: Do NOT use activeIndex as the key. If a context is
            // deleted, array indices shift, causing false cache busts or
            // missed busts — leaking ambient state between contexts.
            key={activeContext.id}
            fieldPrefix={`boundedContexts.${activeIndex}`}
            onBack={() => setViewMode("menu")}
            readOnly={readOnly}
          />
        )}
      </div>

      <WizardFooter
        onBack={onBack}
        onNext={onNext}
        canProceed={!isNextDisabled}
        currentStep={currentStep}
        totalSteps={totalSteps}
      />
    </div>
  );
}
