"use client";

import { useFormContext, useFieldArray, useWatch } from "react-hook-form";
import type {
  ProjectConfig,
  BoundedContext,
} from "@hexagen/project-configuration";

import { StepHeader } from "./StepHeader";
import { WizardFooter } from "../WizardFooter";
import { useMenuFormView } from "../hooks/useMenuFormView";
import {
  ContextList,
  ContextForm,
  createEmptyContext,
} from "./bounded-context-step";

interface BoundedContextStepProps {
  onNext: () => void;
  onBack: () => void;
  canProceed: boolean;
  activeContextId?: string;
  onContextSelect?: (id: string) => void;
  currentStep?: number;
  totalSteps?: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
}

export function BoundedContextStep({
  onNext,
  onBack,
  canProceed,
  activeContextId,
  onContextSelect,
  currentStep = 2,
  totalSteps = 6,
  title,
  description,
  readOnly,
}: BoundedContextStepProps) {
  const { control } = useFormContext<ProjectConfig>();

  const { fields, append, update, remove } = useFieldArray({
    control,
    name: "boundedContexts",
    keyName: "_rfId",
  });

  const watchedContexts = useWatch({ control, name: "boundedContexts" }) || [];

  const boundedContexts = fields.map((field, index) => ({
    ...field,
    ...(watchedContexts[index] || {}),
  }));

  const {
    view,
    confirmDeleteId,
    openMenu,
    openForm,
    requestDelete,
    cancelDelete,
  } = useMenuFormView<string>();

  const activeIndex = boundedContexts.findIndex(
    (c) => c.id === activeContextId,
  );
  const activeContext =
    activeIndex >= 0 ? boundedContexts[activeIndex] : undefined;

  const isNextDisabled =
    !canProceed || boundedContexts.some((c) => !c.name?.trim());

  const handleSelectContext = (id: string) => {
    onContextSelect?.(id);
    openForm();
  };

  const handleAddContext = () => {
    const next = createEmptyContext();
    append(next);
    onContextSelect?.(next.id);
    openForm();
  };

  const handleUpdateContext = (
    updater: (ctx: BoundedContext) => BoundedContext,
  ) => {
    if (activeIndex < 0 || !activeContext) return;
    update(activeIndex, updater(activeContext));
  };

  const handleConfirmDelete = (contextId: string) => {
    const indexToDelete = boundedContexts.findIndex(
      (c) => c.id === contextId,
    );
    if (indexToDelete < 0) {
      cancelDelete();
      return;
    }
    remove(indexToDelete);

    if (activeContextId === contextId) {
      const remaining = boundedContexts.filter((c) => c.id !== contextId);
      if (remaining.length > 0) {
        const newActiveIndex = Math.min(indexToDelete, remaining.length - 1);
        onContextSelect?.(remaining[newActiveIndex].id);
        openMenu();
      } else {
        onContextSelect?.("");
      }
    }
    cancelDelete();
  };

  return (
    <div className="flex flex-col h-full bg-card">
      <StepHeader
        currentStep={currentStep}
        totalSteps={totalSteps}
        title={title || "Bounded Contexts"}
        description={description || "Add and configure bounded contexts."}
        autoGenerated={readOnly}
      />

      <div className="flex-1 min-h-0 overflow-hidden flex flex-col">
        {view === "menu" || !activeContext ? (
          <ContextList
            contexts={boundedContexts}
            activeContextId={activeContextId}
            confirmDeleteId={confirmDeleteId}
            onSelectContext={handleSelectContext}
            onAddContext={handleAddContext}
            onRequestDelete={requestDelete}
            onConfirmDelete={handleConfirmDelete}
            onCancelDelete={cancelDelete}
            readOnly={readOnly}
          />
        ) : (
          <ContextForm
            key={activeContext.id}
            context={activeContext}
            fieldPrefix={`boundedContexts.${activeIndex}`}
            onBack={openMenu}
            onUpdate={handleUpdateContext}
            readOnly={readOnly}
          />
        )}
      </div>

      <WizardFooter
        onBack={onBack}
        onNext={onNext}
        canProceed={!isNextDisabled}
        currentStep={currentStep}
        totalSteps={totalSteps}
      />
    </div>
  );
}
