"use client";

import { useFormContext } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { StepHeader } from "./StepHeader";
import { WizardFooter } from "../WizardFooter";
import {
  ContextPortCard,
  PortsEmptyState,
  toggleContextPort,
} from "./port-configuration-step";

interface PortConfigurationStepProps {
  onNext: () => void;
  onBack: () => void;
  canProceed: boolean;
  currentStep?: number;
  totalSteps?: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
}

/**
 * Wizard step for wiring up hexagonal ports per bounded context.
 * Each context gets a 2-column card: west (inbound/driving ports)
 * and east (outbound/driven ports). Sub-components live under
 * ./port-configuration-step/.
 */
export function PortConfigurationStep({
  onNext,
  onBack,
  canProceed,
  currentStep = 4,
  totalSteps = 6,
  title,
  description,
  readOnly,
}: PortConfigurationStepProps) {
  const { watch, setValue } = useFormContext<ProjectConfig>();
  const boundedContexts = watch("boundedContexts") || [];

  const handleTogglePort = (
    contextIndex: number,
    direction: "inbound" | "outbound",
    port: string,
  ) => {
    const next = toggleContextPort(
      boundedContexts,
      contextIndex,
      direction,
      // Cast here is safe: `port` is supplied by PortColumn which was
      // typed to the specific union per direction. toggleContextPort
      // narrows internally.
      port as never,
    );
    setValue("boundedContexts", next);
  };

  return (
    <div className="flex flex-col h-full bg-card">
      <StepHeader
        currentStep={currentStep}
        totalSteps={totalSteps}
        title={title || "Ports Configuration"}
        description={description || "Configure ports for each context."}
        autoGenerated={readOnly}
      />

      {boundedContexts.length === 0 ? (
        <PortsEmptyState />
      ) : (
        <div className="flex-1 min-h-0 overflow-y-auto px-2 pb-6">
          <fieldset disabled={readOnly} className="space-y-6">
            {boundedContexts.map((context, index) => (
              <ContextPortCard
                key={context.id}
                context={context}
                contextIndex={index}
                onToggleInbound={(port) =>
                  handleTogglePort(index, "inbound", port)
                }
                onToggleOutbound={(port) =>
                  handleTogglePort(index, "outbound", port)
                }
              />
            ))}
          </fieldset>
        </div>
      )}

      <WizardFooter
        onBack={onBack}
        onNext={onNext}
        canProceed={canProceed}
        currentStep={currentStep}
        totalSteps={totalSteps}
      />
    </div>
  );
}
