"use client";

import { useFormContext } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { StepHeader } from "./StepHeader";
import { WizardFooter } from "../WizardFooter";
import {
  ContextPortCard,
  PortsEmptyState,
  toggleContextPort,
} from "./port-configuration-step";
import { listImportedManifestPorts } from "../utils/imported-manifest-ports";

interface PortConfigurationStepProps {
  onNext: () => void;
  onBack: () => void;
  canProceed: boolean;
  currentStep?: number;
  totalSteps?: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
  /**
   * The saved record's manifest for IMPORTED projects (import round-trip
   * integrity, Item 1.4). When `manifestSource === "imported"` the checkbox
   * catalog is replaced by a read-only banner listing the manifest's real
   * named ports — the checkboxes only cover the 8 wizard catalog types and
   * would misrepresent (and on save, degrade) the imported architecture.
   */
  importedManifestYaml?: string | null;
}

/**
 * Wizard step for wiring up hexagonal ports per bounded context.
 * Each context gets a 2-column card: west (inbound/driving ports)
 * and east (outbound/driven ports). Sub-components live under
 * ./port-configuration-step/.
 */
export function PortConfigurationStep({
  onNext,
  onBack,
  canProceed,
  currentStep = 4,
  totalSteps = 6,
  title,
  description,
  readOnly,
  importedManifestYaml,
}: PortConfigurationStepProps) {
  const { watch, setValue } = useFormContext<ProjectConfig>();
  const boundedContexts = watch("boundedContexts") || [];
  const isImported = watch("manifestSource") === "imported";

  const handleTogglePort = (
    contextIndex: number,
    direction: "inbound" | "outbound",
    port: string,
  ) => {
    const next = toggleContextPort(
      boundedContexts,
      contextIndex,
      direction,
      // Cast here is safe: `port` is supplied by PortColumn which was
      // typed to the specific union per direction. toggleContextPort
      // narrows internally.
      port as never,
    );
    setValue("boundedContexts", next);
  };

  if (isImported) {
    // Honest read-only view for manifest-first projects: the checkbox catalog
    // cannot represent (let alone edit) the imported manifest's named ports,
    // so we list them verbatim instead. The list is display-only — the saved
    // manifest stays the source of truth (autosave for imported projects
    // persists formState only and never rewrites manifestYaml).
    const importedPorts = listImportedManifestPorts(importedManifestYaml);
    return (
      <div className="flex flex-col h-full bg-card">
        <StepHeader
          currentStep={currentStep}
          totalSteps={totalSteps}
          title={title || "Ports Configuration"}
          description={description || "Configure ports for each context."}
        />

        <div className="flex-1 min-h-0 overflow-y-auto px-4 pb-6 space-y-4">
          <div
            role="status"
            className="rounded-md border border-border bg-muted/50 p-4 text-sm text-muted-foreground"
          >
            Ports are managed by the imported manifest and can&apos;t be edited
            here. The lists below show the manifest&apos;s real named ports;
            exports and generation use the manifest directly.
          </div>

          {importedPorts.map(({ context, inPorts, outPorts }) => (
            <div
              key={context}
              className="rounded-md border border-border p-4 space-y-2"
            >
              <h3 className="text-sm font-medium text-foreground">{context}</h3>
              <div className="text-sm text-muted-foreground">
                <span className="font-medium">Inbound:</span>{" "}
                {inPorts.length > 0 ? inPorts.join(", ") : "none"}
              </div>
              <div className="text-sm text-muted-foreground">
                <span className="font-medium">Outbound:</span>{" "}
                {outPorts.length > 0 ? outPorts.join(", ") : "none"}
              </div>
            </div>
          ))}
        </div>

        <WizardFooter
          onBack={onBack}
          onNext={onNext}
          canProceed={canProceed}
          currentStep={currentStep}
          totalSteps={totalSteps}
        />
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full bg-card">
      <StepHeader
        currentStep={currentStep}
        totalSteps={totalSteps}
        title={title || "Ports Configuration"}
        description={description || "Configure ports for each context."}
        autoGenerated={readOnly}
      />

      {boundedContexts.length === 0 ? (
        <PortsEmptyState />
      ) : (
        <div className="flex-1 min-h-0 overflow-y-auto px-2 pb-6">
          <fieldset disabled={readOnly} className="space-y-6">
            {boundedContexts.map((context, index) => (
              <ContextPortCard
                key={context.id}
                context={context}
                contextIndex={index}
                onToggleInbound={(port) =>
                  handleTogglePort(index, "inbound", port)
                }
                onToggleOutbound={(port) =>
                  handleTogglePort(index, "outbound", port)
                }
              />
            ))}
          </fieldset>
        </div>
      )}

      <WizardFooter
        onBack={onBack}
        onNext={onNext}
        canProceed={canProceed}
        currentStep={currentStep}
        totalSteps={totalSteps}
      />
    </div>
  );
}
