"use client";

import { useFormContext, useWatch } from "react-hook-form";
import type { ProjectConfig } from "@hexagen/project-configuration";

import { StepHeader } from "./StepHeader";
import { WizardFooter } from "../WizardFooter";
import {
  IdentityFields,
  TemplateSelector,
  PackageManagerSelect,
  NamingConventionsFieldset,
} from "@/workspace-governance-step";

interface WorkspaceGovernanceStepProps {
  onNext: () => void;
  canProceed: boolean;
  currentStep?: number;
  totalSteps?: number;
  title?: string;
  description?: string;
  readOnly?: boolean;
}

export function WorkspaceGovernanceStep({
  onNext,
  canProceed,
  currentStep = 1,
  totalSteps = 6,
  title,
  description,
  readOnly,
}: WorkspaceGovernanceStepProps) {
  const { control, setValue, getValues } = useFormContext<ProjectConfig>();

  const [workspaceName, namespacePrefix] = useWatch({
    control,
    name: ["governance.workspaceName", "governance.namespacePrefix"],
  });

  const handleNext = () => {
    const values = getValues();
    setValue(
      "governance.workspaceName",
      values.governance.workspaceName.trim(),
    );
    setValue(
      "governance.workspaceDescription",
      (values.governance.workspaceDescription ?? "").trim(),
    );
    setValue(
      "governance.namespacePrefix",
      values.governance.namespacePrefix.trim(),
    );
    onNext();
  };

  return (
    <div className="flex flex-col h-full bg-card">
      <StepHeader
        currentStep={currentStep}
        totalSteps={totalSteps}
        title={title || "Workspace Governance"}
        description={
          description ||
          "Define workspace settings and select an architectural template."
        }
        autoGenerated={readOnly}
      />

      <div className="flex-1 min-h-0 overflow-y-auto px-2 pb-2">
        <fieldset disabled={readOnly} className="space-y-6">
          <IdentityFields control={control} />
          <TemplateSelector control={control} />
          <PackageManagerSelect control={control} />
          <NamingConventionsFieldset control={control} />
        </fieldset>
      </div>

      <WizardFooter
        onNext={handleNext}
        canProceed={Boolean(
          canProceed && workspaceName?.trim() && namespacePrefix?.trim(),
        )}
        currentStep={currentStep}
        totalSteps={totalSteps}
        showBack={false}
      />
    </div>
  );
}
