// domain layer barrel — generated by sync.ts
// Minimum content to prevent TS2306 "not a module" error

export {};
// Re-exports will be added automatically when entities/use-cases/ports are declared
export { MonacoSession } from './model/monaco-session/monaco-session';
