import assert from "node:assert";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import yaml from "js-yaml";
import { generateArchitectureFiles } from "../../src/generators/architecture-files.js";
import type { Manifest } from "../../src/types/manifest.js";
import type { SyncConfig, LoggerPort } from "../../src/config.js";

/**
 * Tests for `packages/sync/src/generators/architecture-files.ts`
 * (sync-engine-unified-scaffolding Wave 2c).
 *
 * Coverage mirrors the file's public contract:
 *   - `.architecture/manifest.yaml` is ALWAYS protected
 *       · external mode + fresh target    → create via yaml.dump
 *       · external mode + file exists     → preserve verbatim
 *       · self-regen mode                 → never touched (no stat, no write)
 *   - invariants/layer-rules.yaml, invariants/linter-config.yaml, and
 *     generator.config.yaml are regenerated from:
 *       1. manifest.monorepo.archInvariants[<slot>].template (if present)
 *       2. built-in fallback (otherwise)
 *     with `{scope}`, `{template}`, `{workspaceTemplate}`, `{ownershipBlock}`
 *     interpolated per the flat variable map in `buildInterpolationVars`.
 *   - ownership block is derived from bounded_contexts[].layers ports/adapters,
 *     PascalCase'd, with 6-space indentation.
 *
 * Protection semantics (see fs-utils.ts `isProtectedRoot`): every path under
 * `.architecture/` is root-protected, so writes require `forceRoot: true`.
 * External-mode callers set `forceRoot: true` via the external sync-engine
 * adapter; self-regen runs without `forceRoot` by default.
 */

// -----------------------------------------------------------------------------
// Test helpers
// -----------------------------------------------------------------------------

/** No-op logger that satisfies LoggerPort without cluttering test output. */
const silentLogger: LoggerPort = {
  error: () => {},
  warn: () => {},
  info: () => {},
  debug: () => {},
  errorWithException: () => {},
};

/**
 * Capture-logger used for tests that assert on warn/debug output (e.g. the
 * missing-placeholder path in `interpolateWithLogging`).
 */
function createCaptureLogger(): {
  logger: LoggerPort;
  warnings: string[];
  debugs: string[];
  infos: string[];
} {
  const warnings: string[] = [];
  const debugs: string[] = [];
  const infos: string[] = [];
  return {
    warnings,
    debugs,
    infos,
    logger: {
      error: () => {},
      warn: (msg) => {
        warnings.push(msg);
      },
      info: (msg) => {
        infos.push(msg);
      },
      debug: (msg) => {
        debugs.push(msg);
      },
      errorWithException: () => {},
    },
  };
}

interface ConfigOverrides {
  mode?: "self-regen" | "external";
  forceRoot?: boolean;
  logger?: LoggerPort;
  dryRun?: boolean;
}

/**
 * Build a SyncConfig pointed at a temp workspace. Defaults mirror the
 * contract of each mode:
 *   - external mode → forceRoot: true (matches ExternalSyncEngineAdapter)
 *   - self-regen mode → forceRoot: false (default CLI behaviour)
 * Callers may override these explicitly.
 */
function makeConfig(
  workspaceRoot: string,
  manifest: Manifest,
  overrides: ConfigOverrides = {},
): SyncConfig {
  const mode = overrides.mode ?? "external";
  const defaultForceRoot = mode === "external";
  return {
    dryRun: overrides.dryRun ?? false,
    force: false,
    forceRoot: overrides.forceRoot ?? defaultForceRoot,
    allowDirty: false,
    strict: false,
    mode,
    logger: overrides.logger ?? silentLogger,
    manifest,
    workspaceRoot,
  };
}

async function withTempWorkspace(
  fn: (ctx: { workspaceRoot: string; archDir: string }) => Promise<void>,
) {
  const workspaceRoot = await fs.mkdtemp(
    path.join(os.tmpdir(), "hexagen-arch-files-test-"),
  );
  const archDir = path.join(workspaceRoot, ".architecture");
  try {
    await fn({ workspaceRoot, archDir });
  } finally {
    await fs.rm(workspaceRoot, { recursive: true, force: true });
  }
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function readText(p: string): Promise<string> {
  return fs.readFile(p, "utf8");
}

const GENERATED_MARKER = "// @generated by @hexagen/sync";

// -----------------------------------------------------------------------------
// Test cases
// -----------------------------------------------------------------------------

(async () => {
  console.log("Running architecture-files generator tests...\n");

  // ---------------------------------------------------------------------------
  // 1) Fresh external-mode target: creates all four arch files
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      system: "demo",
      scope: "demo",
      architecture: "modular-monolith",
      bounded_contexts: [{ name: "shared" }],
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    const result = await generateArchitectureFiles(config);

    const manifestPath = path.join(archDir, "manifest.yaml");
    const layerRulesPath = path.join(archDir, "invariants", "layer-rules.yaml");
    const linterPath = path.join(archDir, "invariants", "linter-config.yaml");
    const genConfigPath = path.join(archDir, "generator.config.yaml");

    assert.strictEqual(
      await pathExists(manifestPath),
      true,
      "external fresh target should materialise .architecture/manifest.yaml",
    );
    assert.strictEqual(
      await pathExists(layerRulesPath),
      true,
      "external fresh target should materialise invariants/layer-rules.yaml",
    );
    assert.strictEqual(
      await pathExists(linterPath),
      true,
      "external fresh target should materialise invariants/linter-config.yaml",
    );
    assert.strictEqual(
      await pathExists(genConfigPath),
      true,
      "external fresh target should materialise generator.config.yaml",
    );

    const createdSet = new Set(result.created);
    assert.ok(
      createdSet.has(manifestPath),
      "result.created should include the manifest path",
    );
    assert.ok(
      createdSet.has(layerRulesPath) &&
        createdSet.has(linterPath) &&
        createdSet.has(genConfigPath),
      "result.created should include all three invariant/config files",
    );
    assert.strictEqual(
      result.totalOps,
      4,
      "totalOps should equal 4 when all four files are freshly created",
    );

    console.log(
      "✅ external mode + fresh target → creates manifest, layer-rules, linter-config, generator.config",
    );
  });

  // ---------------------------------------------------------------------------
  // 2) External mode + manifest.yaml absent → writes via yaml.dump
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      system: "yaml-dump-target",
      scope: "yd",
      architecture: "modular-monolith",
      bounded_contexts: [{ name: "alpha" }],
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    await generateArchitectureFiles(config);

    const manifestPath = path.join(archDir, "manifest.yaml");
    const raw = await readText(manifestPath);
    const parsed = yaml.load(raw) as Manifest;

    assert.strictEqual(
      parsed.system,
      "yaml-dump-target",
      "dumped manifest must round-trip the `system` field",
    );
    assert.strictEqual(
      parsed.scope,
      "yd",
      "dumped manifest must round-trip the `scope` field",
    );
    assert.deepStrictEqual(
      parsed.bounded_contexts,
      [{ name: "alpha" }],
      "dumped manifest must round-trip the bounded_contexts array",
    );

    console.log(
      "✅ external mode + manifest absent → creates .architecture/manifest.yaml via yaml.dump",
    );
  });

  // ---------------------------------------------------------------------------
  // 3) External mode + manifest.yaml exists → NEVER overwrites
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    await fs.mkdir(archDir, { recursive: true });
    const manifestPath = path.join(archDir, "manifest.yaml");
    const sentinel =
      "# user-edited manifest — must be preserved verbatim\nsystem: user-owned\n";
    await fs.writeFile(manifestPath, sentinel, "utf8");

    const manifest: Manifest = {
      system: "engine-supplied",
      bounded_contexts: [{ name: "beta" }],
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    const result = await generateArchitectureFiles(config);

    const afterContent = await readText(manifestPath);
    assert.strictEqual(
      afterContent,
      sentinel,
      "external mode must NEVER overwrite an existing manifest.yaml (ALWAYS protected)",
    );
    assert.ok(
      result.skipped.includes(manifestPath),
      "manifest.yaml should appear in result.skipped when preserved",
    );
    assert.ok(
      !result.created.includes(manifestPath),
      "manifest.yaml must not appear in result.created when it already exists",
    );

    console.log(
      "✅ external mode + manifest exists → preserved verbatim (never overwrites)",
    );
  });

  // ---------------------------------------------------------------------------
  // 4) Self-regen mode → skips manifest.yaml entirely (no stat, no write)
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      system: "self-regen-demo",
      bounded_contexts: [{ name: "gamma" }],
    };
    // Self-regen mode with forceRoot so invariant files CAN write. If the
    // manifest-handling branch were ever reached, this flag would be enough to
    // allow a write — so the assertion below truly verifies the early-return.
    const config = makeConfig(workspaceRoot, manifest, {
      mode: "self-regen",
      forceRoot: true,
    });

    const result = await generateArchitectureFiles(config);

    const manifestPath = path.join(archDir, "manifest.yaml");
    assert.strictEqual(
      await pathExists(manifestPath),
      false,
      "self-regen mode must never create .architecture/manifest.yaml",
    );
    assert.ok(
      !result.created.includes(manifestPath) &&
        !result.skipped.includes(manifestPath) &&
        !result.updated.includes(manifestPath),
      "self-regen mode must not record manifest.yaml in any result bucket (early return)",
    );

    console.log(
      "✅ self-regen mode → skips manifest.yaml entirely (no stat, no write, no record)",
    );
  });

  // ---------------------------------------------------------------------------
  // 5) Self-regen + invariant file exists — with forceRoot, regenerates.
  //
  // Invariant files are root-protected (see fs-utils.isProtectedRoot). With
  // `forceRoot: true` the protection gate passes, and because the generator
  // sets `skipGeneratedCheck = true`, the presence/absence of the @generated
  // marker is irrelevant — the file is overwritten.
  //
  // This test uses a marker-bearing existing file to represent the "expected
  // regen" case the self-regen workflow targets.
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const invariantsDir = path.join(archDir, "invariants");
    await fs.mkdir(invariantsDir, { recursive: true });
    const layerRulesPath = path.join(invariantsDir, "layer-rules.yaml");
    const stale = `${GENERATED_MARKER}\n# stale generated content — should be replaced\n`;
    await fs.writeFile(layerRulesPath, stale, "utf8");

    const manifest: Manifest = {
      scope: "regen",
      architecture: "modular-monolith",
      bounded_contexts: [{ name: "shared" }],
    };
    const config = makeConfig(workspaceRoot, manifest, {
      mode: "self-regen",
      forceRoot: true,
    });

    const result = await generateArchitectureFiles(config);

    const after = await readText(layerRulesPath);
    assert.notStrictEqual(
      after,
      stale,
      "self-regen with forceRoot should overwrite stale @generated invariant file",
    );
    assert.ok(
      after.includes("@regen/shared"),
      "regenerated layer-rules.yaml should contain interpolated scope `@regen/shared`",
    );
    assert.ok(
      result.updated.includes(layerRulesPath),
      "layer-rules.yaml should appear in result.updated when regenerated",
    );

    console.log(
      "✅ self-regen + forceRoot + existing invariant file → regenerates",
    );
  });

  // ---------------------------------------------------------------------------
  // 6) Self-regen WITHOUT forceRoot + existing invariant file → preserved.
  //
  // The root-protection gate in `safeWriteFileAtomic` returns "protected"
  // before any write. This is the default self-regen behaviour: operator
  // customisations under .architecture/ are respected unless --force-root
  // is passed.
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const invariantsDir = path.join(archDir, "invariants");
    await fs.mkdir(invariantsDir, { recursive: true });
    const layerRulesPath = path.join(invariantsDir, "layer-rules.yaml");
    const custom =
      "# user customisation — no @generated marker\nlayers:\n  domain:\n    custom: true\n";
    await fs.writeFile(layerRulesPath, custom, "utf8");

    const manifest: Manifest = {
      scope: "regen2",
      bounded_contexts: [{ name: "shared" }],
    };
    // Self-regen, forceRoot: false (default CLI behaviour).
    const config = makeConfig(workspaceRoot, manifest, {
      mode: "self-regen",
      forceRoot: false,
    });

    const result = await generateArchitectureFiles(config);

    const after = await readText(layerRulesPath);
    assert.strictEqual(
      after,
      custom,
      "self-regen without forceRoot must preserve user-customised invariant file",
    );
    assert.ok(
      result.skipped.includes(layerRulesPath),
      "preserved file should be recorded under result.skipped (protected root)",
    );
    assert.ok(
      !result.updated.includes(layerRulesPath),
      "preserved file must not appear in result.updated",
    );

    console.log(
      "✅ self-regen without forceRoot → preserves user invariant file (protected root)",
    );
  });

  // ---------------------------------------------------------------------------
  // 7) manifest.monorepo.archInvariants templates are used when present
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      scope: "demo",
      architecture: "modular-monolith",
      bounded_contexts: [{ name: "shared" }],
      monorepo: {
        archInvariants: {
          layerRules: {
            template:
              "# CUSTOM layer-rules for {scope} ({workspaceTemplate})\ncustom: true\n",
          },
          linterConfig: {
            template: "# CUSTOM linter-config for @{scope}/shared\n",
          },
          generatorConfig: {
            template:
              "# CUSTOM generator-config — workspace={workspaceTemplate}\n",
          },
        },
      },
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    await generateArchitectureFiles(config);

    const layerRules = await readText(
      path.join(archDir, "invariants", "layer-rules.yaml"),
    );
    const linter = await readText(
      path.join(archDir, "invariants", "linter-config.yaml"),
    );
    const genCfg = await readText(path.join(archDir, "generator.config.yaml"));

    assert.ok(
      layerRules.startsWith("# CUSTOM layer-rules for demo (modular-monolith)"),
      "manifest-supplied layerRules template should be used and interpolated",
    );
    assert.ok(
      linter.includes("# CUSTOM linter-config for @demo/shared"),
      "manifest-supplied linterConfig template should be used and interpolated",
    );
    assert.ok(
      genCfg.includes("# CUSTOM generator-config — workspace=modular-monolith"),
      "manifest-supplied generatorConfig template should be used and interpolated",
    );

    console.log(
      "✅ manifest.monorepo.archInvariants templates are used when present",
    );
  });

  // ---------------------------------------------------------------------------
  // 8) Falls back to built-in templates when archInvariants absent
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    // strict-enterprise selects the strict-enterprise built-ins for both
    // layer-rules and linter-config.
    const manifest: Manifest = {
      scope: "acme",
      // Use the legacy workspaceTemplate field to exercise the fallback
      // resolution path in resolveWorkspaceTemplate.
      workspaceTemplate: "strict-enterprise",
      bounded_contexts: [{ name: "shared" }],
    } as Manifest;
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    await generateArchitectureFiles(config);

    const layerRules = await readText(
      path.join(archDir, "invariants", "layer-rules.yaml"),
    );
    const linter = await readText(
      path.join(archDir, "invariants", "linter-config.yaml"),
    );

    // Built-in strict-enterprise marker lines (see architecture-files.ts):
    assert.ok(
      layerRules.includes("Template: strict-enterprise — event-bus boundaries"),
      "built-in strict-enterprise layer-rules should be emitted when archInvariants absent",
    );
    assert.ok(
      layerRules.includes('required_communication: "event-bus"'),
      "built-in strict-enterprise layer-rules should include event-bus cross-context rule",
    );
    assert.ok(
      linter.includes("(strict mode)") &&
        linter.includes("deny_sibling_imports: true"),
      "built-in strict-enterprise linter-config should emit the strict rule set",
    );
    assert.ok(
      linter.includes('"@acme/shared"'),
      "linter-config should interpolate the manifest scope into @{scope}/shared",
    );

    console.log(
      "✅ archInvariants absent → built-in templates used and scope interpolated",
    );
  });

  // ---------------------------------------------------------------------------
  // 9) Interpolates {scope}, {template}, {workspaceTemplate}, {ownershipBlock}
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      scope: "octo",
      architecture: "microservices",
      bounded_contexts: [
        {
          name: "catalog",
          layers: {
            application: {
              ports: {
                in: ["search.in-port.ts"],
                out: ["repository.out-port.ts"],
              },
            },
            infrastructure: {
              adapters: ["postgres.adapter.ts"],
            },
          },
        },
      ],
      monorepo: {
        archInvariants: {
          layerRules: {
            template:
              "scope={scope}\ntemplate={template}\nworkspaceTemplate={workspaceTemplate}\n",
          },
          generatorConfig: {
            template: "ports:\n{ownershipBlock}\n",
          },
        },
      },
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    await generateArchitectureFiles(config);

    const layerRules = await readText(
      path.join(archDir, "invariants", "layer-rules.yaml"),
    );
    assert.ok(
      layerRules.includes("scope=octo"),
      "{scope} must be interpolated to the manifest scope",
    );
    assert.ok(
      layerRules.includes("template=microservices"),
      "{template} must be interpolated to the workspace-template alias",
    );
    assert.ok(
      layerRules.includes("workspaceTemplate=microservices"),
      "{workspaceTemplate} must be interpolated to the same value as {template}",
    );

    const genCfg = await readText(path.join(archDir, "generator.config.yaml"));
    assert.ok(
      genCfg.includes("      Search: catalog") &&
        genCfg.includes("      Repository: catalog") &&
        genCfg.includes("      Postgres: catalog"),
      "{ownershipBlock} must expand to PascalCase'd ports/adapters mapped to bounded context",
    );

    console.log(
      "✅ interpolates {scope}, {template}, {workspaceTemplate}, {ownershipBlock}",
    );
  });

  // ---------------------------------------------------------------------------
  // 10) Ownership block correctly generated from bounded_contexts[].layers
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot, archDir }) => {
    const manifest: Manifest = {
      scope: "own",
      architecture: "modular-monolith",
      bounded_contexts: [
        // `shared` must be skipped per buildOwnershipBlock.
        { name: "shared" },
        {
          name: "orders",
          layers: {
            application: {
              ports: {
                in: ["place-order.in-port.ts", "cancel.in-port.ts"],
                out: ["order-repository.out-port.ts"],
              },
            },
            infrastructure: {
              adapters: ["sql-order-repository.adapter.ts"],
            },
          },
        },
        {
          name: "billing",
          // No ports / adapters declared → must contribute nothing.
          layers: {},
        },
      ],
    };
    const config = makeConfig(workspaceRoot, manifest, { mode: "external" });

    await generateArchitectureFiles(config);

    const genCfg = await readText(path.join(archDir, "generator.config.yaml"));

    // Must contain every expected ownership entry, PascalCase'd, indented 6.
    for (const expected of [
      "      PlaceOrder: orders",
      "      Cancel: orders",
      "      OrderRepository: orders",
      "      SqlOrderRepository: orders",
    ]) {
      assert.ok(
        genCfg.includes(expected),
        `ownership block should include "${expected}"`,
      );
    }

    // `shared` must NOT appear as an owner in the ownership block body.
    // Look only inside the ownership-registry.ports section (below that key).
    const idx = genCfg.indexOf("ownership-registry:");
    assert.ok(
      idx !== -1,
      "generator.config.yaml must include ownership-registry",
    );
    const ownershipSection = genCfg.slice(idx);
    assert.ok(
      !/:\s*shared$/m.test(ownershipSection),
      "no port/adapter should be owned by `shared` — the context is skipped",
    );

    // billing contributes no entries.
    assert.ok(
      !/:\s*billing$/m.test(ownershipSection),
      "context without ports/adapters should not contribute ownership entries",
    );

    console.log(
      "✅ ownership block: skips `shared`, PascalCases names, excludes empty contexts",
    );
  });

  // ---------------------------------------------------------------------------
  // 11) Missing-placeholder path produces a logger.warn diagnostic.
  //     (Guards the interpolateWithLogging branch.)
  // ---------------------------------------------------------------------------
  await withTempWorkspace(async ({ workspaceRoot }) => {
    const manifest: Manifest = {
      scope: "warn",
      bounded_contexts: [{ name: "shared" }],
      monorepo: {
        archInvariants: {
          layerRules: {
            template: "unresolved: {doesNotExist}\n",
          },
        },
      },
    };
    const capture = createCaptureLogger();
    const config = makeConfig(workspaceRoot, manifest, {
      mode: "external",
      logger: capture.logger,
    });

    await generateArchitectureFiles(config);

    const hasWarning = capture.warnings.some(
      (w) =>
        w.includes("architecture-files: unresolved placeholder") &&
        w.includes("doesNotExist") &&
        w.includes("invariants/layer-rules.yaml"),
    );
    assert.ok(
      hasWarning,
      "missing placeholder should surface as a logger.warn with label + variable name",
    );

    console.log(
      "✅ missing placeholder in a template → logger.warn with file label",
    );
  });

  console.log("\n✅ All architecture-files generator tests passed!");
})().catch((err) => {
  console.error("❌ architecture-files generator tests FAILED:", err);
  process.exitCode = 1;
});
