import { describe, it } from "node:test";
import assert from "node:assert";
import { promises as fs } from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import { generateArchitectureFiles } from "../../src/generators/architecture-files.js";
import type { Manifest } from "../../src/types/manifest.js";
import { makeCapturingLogger } from "../helpers/spy-logger.js";
import {
  withTempWorkspace,
  pathExists,
  readText,
} from "../helpers/fs-helpers.js";
import { makeConfig } from "../helpers/test-config.js";

const GENERATED_MARKER = "// @generated by @hexagen/sync";

describe("architecture files", () => {
  it("should create all architecture files in external mode on fresh target", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        system: "demo",
        scope: "demo",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      const result = await generateArchitectureFiles(config);

      const manifestPath = path.join(archDir, "manifest.yaml");
      const layerRulesPath = path.join(
        archDir,
        "invariants",
        "layer-rules.yaml",
      );
      const linterPath = path.join(archDir, "invariants", "linter-config.yaml");
      const genConfigPath = path.join(archDir, "generator.config.yaml");

      assert.strictEqual(
        await pathExists(manifestPath),
        true,
        "external fresh target should materialise .architecture/manifest.yaml",
      );
      assert.strictEqual(
        await pathExists(layerRulesPath),
        true,
        "external fresh target should materialise invariants/layer-rules.yaml",
      );
      assert.strictEqual(
        await pathExists(linterPath),
        true,
        "external fresh target should materialise invariants/linter-config.yaml",
      );
      assert.strictEqual(
        await pathExists(genConfigPath),
        true,
        "external fresh target should materialise generator.config.yaml",
      );

      const createdSet = new Set(result.created);
      assert.ok(
        createdSet.has(manifestPath),
        "result.created should include the manifest path",
      );
      assert.ok(
        createdSet.has(layerRulesPath) &&
          createdSet.has(linterPath) &&
          createdSet.has(genConfigPath),
        "result.created should include all three invariant/config files",
      );
      assert.strictEqual(
        result.totalOps,
        4,
        "totalOps should equal 4 when all four files are freshly created",
      );
    });
  });

  it("should create manifest.yaml via yaml.dump when absent in external mode", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        system: "yaml-dump-target",
        scope: "yd",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "alpha" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const manifestPath = path.join(archDir, "manifest.yaml");
      const raw = await readText(manifestPath);
      const parsed = yaml.load(raw) as Manifest;

      assert.strictEqual(
        parsed.system,
        "yaml-dump-target",
        "dumped manifest must round-trip the `system` field",
      );
      assert.strictEqual(
        parsed.scope,
        "yd",
        "dumped manifest must round-trip the `scope` field",
      );
      assert.deepStrictEqual(
        parsed.bounded_contexts,
        [{ name: "alpha" }],
        "dumped manifest must round-trip the bounded_contexts array",
      );
    });
  });

  it("should preserve existing manifest.yaml in external mode", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      await fs.mkdir(archDir, { recursive: true });
      const manifestPath = path.join(archDir, "manifest.yaml");
      const sentinel =
        "# user-edited manifest — must be preserved verbatim\nsystem: user-owned\n";
      await fs.writeFile(manifestPath, sentinel, "utf8");

      const manifest: Manifest = {
        system: "engine-supplied",
        bounded_contexts: [{ name: "beta" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      const result = await generateArchitectureFiles(config);

      const afterContent = await readText(manifestPath);
      assert.strictEqual(
        afterContent,
        sentinel,
        "external mode must NEVER overwrite an existing manifest.yaml (ALWAYS protected)",
      );
      assert.ok(
        result.skipped.includes(manifestPath),
        "manifest.yaml should appear in result.skipped when preserved",
      );
      assert.ok(
        !result.created.includes(manifestPath),
        "manifest.yaml must not appear in result.created when it already exists",
      );
    });
  });

  it("should skip manifest.yaml entirely in self-regen mode", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        system: "self-regen-demo",
        bounded_contexts: [{ name: "gamma" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "self-regen",
        forceRoot: true,
      });

      const result = await generateArchitectureFiles(config);

      const manifestPath = path.join(archDir, "manifest.yaml");
      assert.strictEqual(
        await pathExists(manifestPath),
        false,
        "self-regen mode must never create .architecture/manifest.yaml",
      );
      assert.ok(
        !result.created.includes(manifestPath) &&
          !result.skipped.includes(manifestPath) &&
          !result.updated.includes(manifestPath),
        "self-regen mode must not record manifest.yaml in any result bucket (early return)",
      );
    });
  });

  it("should regenerate stale @generated invariant file in self-regen with forceRoot", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const invariantsDir = path.join(archDir, "invariants");
      await fs.mkdir(invariantsDir, { recursive: true });
      const layerRulesPath = path.join(invariantsDir, "layer-rules.yaml");
      const stale = `${GENERATED_MARKER}\n# stale generated content — should be replaced\n`;
      await fs.writeFile(layerRulesPath, stale, "utf8");

      const manifest: Manifest = {
        scope: "regen",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "self-regen",
        forceRoot: true,
      });

      const result = await generateArchitectureFiles(config);

      const after = await readText(layerRulesPath);
      assert.notStrictEqual(
        after,
        stale,
        "self-regen with forceRoot should overwrite stale @generated invariant file",
      );
      assert.ok(
        after.includes("@regen/shared"),
        "regenerated layer-rules.yaml should contain interpolated scope `@regen/shared`",
      );
      assert.ok(
        result.updated.includes(layerRulesPath),
        "layer-rules.yaml should appear in result.updated when regenerated",
      );
    });
  });

  it("should preserve user-customised invariant file in self-regen without forceRoot", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const invariantsDir = path.join(archDir, "invariants");
      await fs.mkdir(invariantsDir, { recursive: true });
      const layerRulesPath = path.join(invariantsDir, "layer-rules.yaml");
      const custom =
        "# user customisation — no @generated marker\nlayers:\n  domain:\n    custom: true\n";
      await fs.writeFile(layerRulesPath, custom, "utf8");

      const manifest: Manifest = {
        scope: "regen2",
        bounded_contexts: [{ name: "shared" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "self-regen",
        forceRoot: false,
      });

      const result = await generateArchitectureFiles(config);

      const after = await readText(layerRulesPath);
      assert.strictEqual(
        after,
        custom,
        "self-regen without forceRoot must preserve user-customised invariant file",
      );
      assert.ok(
        result.skipped.includes(layerRulesPath),
        "preserved file should be recorded under result.skipped (protected root)",
      );
      assert.ok(
        !result.updated.includes(layerRulesPath),
        "preserved file must not appear in result.updated",
      );
    });
  });

  it("should use manifest monorepo archInvariants templates when present", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        scope: "demo",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
        monorepo: {
          archInvariants: {
            layerRules: {
              template:
                "# CUSTOM layer-rules for {scope} ({workspaceTemplate})\ncustom: true\n",
            },
            linterConfig: {
              template: "# CUSTOM linter-config for @{scope}/shared\n",
            },
            generatorConfig: {
              template:
                "# CUSTOM generator-config — workspace={workspaceTemplate}\n",
            },
          },
        },
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const layerRules = await readText(
        path.join(archDir, "invariants", "layer-rules.yaml"),
      );
      const linter = await readText(
        path.join(archDir, "invariants", "linter-config.yaml"),
      );
      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      assert.ok(
        layerRules.startsWith(
          "# CUSTOM layer-rules for demo (modular-monolith)",
        ),
        "manifest-supplied layerRules template should be used and interpolated",
      );
      assert.ok(
        linter.includes("# CUSTOM linter-config for @demo/shared"),
        "manifest-supplied linterConfig template should be used and interpolated",
      );
      assert.ok(
        genCfg.includes(
          "# CUSTOM generator-config — workspace=modular-monolith",
        ),
        "manifest-supplied generatorConfig template should be used and interpolated",
      );
    });
  });

  it("should use built-in templates and interpolate scope when archInvariants absent", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        scope: "acme",
        workspaceTemplate: "strict-enterprise",
        bounded_contexts: [{ name: "shared" }],
      } as Manifest;
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const layerRules = await readText(
        path.join(archDir, "invariants", "layer-rules.yaml"),
      );
      const linter = await readText(
        path.join(archDir, "invariants", "linter-config.yaml"),
      );

      assert.ok(
        layerRules.includes(
          "Template: strict-enterprise — event-bus boundaries",
        ),
        "built-in strict-enterprise layer-rules should be emitted when archInvariants absent",
      );
      assert.ok(
        layerRules.includes('required_communication: "event-bus"'),
        "built-in strict-enterprise layer-rules should include event-bus cross-context rule",
      );
      assert.ok(
        linter.includes("(strict mode)") &&
          linter.includes("deny_sibling_imports: true"),
        "built-in strict-enterprise linter-config should emit the strict rule set",
      );
      assert.ok(
        linter.includes('"@acme/shared"'),
        "linter-config should interpolate the manifest scope into @{scope}/shared",
      );
    });
  });

  it("should interpolate {scope}, {template}, {workspaceTemplate}, and {ownershipBlock}", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        scope: "octo",
        architecture: "microservices",
        bounded_contexts: [
          {
            name: "catalog",
            layers: {
              application: {
                ports: {
                  in: ["search.in-port.ts"],
                  out: ["repository.out-port.ts"],
                },
              },
              infrastructure: {
                adapters: ["postgres.adapter.ts"],
              },
            },
          },
        ],
        monorepo: {
          archInvariants: {
            layerRules: {
              template:
                "scope={scope}\ntemplate={template}\nworkspaceTemplate={workspaceTemplate}\n",
            },
            generatorConfig: {
              template: "ports:\n{ownershipBlock}\n",
            },
          },
        },
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const layerRules = await readText(
        path.join(archDir, "invariants", "layer-rules.yaml"),
      );
      assert.ok(
        layerRules.includes("scope=octo"),
        "{scope} must be interpolated to the manifest scope",
      );
      assert.ok(
        layerRules.includes("template=microservices"),
        "{template} must be interpolated to the workspace-template alias",
      );
      assert.ok(
        layerRules.includes("workspaceTemplate=microservices"),
        "{workspaceTemplate} must be interpolated to the same value as {template}",
      );

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );
      assert.ok(
        genCfg.includes("      Search: catalog") &&
          genCfg.includes("      Repository: catalog") &&
          genCfg.includes("      Postgres: catalog"),
        "{ownershipBlock} must expand to PascalCase'd ports/adapters mapped to bounded context",
      );
    });
  });

  it("should build ownership block with correct context assignments", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        scope: "own",
        architecture: "modular-monolith",
        bounded_contexts: [
          { name: "shared" },
          {
            name: "orders",
            layers: {
              application: {
                ports: {
                  in: ["place-order.in-port.ts", "cancel.in-port.ts"],
                  out: ["order-repository.out-port.ts"],
                },
              },
              infrastructure: {
                adapters: ["sql-order-repository.adapter.ts"],
              },
            },
          },
          {
            name: "billing",
            layers: {},
          },
        ],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      for (const expected of [
        "      PlaceOrder: orders",
        "      Cancel: orders",
        "      OrderRepository: orders",
        "      SqlOrderRepository: orders",
      ]) {
        assert.ok(
          genCfg.includes(expected),
          `ownership block should include "${expected}"`,
        );
      }

      const idx = genCfg.indexOf("ownership-registry:");
      assert.ok(
        idx !== -1,
        "generator.config.yaml must include ownership-registry",
      );
      const ownershipSection = genCfg.slice(idx);
      assert.ok(
        !/:\s*shared$/m.test(ownershipSection),
        "no port/adapter should be owned by `shared` — the context is skipped",
      );
      assert.ok(
        !/:\s*billing$/m.test(ownershipSection),
        "context without ports/adapters should not contribute ownership entries",
      );
    });
  });

  it("qualifies cross-context ownership collisions and keeps the YAML loadable", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      // The campaign-foundry shape (RCA #9): two contexts declare the same
      // port/adapter stem. Bare keys would be a duplicate YAML mapping key —
      // js-yaml load() throws on it — inside the very document whose
      // port-single-ownership invariant promises exactly one owner.
      const manifest: Manifest = {
        scope: "col",
        system: "collision-demo",
        architecture: "modular-monolith",
        bounded_contexts: [
          {
            name: "catalog",
            layers: {
              infrastructure: {
                adapters: ["external-service-client.adapter.ts"],
              },
            },
          },
          {
            name: "search-api",
            layers: {
              application: {
                ports: { out: ["external-service-client.out-port.ts"] },
              },
            },
          },
        ],
      };
      const capture = makeCapturingLogger();
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        logger: capture.logger,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      assert.ok(
        genCfg.includes('      "catalog.ExternalServiceClient": catalog'),
        "first claimant should get a raw-context-qualified key",
      );
      assert.ok(
        genCfg.includes('      "search-api.ExternalServiceClient": search-api'),
        "second claimant should get a raw-context-qualified key",
      );
      assert.ok(
        !/^\s+ExternalServiceClient:/m.test(genCfg),
        "the contested name must not also appear as a bare key",
      );

      // Full-document round-trip through the strict loader — this is the
      // actual consumer-facing contract (duplicate keys would throw here).
      const parsed = yaml.load(genCfg) as {
        generator: {
          "ownership-registry": { ports: Record<string, string> };
        };
      };
      assert.strictEqual(
        parsed.generator["ownership-registry"].ports[
          "catalog.ExternalServiceClient"
        ],
        "catalog",
        "qualified key must survive a YAML round-trip with its owner intact",
      );
      assert.strictEqual(
        parsed.generator["ownership-registry"].ports[
          "search-api.ExternalServiceClient"
        ],
        "search-api",
        "qualified key must survive a YAML round-trip with its owner intact",
      );

      const hasCollisionWarning = capture.logs.some(
        (w) =>
          w.level === "warn" &&
          w.message.includes("ownership-registry name collision") &&
          w.message.includes("ExternalServiceClient"),
      );
      assert.ok(
        hasCollisionWarning,
        "a cross-context collision should surface as a logger.warn naming the contested stem",
      );
    });
  });

  it("keeps qualified keys distinct when context names normalize identically", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      // `api2` and `api-2` both PascalCase to `Api2` — a normalized qualifier
      // would collapse them back into a duplicate YAML key. The raw-context
      // qualifier must keep them distinct.
      const manifest: Manifest = {
        scope: "nrm",
        system: "normalize-demo",
        architecture: "modular-monolith",
        bounded_contexts: [
          {
            name: "api2",
            layers: {
              application: {
                ports: { out: ["widget-sync.out-port.ts"] },
              },
            },
          },
          {
            name: "api-2",
            layers: {
              infrastructure: {
                adapters: ["widget-sync.adapter.ts"],
              },
            },
          },
        ],
      };
      const capture = makeCapturingLogger();
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        logger: capture.logger,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      const parsed = yaml.load(genCfg) as {
        generator: {
          "ownership-registry": { ports: Record<string, string> };
        };
      };
      const ports = parsed.generator["ownership-registry"].ports;
      assert.strictEqual(
        ports["api2.WidgetSync"],
        "api2",
        "raw-context qualifier must keep the first claimant distinct",
      );
      assert.strictEqual(
        ports["api-2.WidgetSync"],
        "api-2",
        "raw-context qualifier must keep the second claimant distinct",
      );
      assert.ok(
        capture.logs.some(
          (w) =>
            w.level === "warn" &&
            w.message.includes("ownership-registry name collision") &&
            w.message.includes("WidgetSync"),
        ),
        "the collision warning still fires for identically-normalizing contexts",
      );
    });
  });

  it("dedupes a same-context in/out port stem pair to one ownership entry", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      // payment.in-port.ts + payment.out-port.ts both PascalCase to `Payment`.
      // Same context, one ownership fact — emitting it twice was a duplicate
      // YAML key even with identical values (js-yaml throws regardless).
      const manifest: Manifest = {
        scope: "dd",
        system: "dedupe-demo",
        architecture: "modular-monolith",
        bounded_contexts: [
          {
            name: "orders",
            layers: {
              application: {
                ports: {
                  in: ["payment.in-port.ts"],
                  out: ["payment.out-port.ts"],
                },
              },
            },
          },
        ],
      };
      const capture = makeCapturingLogger();
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        logger: capture.logger,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      const occurrences = genCfg.split("      Payment: orders").length - 1;
      assert.strictEqual(
        occurrences,
        1,
        "an in/out stem pair in the same context must emit exactly one entry",
      );
      assert.doesNotThrow(
        () => yaml.load(genCfg),
        "the emitted document must satisfy the strict loader",
      );
      assert.ok(
        !capture.logs.some(
          (w) =>
            w.level === "warn" &&
            w.message.includes("ownership-registry name collision"),
        ),
        "a same-context stem pair is not a collision — no warning expected",
      );
    });
  });

  it("emits the camelCase workspaceTemplate key (matches the manifest spelling)", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      const manifest: Manifest = {
        scope: "case",
        system: "case-demo",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      assert.ok(
        !genCfg.includes("workspace_template"),
        "the snake_case key (matched nothing in the toolchain) must be gone",
      );
      const parsed = yaml.load(genCfg) as {
        generator: { workspaceTemplate: string };
      };
      assert.strictEqual(
        parsed.generator.workspaceTemplate,
        "modular-monolith",
        "generator.workspaceTemplate should carry the resolved workspace template",
      );
    });
  });

  it("quotes a YAML-hostile context name on the value side so the document still parses", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      // A context name that is NOT a safe plain scalar (leading `*` — a YAML
      // alias indicator). Bare, `Ledger: *billing-svc` throws at load; the
      // value side (like the key) must be quoted. Real kebab/alnum names stay
      // bare — the other ownership tests are the byte-identity regression net.
      const manifest: Manifest = {
        scope: "hz",
        system: "hostile-demo",
        architecture: "modular-monolith",
        bounded_contexts: [
          {
            name: "*billing-svc",
            layers: {
              application: { ports: { out: ["ledger.out-port.ts"] } },
            },
          },
        ],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      assert.ok(
        genCfg.includes('Ledger: "*billing-svc"'),
        "a hostile context value must be double-quoted",
      );
      const parsed = yaml.load(genCfg) as {
        generator: {
          "ownership-registry": { ports: Record<string, string> };
        };
      };
      assert.strictEqual(
        parsed.generator["ownership-registry"].ports["Ledger"],
        "*billing-svc",
        "the quoted value must round-trip to the raw context name",
      );
    });
  });

  it("round-trips a contested name whose context is hostile (quoted key AND quoted value)", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const archDir = path.join(workspaceRoot, ".architecture");
      // A hostile context (`a"b`, embedded double-quote) AND a safe one both
      // claim the same stem → contested. For the hostile one BOTH the qualified
      // KEY (JSON.stringify) and the VALUE (yamlScalar → JSON.stringify) carry a
      // JSON escape; this pins that the two quoting paths compose and the whole
      // document still loads — the combination the *billing-svc test (a single,
      // non-contested context) leaves only reasoned.
      const manifest: Manifest = {
        scope: "ch",
        system: "contested-hostile",
        architecture: "modular-monolith",
        bounded_contexts: [
          {
            name: 'a"b',
            layers: { application: { ports: { out: ["widget.out-port.ts"] } } },
          },
          {
            name: "catalog",
            layers: { infrastructure: { adapters: ["widget.adapter.ts"] } },
          },
        ],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
      });

      await generateArchitectureFiles(config);

      const genCfg = await readText(
        path.join(archDir, "generator.config.yaml"),
      );

      const parsed = yaml.load(genCfg) as {
        generator: {
          "ownership-registry": { ports: Record<string, string> };
        };
      };
      const ports = parsed.generator["ownership-registry"].ports;
      assert.strictEqual(
        ports['a"b.Widget'],
        'a"b',
        "the hostile context's qualified key AND value must both round-trip through JSON/YAML escaping",
      );
      assert.strictEqual(
        ports["catalog.Widget"],
        "catalog",
        "the safe contested entry stays alongside, keys distinct",
      );
    });
  });

  it("should warn on unresolved template placeholders", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const manifest: Manifest = {
        scope: "warn",
        bounded_contexts: [{ name: "shared" }],
        monorepo: {
          archInvariants: {
            layerRules: {
              template: "unresolved: {doesNotExist}\n",
            },
          },
        },
      };
      const capture = makeCapturingLogger();
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        logger: capture.logger,
      });

      await generateArchitectureFiles(config);

      const hasWarning = capture.logs.some(
        (w) =>
          w.level === "warn" &&
          w.message.includes("architecture-files: unresolved placeholder") &&
          w.message.includes("doesNotExist") &&
          w.message.includes("invariants/layer-rules.yaml"),
      );
      assert.ok(
        hasWarning,
        "missing placeholder should surface as a logger.warn with label + variable name",
      );
    });
  });
});

describe("architecture files — --only scope", () => {
  it("does NOT materialise the external manifest when it is out of scope", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const manifest: Manifest = {
        system: "demo",
        scope: "demo",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
      };
      // External + fresh target would normally write .architecture/manifest.yaml
      // via a direct fs.writeFile. With --only pointing elsewhere it must be
      // skipped — the write bypasses safeWriteFileAtomic, so the guard lives in
      // writeManifestIfFreshExternal itself.
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        only: ["packages/something-else"],
      });

      const result = await generateArchitectureFiles(config);

      const manifestPath = path.join(
        workspaceRoot,
        ".architecture",
        "manifest.yaml",
      );
      assert.strictEqual(
        await pathExists(manifestPath),
        false,
        "out-of-scope external manifest must NOT be written",
      );
      assert.ok(
        result.skipped.some((p) => p.endsWith("manifest.yaml")),
        "the skipped manifest should be recorded in result.skipped",
      );
    });
  });

  it("materialises the external manifest when .architecture is in scope", async () => {
    await withTempWorkspace(async ({ workspaceRoot }) => {
      const manifest: Manifest = {
        system: "demo",
        scope: "demo",
        architecture: "modular-monolith",
        bounded_contexts: [{ name: "shared" }],
      };
      const config = makeConfig(workspaceRoot, manifest, {
        mode: "external",
        forceRoot: true,
        only: [".architecture"],
      });

      await generateArchitectureFiles(config);

      const manifestPath = path.join(
        workspaceRoot,
        ".architecture",
        "manifest.yaml",
      );
      assert.strictEqual(
        await pathExists(manifestPath),
        true,
        "in-scope external manifest must be written",
      );
    });
  });
});
