import assert from "node:assert";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateEslintConfig } from "../../src/generators/eslint.js";
import type { Manifest } from "../../src/types/manifest.js";
import type { SyncConfig, LoggerPort } from "../../src/config.js";

/**
 * Tests for the sync-engine-unified-scaffolding §Phase 4 eslint generator.
 *
 * Covers:
 *   - Emission of the `// @generated by @hexagen/sync` marker
 *   - The three-level merge cascade
 *     (per-context override > workspaceDefaults > built-in fallback)
 *   - safeWriteFileAtomic protection of hand-written eslint.config.js
 *     (files without the @generated marker are preserved)
 *   - Regeneration of previously generated files when the template changes
 *   - `{packageName}` and `{scope}` interpolation
 *   - Empty-template failure mode: error logged + file skipped (not aborted)
 *
 * Style intentionally mirrors `package-json.test.ts`: disposable temp
 * workspace per test, silent logger by default, capture-logger when a test
 * needs to assert on logged messages.
 */

// -----------------------------------------------------------------------------
// Test helpers
// -----------------------------------------------------------------------------

/** No-op logger satisfying LoggerPort without cluttering test output. */
const silentLogger: LoggerPort = {
  error: () => {},
  warn: () => {},
  info: () => {},
  debug: () => {},
  errorWithException: () => {},
};

interface CapturedLogger extends LoggerPort {
  errors: string[];
  warns: string[];
}

/**
 * Logger that records `error` / `warn` messages so tests can assert the
 * generator surfaced the expected diagnostics. Other levels are silent.
 */
function makeCapturedLogger(): CapturedLogger {
  const errors: string[] = [];
  const warns: string[] = [];
  return {
    errors,
    warns,
    error: (msg) => {
      errors.push(String(msg));
    },
    warn: (msg) => {
      warns.push(String(msg));
    },
    info: () => {},
    debug: () => {},
    errorWithException: () => {},
  };
}

function makeConfig(
  workspaceRoot: string,
  manifest: Manifest,
  logger: LoggerPort = silentLogger,
): SyncConfig {
  return {
    dryRun: false,
    force: false,
    forceRoot: false,
    allowDirty: false,
    strict: false,
    mode: "external",
    logger,
    manifest,
    workspaceRoot,
  };
}

/**
 * Run `fn` inside a disposable temp workspace containing a single package
 * directory at `packages/<moduleName>/`. The workspace is removed on exit.
 */
async function withTempWorkspace(
  moduleName: string,
  fn: (ctx: {
    workspaceRoot: string;
    modulePath: string;
    eslintPath: string;
  }) => Promise<void>,
) {
  const workspaceRoot = await fs.mkdtemp(
    path.join(os.tmpdir(), "hexagen-eslint-test-"),
  );
  const modulePath = path.join(workspaceRoot, "packages", moduleName);
  await fs.mkdir(modulePath, { recursive: true });
  const eslintPath = path.join(modulePath, "eslint.config.js");
  try {
    await fn({ workspaceRoot, modulePath, eslintPath });
  } finally {
    await fs.rm(workspaceRoot, { recursive: true, force: true });
  }
}

const GENERATED_MARKER_LINE = "// @generated by @hexagen/sync";

// -----------------------------------------------------------------------------
// Test cases
// -----------------------------------------------------------------------------

(async () => {
  console.log("Running eslint generator tests...\n");

  // ---------------------------------------------------------------------------
  // 1) @generated marker + fresh-file creation
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "fresh-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      const manifest: Manifest = {
        bounded_contexts: [{ name: "fresh-pkg" }],
      };
      const config = makeConfig(workspaceRoot, manifest);

      const result = await generateEslintConfig(
        path.dirname(eslintPath),
        "fresh-pkg",
        config,
      );

      assert.strictEqual(
        result.created.length,
        1,
        "fresh package should report exactly one created file",
      );
      assert.strictEqual(
        result.created[0],
        eslintPath,
        "created entry should be the eslint.config.js path",
      );
      assert.strictEqual(
        result.updated.length,
        0,
        "fresh package should not report any updated files",
      );
      assert.strictEqual(
        result.skipped.length,
        0,
        "fresh package should not report any skipped files",
      );

      const content = await fs.readFile(eslintPath, "utf8");
      assert.ok(
        content.startsWith(`${GENERATED_MARKER_LINE}\n`),
        "emitted file must start with the @generated marker line",
      );
      console.log(
        "✅ creates eslint.config.js prefixed with the @generated marker",
      );
    },
  );

  // ---------------------------------------------------------------------------
  // 2) Cascade level 3: built-in fallback
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "fallback-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      // Manifest declares neither workspaceDefaults.eslint nor per-context
      // generator.eslint — the generator must fall back to the built-in
      // template.
      const manifest: Manifest = {
        bounded_contexts: [{ name: "fallback-pkg" }],
      };
      const config = makeConfig(workspaceRoot, manifest);

      await generateEslintConfig(
        path.dirname(eslintPath),
        "fallback-pkg",
        config,
      );

      const content = await fs.readFile(eslintPath, "utf8");
      // The built-in fallback is the static legacy config ported from
      // root-files.ts. We assert on stable substrings rather than the full
      // body to avoid coupling the test to whitespace.
      assert.ok(
        content.includes("import eslint from '@eslint/js';"),
        "fallback template should include the @eslint/js import",
      );
      assert.ok(
        content.includes("import tseslint from 'typescript-eslint';"),
        "fallback template should include the typescript-eslint import",
      );
      assert.ok(
        content.includes("'@typescript-eslint/no-explicit-any': 'warn'"),
        "fallback template should include the legacy no-explicit-any rule",
      );
      console.log(
        "✅ uses built-in fallback when neither workspace nor per-context template is declared",
      );
    },
  );

  // ---------------------------------------------------------------------------
  // 3) Cascade level 2: workspaceDefaults.eslint.template overrides fallback
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "workspace-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      const workspaceTemplate =
        "// workspace-level eslint config\nexport default [];\n";
      const manifest: Manifest = {
        monorepo: {
          workspaceDefaults: {
            eslint: { template: workspaceTemplate },
          },
        },
        bounded_contexts: [{ name: "workspace-pkg" }],
      };
      const config = makeConfig(workspaceRoot, manifest);

      await generateEslintConfig(
        path.dirname(eslintPath),
        "workspace-pkg",
        config,
      );

      const content = await fs.readFile(eslintPath, "utf8");
      assert.strictEqual(
        content,
        `${GENERATED_MARKER_LINE}\n${workspaceTemplate}`,
        "workspaceDefaults template (with prepended marker) should be written verbatim",
      );
      // Guard against accidental fallback usage.
      assert.ok(
        !content.includes("import eslint from '@eslint/js';"),
        "fallback template must NOT leak into the output when workspaceDefaults is set",
      );
      console.log(
        "✅ workspaceDefaults.eslint.template overrides the built-in fallback",
      );
    },
  );

  // ---------------------------------------------------------------------------
  // 4) Cascade level 1: per-context generator.eslint.template overrides workspace
  // ---------------------------------------------------------------------------
  await withTempWorkspace("ctx-pkg", async ({ workspaceRoot, eslintPath }) => {
    const workspaceTemplate = "// workspace template — should be shadowed\n";
    const contextTemplate =
      "// per-context template wins\nexport default {};\n";
    const manifest: Manifest = {
      monorepo: {
        workspaceDefaults: {
          eslint: { template: workspaceTemplate },
        },
      },
      bounded_contexts: [
        {
          name: "ctx-pkg",
          generator: {
            eslint: { template: contextTemplate },
          },
        },
      ],
    };
    const config = makeConfig(workspaceRoot, manifest);

    await generateEslintConfig(path.dirname(eslintPath), "ctx-pkg", config);

    const content = await fs.readFile(eslintPath, "utf8");
    assert.strictEqual(
      content,
      `${GENERATED_MARKER_LINE}\n${contextTemplate}`,
      "per-context template should win over workspaceDefaults",
    );
    assert.ok(
      !content.includes("should be shadowed"),
      "workspaceDefaults template must not appear when a per-context template is set",
    );
    console.log(
      "✅ per-context generator.eslint.template overrides workspaceDefaults",
    );
  });

  // ---------------------------------------------------------------------------
  // 5) Hand-written eslint.config.js is preserved (no @generated marker)
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "handwritten-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      // User-authored config WITHOUT the @generated marker — must be left
      // untouched by safeWriteFileAtomic's isGeneratedFile check.
      const handwritten =
        "// Hand-written by a human. Do not modify.\nexport default [\n  { rules: { 'no-console': 'error' } },\n];\n";
      await fs.writeFile(eslintPath, handwritten, "utf8");

      const manifest: Manifest = {
        monorepo: {
          workspaceDefaults: {
            eslint: {
              template:
                "// generator tried to overwrite this\nexport default [];\n",
            },
          },
        },
        bounded_contexts: [{ name: "handwritten-pkg" }],
      };
      const config = makeConfig(workspaceRoot, manifest);

      const result = await generateEslintConfig(
        path.dirname(eslintPath),
        "handwritten-pkg",
        config,
      );

      const onDisk = await fs.readFile(eslintPath, "utf8");
      assert.strictEqual(
        onDisk,
        handwritten,
        "hand-written eslint.config.js must be preserved verbatim",
      );
      assert.strictEqual(
        result.created.length,
        0,
        "existing hand-written file must not be reported as created",
      );
      assert.strictEqual(
        result.updated.length,
        0,
        "existing hand-written file must not be reported as updated",
      );
      assert.strictEqual(
        result.skipped.length,
        1,
        "existing hand-written file must be reported as skipped",
      );
      assert.strictEqual(
        result.skipped[0],
        eslintPath,
        "skipped entry should be the eslint.config.js path",
      );
      console.log(
        "✅ preserves hand-written eslint.config.js (no @generated marker)",
      );
    },
  );

  // ---------------------------------------------------------------------------
  // 6) Regenerates a previously-@generated file when the template changes
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "regen-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      // Seed the file with a DIFFERENT previously-generated body (marker
      // present). Content hash must differ from the new template so
      // safeWriteFileAtomic classifies the write as "updated", not
      // "unchanged".
      const stalePreviousBody =
        "// old generated body\nexport default [{ rules: {} }];\n";
      await fs.writeFile(
        eslintPath,
        `${GENERATED_MARKER_LINE}\n${stalePreviousBody}`,
        "utf8",
      );

      const newTemplate =
        "// refreshed generated body\nexport default [{ rules: { 'no-debugger': 'error' } }];\n";
      const manifest: Manifest = {
        monorepo: {
          workspaceDefaults: {
            eslint: { template: newTemplate },
          },
        },
        bounded_contexts: [{ name: "regen-pkg" }],
      };
      const config = makeConfig(workspaceRoot, manifest);

      const result = await generateEslintConfig(
        path.dirname(eslintPath),
        "regen-pkg",
        config,
      );

      assert.strictEqual(
        result.updated.length,
        1,
        "stale @generated file should be reported as updated",
      );
      assert.strictEqual(
        result.updated[0],
        eslintPath,
        "updated entry should be the eslint.config.js path",
      );
      assert.strictEqual(
        result.created.length,
        0,
        "regeneration must not be reported as created",
      );

      const onDisk = await fs.readFile(eslintPath, "utf8");
      assert.strictEqual(
        onDisk,
        `${GENERATED_MARKER_LINE}\n${newTemplate}`,
        "file on disk should reflect the new template body",
      );
      assert.ok(
        !onDisk.includes("old generated body"),
        "stale template body must be fully replaced",
      );
      console.log(
        "✅ regenerates @generated eslint.config.js when the template changes",
      );
    },
  );

  // ---------------------------------------------------------------------------
  // 7) {packageName} and {scope} interpolation
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "interp-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      const template =
        "// eslint for {packageName} in {scope}\nexport default { name: '{scope}/{packageName}' };\n";
      const manifest: Manifest = {
        scope: "acme",
        monorepo: {
          workspaceDefaults: {
            eslint: { template },
          },
        },
        bounded_contexts: [{ name: "interp-pkg" }],
      };
      const logger = makeCapturedLogger();
      const config = makeConfig(workspaceRoot, manifest, logger);

      await generateEslintConfig(
        path.dirname(eslintPath),
        "interp-pkg",
        config,
      );

      const content = await fs.readFile(eslintPath, "utf8");
      assert.ok(
        content.includes("// eslint for interp-pkg in acme"),
        "{packageName} and {scope} should both interpolate in comments",
      );
      assert.ok(
        content.includes("name: 'acme/interp-pkg'"),
        "{scope}/{packageName} should interpolate in the config body",
      );
      assert.ok(
        !content.includes("{packageName}"),
        "{packageName} placeholder must be fully resolved",
      );
      assert.ok(
        !content.includes("{scope}"),
        "{scope} placeholder must be fully resolved",
      );
      assert.strictEqual(
        logger.warns.length,
        0,
        "resolved placeholders must not emit interpolation warnings",
      );
      console.log("✅ interpolates {packageName} and {scope}");
    },
  );

  // ---------------------------------------------------------------------------
  // 8) Empty template at all levels: error logged, file skipped gracefully
  // ---------------------------------------------------------------------------
  await withTempWorkspace(
    "empty-pkg",
    async ({ workspaceRoot, eslintPath }) => {
      // Explicit empty string at the per-context level. Because
      // `contextOverride?.template !== undefined`, the empty string "wins"
      // the cascade and then triggers the `length === 0` defensive branch
      // in the generator — exercising the "Missing template + missing
      // fallback → log error, skip" contract.
      const manifest: Manifest = {
        bounded_contexts: [
          {
            name: "empty-pkg",
            generator: {
              eslint: { template: "" },
            },
          },
        ],
      };
      const logger = makeCapturedLogger();
      const config = makeConfig(workspaceRoot, manifest, logger);

      const result = await generateEslintConfig(
        path.dirname(eslintPath),
        "empty-pkg",
        config,
      );

      assert.strictEqual(
        result.created.length,
        0,
        "empty-template run must not create any files",
      );
      assert.strictEqual(
        result.updated.length,
        0,
        "empty-template run must not update any files",
      );
      assert.strictEqual(
        result.skipped.length,
        1,
        "empty-template run must report the file as skipped",
      );
      assert.strictEqual(
        result.skipped[0],
        eslintPath,
        "skipped entry should be the eslint.config.js path",
      );
      assert.ok(
        typeof result.summary === "string" &&
          result.summary.includes("empty-pkg"),
        "result.summary should mention the module name",
      );

      // Generator must NOT throw and must NOT write a file.
      await assert.rejects(
        fs.access(eslintPath),
        (err: NodeJS.ErrnoException) => err.code === "ENOENT",
        "no eslint.config.js should be written when the template is empty",
      );

      assert.ok(
        logger.errors.some((msg) =>
          msg.includes("No eslint template resolved for empty-pkg"),
        ),
        "generator should log an explicit error for the empty-template case",
      );
      console.log(
        "✅ empty template at all levels logs an error and skips gracefully",
      );
    },
  );

  console.log("\n✅ All eslint generator tests passed!");
})().catch((err) => {
  console.error("❌ eslint generator tests FAILED:", err);
  process.exitCode = 1;
});
