import { describe, it } from "vitest";
import assert from "node:assert";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateEslintConfig } from "../../src/generators/eslint.js";
import type { Manifest } from "../../src/types/manifest.js";
import type { SyncConfig, LoggerPort } from "../../src/config.js";

const silentLogger: LoggerPort = {
  error: () => {},
  warn: () => {},
  info: () => {},
  debug: () => {},
  errorWithException: () => {},
};

interface CapturedLogger extends LoggerPort {
  errors: string[];
  warns: string[];
}

function makeCapturedLogger(): CapturedLogger {
  const errors: string[] = [];
  const warns: string[] = [];
  return {
    errors,
    warns,
    error: (msg) => {
      errors.push(String(msg));
    },
    warn: (msg) => {
      warns.push(String(msg));
    },
    info: () => {},
    debug: () => {},
    errorWithException: () => {},
  };
}

function makeConfig(
  workspaceRoot: string,
  manifest: Manifest,
  logger: LoggerPort = silentLogger,
): SyncConfig {
  return {
    dryRun: false,
    force: false,
    forceRoot: false,
    allowDirty: false,
    strict: false,
    mode: "external",
    logger,
    manifest,
    workspaceRoot,
  };
}

async function withTempWorkspace(
  moduleName: string,
  fn: (ctx: {
    workspaceRoot: string;
    modulePath: string;
    eslintPath: string;
  }) => Promise<void>,
) {
  const workspaceRoot = await fs.mkdtemp(
    path.join(os.tmpdir(), "hexagen-eslint-test-"),
  );
  const modulePath = path.join(workspaceRoot, "packages", moduleName);
  await fs.mkdir(modulePath, { recursive: true });
  const eslintPath = path.join(modulePath, "eslint.config.js");
  try {
    await fn({ workspaceRoot, modulePath, eslintPath });
  } finally {
    await fs.rm(workspaceRoot, { recursive: true, force: true });
  }
}

const GENERATED_MARKER_LINE = "// @generated by @hexagen/sync";

describe("eslint", () => {
  it("should create eslint.config.js with @generated marker for fresh package", async () => {
    await withTempWorkspace(
      "fresh-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const manifest: Manifest = {
          bounded_contexts: [{ name: "fresh-pkg" }],
        };
        const config = makeConfig(workspaceRoot, manifest);

        const result = await generateEslintConfig(
          path.dirname(eslintPath),
          "fresh-pkg",
          config,
        );

        assert.strictEqual(
          result.created.length,
          1,
          "fresh package should report exactly one created file",
        );
        assert.strictEqual(
          result.created[0],
          eslintPath,
          "created entry should be the eslint.config.js path",
        );
        assert.strictEqual(
          result.updated.length,
          0,
          "fresh package should not report any updated files",
        );
        assert.strictEqual(
          result.skipped.length,
          0,
          "fresh package should not report any skipped files",
        );

        const content = await fs.readFile(eslintPath, "utf8");
        assert.ok(
          content.startsWith(`${GENERATED_MARKER_LINE}\n`),
          "emitted file must start with the @generated marker line",
        );
      },
    );
  });

  it("should use built-in fallback when no template is declared", async () => {
    await withTempWorkspace(
      "fallback-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const manifest: Manifest = {
          bounded_contexts: [{ name: "fallback-pkg" }],
        };
        const config = makeConfig(workspaceRoot, manifest);

        await generateEslintConfig(
          path.dirname(eslintPath),
          "fallback-pkg",
          config,
        );

        const content = await fs.readFile(eslintPath, "utf8");
        assert.ok(
          content.includes("import eslint from '@eslint/js';"),
          "fallback template should include the @eslint/js import",
        );
        assert.ok(
          content.includes("import tseslint from 'typescript-eslint';"),
          "fallback template should include the typescript-eslint import",
        );
        assert.ok(
          content.includes("'@typescript-eslint/no-explicit-any': 'warn'"),
          "fallback template should include the legacy no-explicit-any rule",
        );
      },
    );
  });

  it("should use workspaceDefaults eslint template over fallback", async () => {
    await withTempWorkspace(
      "workspace-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const workspaceTemplate =
          "// workspace-level eslint config\nexport default [];\n";
        const manifest: Manifest = {
          monorepo: {
            workspaceDefaults: {
              eslint: { template: workspaceTemplate },
            },
          },
          bounded_contexts: [{ name: "workspace-pkg" }],
        };
        const config = makeConfig(workspaceRoot, manifest);

        await generateEslintConfig(
          path.dirname(eslintPath),
          "workspace-pkg",
          config,
        );

        const content = await fs.readFile(eslintPath, "utf8");
        assert.strictEqual(
          content,
          `${GENERATED_MARKER_LINE}\n${workspaceTemplate}`,
          "workspaceDefaults template (with prepended marker) should be written verbatim",
        );
        assert.ok(
          !content.includes("import eslint from '@eslint/js';"),
          "fallback template must NOT leak into the output when workspaceDefaults is set",
        );
      },
    );
  });

  it("should use per-context generator eslint template over workspaceDefaults", async () => {
    await withTempWorkspace(
      "ctx-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const workspaceTemplate =
          "// workspace template — should be shadowed\n";
        const contextTemplate =
          "// per-context template wins\nexport default {};\n";
        const manifest: Manifest = {
          monorepo: {
            workspaceDefaults: {
              eslint: { template: workspaceTemplate },
            },
          },
          bounded_contexts: [
            {
              name: "ctx-pkg",
              generator: {
                eslint: { template: contextTemplate },
              },
            },
          ],
        };
        const config = makeConfig(workspaceRoot, manifest);

        await generateEslintConfig(path.dirname(eslintPath), "ctx-pkg", config);

        const content = await fs.readFile(eslintPath, "utf8");
        assert.strictEqual(
          content,
          `${GENERATED_MARKER_LINE}\n${contextTemplate}`,
          "per-context template should win over workspaceDefaults",
        );
        assert.ok(
          !content.includes("should be shadowed"),
          "workspaceDefaults template must not appear when a per-context template is set",
        );
      },
    );
  });

  it("should preserve hand-written eslint.config.js without @generated marker", async () => {
    await withTempWorkspace(
      "handwritten-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const handwritten =
          "// Hand-written by a human. Do not modify.\nexport default [\n  { rules: { 'no-console': 'error' } },\n];\n";
        await fs.writeFile(eslintPath, handwritten, "utf8");

        const manifest: Manifest = {
          monorepo: {
            workspaceDefaults: {
              eslint: {
                template:
                  "// generator tried to overwrite this\nexport default [];\n",
              },
            },
          },
          bounded_contexts: [{ name: "handwritten-pkg" }],
        };
        const config = makeConfig(workspaceRoot, manifest);

        const result = await generateEslintConfig(
          path.dirname(eslintPath),
          "handwritten-pkg",
          config,
        );

        const onDisk = await fs.readFile(eslintPath, "utf8");
        assert.strictEqual(
          onDisk,
          handwritten,
          "hand-written eslint.config.js must be preserved verbatim",
        );
        assert.strictEqual(
          result.created.length,
          0,
          "existing hand-written file must not be reported as created",
        );
        assert.strictEqual(
          result.updated.length,
          0,
          "existing hand-written file must not be reported as updated",
        );
        assert.strictEqual(
          result.skipped.length,
          1,
          "existing hand-written file must be reported as skipped",
        );
        assert.strictEqual(
          result.skipped[0],
          eslintPath,
          "skipped entry should be the eslint.config.js path",
        );
      },
    );
  });

  it("should regenerate previously @generated file when template changes", async () => {
    await withTempWorkspace(
      "regen-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const stalePreviousBody =
          "// old generated body\nexport default [{ rules: {} }];\n";
        await fs.writeFile(
          eslintPath,
          `${GENERATED_MARKER_LINE}\n${stalePreviousBody}`,
          "utf8",
        );

        const newTemplate =
          "// refreshed generated body\nexport default [{ rules: { 'no-debugger': 'error' } }];\n";
        const manifest: Manifest = {
          monorepo: {
            workspaceDefaults: {
              eslint: { template: newTemplate },
            },
          },
          bounded_contexts: [{ name: "regen-pkg" }],
        };
        const config = makeConfig(workspaceRoot, manifest);

        const result = await generateEslintConfig(
          path.dirname(eslintPath),
          "regen-pkg",
          config,
        );

        assert.strictEqual(
          result.updated.length,
          1,
          "stale @generated file should be reported as updated",
        );
        assert.strictEqual(
          result.updated[0],
          eslintPath,
          "updated entry should be the eslint.config.js path",
        );
        assert.strictEqual(
          result.created.length,
          0,
          "regeneration must not be reported as created",
        );

        const onDisk = await fs.readFile(eslintPath, "utf8");
        assert.strictEqual(
          onDisk,
          `${GENERATED_MARKER_LINE}\n${newTemplate}`,
          "file on disk should reflect the new template body",
        );
        assert.ok(
          !onDisk.includes("old generated body"),
          "stale template body must be fully replaced",
        );
      },
    );
  });

  it("should interpolate {packageName} and {scope}", async () => {
    await withTempWorkspace(
      "interp-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const template =
          "// eslint for {packageName} in {scope}\nexport default { name: '{scope}/{packageName}' };\n";
        const manifest: Manifest = {
          scope: "acme",
          monorepo: {
            workspaceDefaults: {
              eslint: { template },
            },
          },
          bounded_contexts: [{ name: "interp-pkg" }],
        };
        const logger = makeCapturedLogger();
        const config = makeConfig(workspaceRoot, manifest, logger);

        await generateEslintConfig(
          path.dirname(eslintPath),
          "interp-pkg",
          config,
        );

        const content = await fs.readFile(eslintPath, "utf8");
        assert.ok(
          content.includes("// eslint for interp-pkg in acme"),
          "{packageName} and {scope} should both interpolate in comments",
        );
        assert.ok(
          content.includes("name: 'acme/interp-pkg'"),
          "{scope}/{packageName} should interpolate in the config body",
        );
        assert.ok(
          !content.includes("{packageName}"),
          "{packageName} placeholder must be fully resolved",
        );
        assert.ok(
          !content.includes("{scope}"),
          "{scope} placeholder must be fully resolved",
        );
        assert.strictEqual(
          logger.warns.length,
          0,
          "resolved placeholders must not emit interpolation warnings",
        );
      },
    );
  });

  it("should log error and skip gracefully for empty template", async () => {
    await withTempWorkspace(
      "empty-pkg",
      async ({ workspaceRoot, eslintPath }) => {
        const manifest: Manifest = {
          bounded_contexts: [
            {
              name: "empty-pkg",
              generator: {
                eslint: { template: "" },
              },
            },
          ],
        };
        const logger = makeCapturedLogger();
        const config = makeConfig(workspaceRoot, manifest, logger);

        const result = await generateEslintConfig(
          path.dirname(eslintPath),
          "empty-pkg",
          config,
        );

        assert.strictEqual(
          result.created.length,
          0,
          "empty-template run must not create any files",
        );
        assert.strictEqual(
          result.updated.length,
          0,
          "empty-template run must not update any files",
        );
        assert.strictEqual(
          result.skipped.length,
          1,
          "empty-template run must report the file as skipped",
        );
        assert.strictEqual(
          result.skipped[0],
          eslintPath,
          "skipped entry should be the eslint.config.js path",
        );
        assert.ok(
          typeof result.summary === "string" &&
            result.summary.includes("empty-pkg"),
          "result.summary should mention the module name",
        );

        await assert.rejects(
          fs.access(eslintPath),
          (err: NodeJS.ErrnoException) => err.code === "ENOENT",
          "no eslint.config.js should be written when the template is empty",
        );

        assert.ok(
          logger.errors.some((msg) =>
            msg.includes("No eslint template resolved for empty-pkg"),
          ),
          "generator should log an explicit error for the empty-template case",
        );
      },
    );
  });
});
