/**
 * 6.7(a) companion: unused layers no longer emit export {} barrels.
 * CLI hexagen sync is self-regen, so generateSharedKernel does not run.
 * A package still ships tsconfig include src/ — tsc TS18003 if src/
 * is empty. Write-if-absent src/index.ts is the package entry, not a layer.
 */
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { ensurePackageSrcIndex } from "../../src/generators/package-src-index.js";
import type { SyncConfig, LoggerPort } from "../../src/config.js";

const silentLogger: LoggerPort = {
  error: () => {},
  warn: () => {},
  info: () => {},
  debug: () => {},
  errorWithException: () => {},
};

function makeConfig(
  workspaceRoot: string,
  overrides: Partial<SyncConfig> = {},
): SyncConfig {
  return {
    dryRun: false,
    force: false,
    forceRoot: false,
    allowDirty: false,
    strict: false,
    mode: "self-regen",
    logger: silentLogger,
    manifest: {},
    workspaceRoot,
    ...overrides,
  };
}

describe("ensurePackageSrcIndex", () => {
  it("writes a generated export {} stub when src/index.ts is absent (self-regen)", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "pkg-src-index-"));
    try {
      const moduleDir = path.join(root, "packages", "shared");
      const result = await ensurePackageSrcIndex(moduleDir, makeConfig(root));
      const entry = path.join(moduleDir, "src", "index.ts");
      const body = await fs.readFile(entry, "utf8");
      assert.ok(result.created.includes(entry) || result.created.length === 1);
      assert.match(body, /@generated by @hexagen\/sync/);
      assert.match(body, /export \{\};/);
    } finally {
      await fs.rm(root, { recursive: true, force: true });
    }
  });

  it("does not overwrite an existing package-root barrel", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "pkg-src-keep-"));
    try {
      const moduleDir = path.join(root, "packages", "shared");
      const entry = path.join(moduleDir, "src", "index.ts");
      await fs.mkdir(path.dirname(entry), { recursive: true });
      await fs.writeFile(entry, "export const keep = 1;\n");
      const result = await ensurePackageSrcIndex(moduleDir, makeConfig(root));
      assert.ok(result.skipped.includes(entry));
      assert.equal(
        await fs.readFile(entry, "utf8"),
        "export const keep = 1;\n",
      );
    } finally {
      await fs.rm(root, { recursive: true, force: true });
    }
  });

  it("does not mkdir on dry-run", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "pkg-src-dry-"));
    try {
      const moduleDir = path.join(root, "packages", "shared");
      await ensurePackageSrcIndex(
        moduleDir,
        makeConfig(root, { dryRun: true }),
      );
      await assert.rejects(fs.stat(path.join(moduleDir, "src", "index.ts")), {
        code: "ENOENT",
      });
    } finally {
      await fs.rm(root, { recursive: true, force: true });
    }
  });
});
