#!/usr/bin/env node
/**
 * Generates src/infrastructure/generated/template-bundle.generated.ts — the
 * manifests + file contents of every template, inlined so the web/serverless
 * materialization path needs no runtime filesystem access.
 *
 * Run: `yarn workspace @hexagen/template-engine gen:bundle`
 * The parity test (template-bundle.test.ts) fails CI if the committed module
 * diverges from templates/, so a new/changed template can't ship stale.
 */
/* eslint-disable no-console -- a CLI generation script; stdout is its interface */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildTemplateBundle,
  type TemplateBundle,
} from "../src/infrastructure/build-template-bundle.js";

const OUT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "infrastructure",
  "generated",
  "template-bundle.generated.ts",
);

/**
 * Double-stringify a value into a JS string literal holding its JSON, then
 * rewrite U+2028 / U+2029 (left raw by JSON.stringify, but only legal in JS
 * string literals since ES2019) to explicit \uXXXX escapes so the emitted
 * module is valid at any target.
 */
function jsStringLiteral(value: unknown): string {
  let out = JSON.stringify(JSON.stringify(value));
  for (const code of [0x2028, 0x2029]) {
    out = out.split(String.fromCharCode(code)).join("\\u" + code.toString(16));
  }
  return out;
}

function emit(bundle: TemplateBundle): string {
  // Embed as JSON.parse("...") rather than object literals: the values contain
  // `${...}` / backticks / quotes from template sources, and this also avoids
  // tsc structurally type-checking a ~0.6 MB literal.
  const manifests = jsStringLiteral(bundle.manifests);
  const files = jsStringLiteral(bundle.files);
  return [
    "/* eslint-disable */",
    "// @generated by scripts/generate-template-bundle.ts — DO NOT EDIT.",
    "// Regenerate: `yarn workspace @hexagen/template-engine gen:bundle`",
    'import type { TemplateManifest } from "../../domain/index.js";',
    "",
    "/** All template manifests (validated at generation time). */",
    `export const TEMPLATE_MANIFESTS: TemplateManifest[] = JSON.parse(${manifests});`,
    "",
    '/** Every template source file: "<id>/<relPathInFilesDir>" → raw content. */',
    `export const TEMPLATE_FILES: Record<string, string> = JSON.parse(${files});`,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const bundle = await buildTemplateBundle();
  await fs.mkdir(path.dirname(OUT), { recursive: true });
  await fs.writeFile(OUT, emit(bundle), "utf-8");
  console.log(
    `Wrote ${path.relative(process.cwd(), OUT)} — ${bundle.manifests.length} manifests, ${Object.keys(bundle.files).length} files`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
