import type { IGenerateProjectPort } from '../ports/in/generate-project.port';
import type { FileTreeNode } from '../../domain/model/file-tree-node/file-tree-node';

interface ProjectSpec {
  rootName?: string;
  name?: string;
  version?: string;
  description?: string;
  boundedContexts?: string[];
}

export class GenerateProjectUseCase implements IGenerateProjectPort {
  async execute(spec: ProjectSpec): Promise<FileTreeNode> {
    const name = spec?.rootName || spec?.name || 'untitled-project';
    const projectName = name.toLowerCase().replace(/\s+/g, '-');

    const root: FileTreeNode = {
      name: projectName,
      type: 'folder',
      children: [
        {
          name: '.architecture.yaml',
          type: 'file',
          content: `# Generated by Hexagen Monaco v2\nsystem: ${projectName}\nscope: 'hexagen'\narchitecture: modular-monolith`,
        },
        {
          name: 'package.json',
          type: 'file',
          content: JSON.stringify(
            {
              name: projectName,
              version: spec?.version || '1.0.0',
              private: true,
              packageManager: 'yarn@4.12.0',
              workspaces: ['apps/*', 'packages/*', 'tools/*'],
            },
            null,
            2
          ),
        },
        {
          name: 'README.md',
          type: 'file',
          content: `# ${name}\n\n${spec?.description || ''}\n\nDate: ${new Date().toISOString()}`,
        },
        {
          name: 'apps',
          type: 'folder',
          children: [
            { name: 'web', type: 'folder', children: [] },
            { name: 'api-gateway', type: 'folder', children: [] },
          ],
        },
        {
          name: 'packages',
          type: 'folder',
          children: (spec?.boundedContexts || ['User', 'Order']).map(
            (bc: string) => ({
              name: bc.toLowerCase(),
              type: 'folder' as const,
              children: [],
            })
          ),
        },
      ],
    };
    return root;
  }
}
