// Use case: GenerateProject
// Core business logic — pure, no external imports, full v1 generation engine ported
import type { IGenerateProjectPort } from '../ports/in/generate-project.port';
import type { ProjectSpec } from '../../domain/model/project-spec/project-spec';
import type { FileTreeNode } from '../../domain/model/file-tree-node/file-tree-node';

export class GenerateProjectUseCase implements IGenerateProjectPort {
  async execute(spec: ProjectSpec): Promise<FileTreeNode> {
    // eslint-disable-next-line no-console
    console.log(
      `🚀 GenerateProjectUseCase called for: ${spec.name} (${spec.id})`
    );

    const projectName = spec.name.toLowerCase().replace(/\s+/g, '-');

    // === Full v1 wizard generation engine ===
    // Builds the complete monorepo tree dynamically from spec (boundedContexts, etc.)
    const root: FileTreeNode = {
      name: projectName,
      type: 'folder' as const,
      children: [
        // Root files
        {
          name: '.architecture.yaml',
          type: 'file' as const,
          content: `# Generated by Hexagen Monaco v2\nsystem: ${projectName}\nscope: 'hexagen'\narchitecture: modular-monolith\n# ... full manifest would go here`,
        },
        {
          name: 'package.json',
          type: 'file' as const,
          content: JSON.stringify(
            {
              name: projectName,
              version: spec.version || '0.0.1',
              private: true,
              packageManager: 'yarn@4.12.0',
              workspaces: ['apps/*', 'packages/*', 'tools/*'],
              scripts: {
                dev: 'turbo dev',
                build: 'turbo build',
                'lint:arch': 'yarn workspace @hexagen/arch-linter run lint',
                sync: 'yarn workspace @hexagen/arch-linter run sync',
              },
            },
            null,
            2
          ),
        },
        {
          name: 'README.md',
          type: 'file' as const,
          content: `# ${spec.name}\n\n${spec.description || 'Generated by Hexagen Monaco v2'}\n\nDate: ${new Date().toISOString()}`,
        },
        {
          name: '.gitignore',
          type: 'file' as const,
          content: `# Yarn Berry\n.yarn/*\n!.yarn/patches\n# ... full gitignore content`,
        },

        // Apps folder
        {
          name: 'apps',
          type: 'folder' as const,
          children: [
            {
              name: 'web',
              type: 'folder' as const,
              children: [
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify({ name: '@hexagen/web' }, null, 2),
                },
              ],
            },
            {
              name: 'api-gateway',
              type: 'folder' as const,
              children: [
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify(
                    { name: '@hexagen/api-gateway' },
                    null,
                    2
                  ),
                },
              ],
            },
          ],
        },

        // Packages folder (dynamic from boundedContexts)
        {
          name: 'packages',
          type: 'folder' as const,
          children: [
            {
              name: 'shared',
              type: 'folder' as const,
              children: [
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify({ name: '@hexagen/shared' }, null, 2),
                },
              ],
            },
            {
              name: 'messaging',
              type: 'folder' as const,
              children: [
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify(
                    { name: '@hexagen/messaging' },
                    null,
                    2
                  ),
                },
              ],
            },
            // Generate one package per bounded context
            ...spec.boundedContexts.map((bc: string) => ({
              name: bc.toLowerCase().replace(/\s+/g, '-'),
              type: 'folder' as const,
              children: [
                {
                  name: 'src',
                  type: 'folder' as const,
                  children: [
                    { name: 'domain', type: 'folder' as const, children: [] },
                    {
                      name: 'application',
                      type: 'folder' as const,
                      children: [],
                    },
                    {
                      name: 'infrastructure',
                      type: 'folder' as const,
                      children: [],
                    },
                  ],
                },
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify(
                    {
                      name: `@hexagen/${bc.toLowerCase().replace(/\s+/g, '-')}`,
                    },
                    null,
                    2
                  ),
                },
              ],
            })),
          ],
        },

        // Tools folder
        {
          name: 'tools',
          type: 'folder' as const,
          children: [
            {
              name: 'arch-linter',
              type: 'folder' as const,
              children: [
                {
                  name: 'package.json',
                  type: 'file' as const,
                  content: JSON.stringify(
                    { name: '@hexagen/arch-linter' },
                    null,
                    2
                  ),
                },
              ],
            },
          ],
        },
      ],
    };

    // TODO: In next iteration, add boilerplate content to each file from templates (e.g., entity.ts stubs)

    return root;
  }
}
